### ISSUE TITLE
Failed to create File Store directory Error:mkdir : The system cannot find the path specified.

### ISSUE THREAD

**Issue by frenchyjef** [Azure/azure-container-networking#104]
Running the new azure-vnet-plugin.exe 1.0.3 on my Windows 10 Azure VM gives me the below error...

```
C:\temp\azure-vnet-cnm-windows-amd64-v1.0.3>azure-vnet-plugin.exe
Failed to create File Store directory Error:mkdir : The system cannot find the path specified.
```
Also, am I supposed to set the --api-url argument? What value should go there?

Thanks,
J-F

**Comment by sharmasushant** [comment]
Closing as this is now fixed in latest release.
