### ISSUE TITLE
NPM blocks graceful shutdown connections for pods in Terminating state

### ISSUE THREAD

**Issue by vakalapa** [Azure/azure-container-networking#1066]
**What happened:**  
When a Pod is deleted, NPM does not allow any grace period and removes pod ip from all relevant IPSets resulting in blocking of graceful shutdown connections.

**What you expected to happen:**  
NPM Should not delete pod as soon as an update event comes with deletionTimeStamp set, it should wait until the delete event is called or wait for the  terminationGracePeriodSeconds to expire.

**How to reproduce it:**  
Check the linked issue for repro details.

**Comment by jakubneubauer** [comment]
@JungukCho Please can you help me with upgrading? We have AKS with Kubernetes v 1.22.4, Running more than year. I still can see the azure-npm pods with version v1.4.9. How can I achieve newer version to be used? I thought that this is managed by Azure AKS transparently.
