### ISSUE TITLE
Azure IPAM allocates subnet per pod on the node if subnet is not specified in network config

### ISSUE THREAD

**Issue by abhi** [Azure/azure-container-networking#111]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**Which release version?**:
I tried on azure v1.0.2

**Which componenet (CNI/IPAM/CNM/CNS)**:
CNI IPAM

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

**What happened**:
As explained in the PR https://github.com/Azure/azure-container-networking/pull/105, azure ipam fails to allocate IPs from second pods onwards on nodes if the subnet in the network config is not set.

**What you expected to happen**:
Azure to allocate a pool if its not allocated and then allocate an ip for every pod from the pool.

**How to reproduce it** (as minimally and precisely as possible):
1) Create a vnet 172.17.0.0/16
2) Create 3 subnets in the vnet 172.17.1.0/24, 172.17.2.0/24 , 172.17.3.0/24
<img width="631" alt="screen shot 2018-04-02 at 2 42 28 pm" src="https://user-images.githubusercontent.com/784144/38217720-36a16cd0-3684-11e8-9818-a691d809abe7.png">

2) Create 3 Linux VMs on Azure and attach VM1 to default subnet , VM2 ucp-subnet, VM3 linux-subnet.
So the azure metadata servers on each of the VMs now have access to the /24 subnet its attached to.
3) Install kubernetes using kubeadm
4) Now that kubernetes is running , copy the azure-vnet-ipam binary to cni directory.
5) Deploy Calico cni and point the ipam to azure-vnet-ipam. Here is the calico.yaml I used.
https://gist.github.com/abhi/b752cc662297c12b9780c0297d16181b
Note the only change in this yaml from standard calico yaml is the ipam is set to azure-vnet-ipam and the address pool for calico is set to the main address pool 172.17.0.0/16 (Though this is not relevant in my setup).
6) Now that cni and ipam plugins are deploy. Kubernetes is ready for deployment.
```
kubectl get nodes
NAME           STATUS     ROLES     AGE       VERSION
abhi-cali-1    Ready      master    49m       v1.10.0
abhi-cali-2   NotReady   <none>    48m       v1.10.0
abhi-cali-3    Ready      <none>    48m       v1.10.0
```
 7) Deploy pods ```kubectl run curl-image6 --image=sequenceiq/alpine-curl --replicas=10 -- sleep 900000```
8) 
```
kubectl get pods -o wide
NAME                           READY     STATUS              RESTARTS   AGE       IP            NODE
curl-image6-55f998f9cb-29b64   0/1       ContainerCreating   0          16m       <none>        abhi-cali-3
curl-image6-55f998f9cb-4n8g8   0/1       ContainerCreating   0          16m       <none>        abhi-cali-3
curl-image6-55f998f9cb-9q9qx   0/1       ContainerCreating   0          16m       <none>        abhi-cali-2
curl-image6-55f998f9cb-dfw8f   0/1       ContainerCreating   0          16m       <none>        abhi-cali-2
curl-image6-55f998f9cb-fsgh6   0/1       ContainerCreating   0          16m       <none>        abhi-cali-3
curl-image6-55f998f9cb-fwwq4   0/1       ContainerCreating   0          16m       <none>        abhi-cali-3
curl-image6-55f998f9cb-mlh5s   0/1       ContainerCreating   0          16m       <none>        abhi-cali-2
curl-image6-55f998f9cb-p9zff   1/1       Running             0          16m       172.17.2.80   abhi-cali-3
curl-image6-55f998f9cb-w5t2d   1/1       Running             0          16m       172.17.0.62   abhi-cali-2
curl-image6-55f998f9cb-zt77x   0/1       ContainerCreating   0          16m       <none>        abhi-cali-2
```
Logs from azure ipam on of the nodes where the second pod failed
```
2018/04/02 21:36:46 [cni-ipam] Plugin started.
2018/04/02 21:36:46 [cni-ipam] Processing ADD command with args {ContainerID:0aafa74c66f31f16254a86429e79b4ed0cb7f61a05bffa99ea31239baabc022a Netns:/proc/105794/ns/net IfName:eth0 Args:IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=curl-image6-55f998f9cb-mlh5s;K8S_POD_INFRA_CONTAINER_ID=0aafa74c66f31f16254a86429e79b4ed0cb7f61a05bffa99ea31239baabc022a Path:/opt/calico/bin:/opt/cni/bin}.
2018/04/02 21:36:46 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:k8s-pod-network Type:calico Mode: Master: Bridge: LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:}}.
2018/04/02 21:36:46 [ipam] Starting source azure.
2018/04/02 21:36:46 [ipam] Refreshing address source.
2018/04/02 21:36:46 [ipam] Save succeeded.
2018/04/02 21:36:46 [ipam] Requesting pool with poolId: options:map[azure.interface.name:] v6:false.
2018/04/02 21:36:46 [ipam] Checking pool 172.17.0.0/24.
2018/04/02 21:36:46 [ipam] Pool is in use.
2018/04/02 21:36:46 [ipam] Pool request completed with pool:<nil> err:No available address pools.
2018/04/02 21:36:46 [azure-vnet-ipam] Failed to allocate pool: No available address pools.
2018/04/02 21:36:46 [cni-ipam] ADD command completed with result:<nil> err:Failed to allocate pool: No available address pools.
2018/04/02 21:36:46 [cni-ipam] Plugin stopped.
```

**Anything else we need to know**:

**Comment by abhi** [comment]
ping @sharmasushant

**Comment by tamilmani1989** [comment]
@abhi It looks like you already requested a pool and got poolid and so the pool will be marked in use. In your subsequent requests you have to pass poolid that you received to get ips from the pool. Unless you release the pool, you can't allocate ips from the pool. BTW how did you endup in such scenario?  Did azure-vnet-ipam already run and you restarted it?

**Comment by abhi** [comment]
@tamilmani1989 I opened this PR https://github.com/Azure/azure-container-networking/pull/105 and I have added the explanation. From @sharmasushant discussion it looks this is a bug in Azure IPAM. I am not sure why a CNI plugin would pass a pool id to the IPAM plugin. 
When you say pool id are u talking about ``` subnet``` ? I have listed complete set of steps that anyone can reproduce the issue with. I did a code walk through and it looks pretty straightforward. If subnet is not set a new pool is allocated. Hence I open a PR to add another mechanism to allocate IP from "any" available subnet.

**Comment by ozdanborne** [comment]
>In your subsequent requests you have to pass poolid that you received to get ips from the pool

I think the issue is that this^ is not a part of the official CNI spec, so other CNI plugins won't do it. For the Azure IPAM plugin to be compatible with other CNI plugins (like Calico's), it needs to be able to be called subsequently without the "poolid".

**Comment by ashvindeodhar** [comment]
We don't plan to make this change at this point. We will reconsider if needed in future.

**Comment by selansen** [comment]
Is there any specific reason why this issue is not getting addressed ?
