### ISSUE TITLE
When using Multus - CNI err:Failed to allocate pool: No available address pools.

### ISSUE THREAD

**Issue by VasylR** [Azure/azure-container-networking#1132]
**What happened:** 

When we try to deploy multus with Azure CNI, eth1 is completely ignored by the Azure CNI plugin and as the result it is not possible to attach second interface to a pod. 

This is the error from /var/log/azure-vnet.log

2021/11/25 03:52:58 [4061] [cni-net] Processing ADD command with args {ContainerID:9ae31f5f156f2b5a134ba93c7ce37ff69344ec5458de2b004275dbcd989134dc Netns:/proc/3956/ns/net IfName:net1 Args:IgnoreUnknown=true;K8S_POD_NAMESPACE=default;K8S_POD_NAME=vcu-pod;K8S_POD_INFRA_CONTAINER_ID=9ae31f5f156f2b5a134ba93c7ce37ff69344ec5458de2b004275dbcd989134dc;K8S_POD_UID= Path:/opt/cni/bin:/opt/cni/bin StdinData:{"bridge":"azure2","cniVersion":"0.3.1","ipam":{"environment":"azure","type":"azure-vnet-ipam"},"logLevel":"info","master":"eth1","name":"azure222","type":"azure-vnet"}}.
2021/11/25 03:52:58 [4061] [cni-net] Read network configuration &{CNIVersion:0.3.1 Name:azure222 Type:azure-vnet Mode: Master:eth1 Bridge:azure2 LogLevel:info LogTarget: InfraVnetAddressSpace: IPV6Mode: ServiceCidrs: VnetCidrs: PodNamespaceForDualNetwork:[] IPsToRouteViaHost:[] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false DisableHairpinOnHostInterface:false DisableIPTableLock:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment:azure AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.

2021/11/25 03:52:58 [4061] Get number of endpoints for ifname eth0 network azure222

2021/11/25 03:52:58 [4061] Result from multitenancy <nil>
2021/11/25 03:52:58 [4061] [cni-net] Creating network azure222.
2021/11/25 03:52:58 [4061] [cni] Calling plugin azure-vnet-ipam ADD nwCfg:&{CNIVersion:0.3.1 Name:azure222 Type:azure-vnet Mode: Master:eth1 Bridge:azure2 LogLevel:info LogTarget: InfraVnetAddressSpace: IPV6Mode: ServiceCidrs: VnetCidrs: PodNamespaceForDualNetwork:[] IPsToRouteViaHost:[] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false DisableHairpinOnHostInterface:false DisableIPTableLock:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment:azure AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} AdditionalArgs:[]}.
2021/11/25 03:52:58 [4061] [cni] Plugin azure-vnet-ipam returned result:<nil>, err:Failed to allocate pool: No available address pools.
2021/11/25 03:52:58 [4061] [azure-vnet] Failed to allocate pool: Failed to delegate: Failed to allocate pool: No available address pools.
2021/11/25 03:52:58 [4061] [cni-net] ADD command completed with result:Interfaces:[{Name:net1 Mac: Sandbox:}], DNS:{Nameservers:[] Domain: Search:[] Options:[]} err:Failed to allocate pool: Failed to delegate: Failed to allocate pool: No available address pools.
2021/11/25 03:52:58 [4061] Failed to execute network plugin, err:Failed to allocate pool: Failed to delegate: Failed to allocate pool: No available address pools.
2021/11/25 03:52:58 [4061] [cni-net] Plugin stopped.
2021/11/25 03:52:58 [4061] Report plugin error

**What you expected to happen:**  

Azure CNI should create a second network for eth1.

**How to reproduce it:**  

We have vnet 10.240.0.0/15 with two subnets 10.240.0.0/16 and 10.241.0.0/16. 

Here is the AKS-engine config. 
{
    "apiVersion": "vlabs",
    "properties": {
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "ACSKubeMaster",
            "vmSize": "Standard_DS2_v2",
            "vnetSubnetId": "vnetSubnetId": "/subscriptions/<reducted>/providers/Microsoft.Network/virtualNetworks/<reducted>/subnets/default",
            "firstConsecutiveStaticIP": "10.240.0.200",
            "vnetCidr": "10.240.0.0/15"
        },
        "agentPoolProfiles": [
            {
                "name": "k8sagentpoo1",
                "count": 2,
                "vmSize": "Standard_DS2_v2",
                "vnetSubnetId": "/subscriptions/<reducted>/providers/Microsoft.Network/virtualNetworks/<reducted>/subnets/default",
                "availabilityProfile": "VirtualMachineScaleSets"
            }
        ],
        "linuxProfile": {
            "adminUsername": "azureuser",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData":  "<reducted>"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "<reducted>",
            "secret": "<reducted>"
        }
    }
}

Multus was installed using this guide:

https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md#installation

When multus was deployed we modified vmss to add second NIC. Next, upgraded the vmss model to the latest version.

Deployed NAD.

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: default
spec:
  config: '
{
  "cniVersion": "0.3.1",
  "name": "azure222",
  "type": "azure-vnet",
  "master": "eth1",
  "bridge": "azure2",
  "logLevel": "info",
  "ipam": {
    "type": "azure-vnet-ipam",
    "environment": "azure"
  }
}
'

Deployed pod that uses the NAD

apiVersion: v1
kind: Pod
metadata:
  name: podA
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: podA
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
  nodeSelector:
    label: nodeA

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

Linux k8s-k8sagentpoo1-29370234-vmss000000 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

P.S. you have a typo in the command above. It should be uname -a.

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by MartinForReal** [comment]
IMO, multus configuration is not activated, please make sure the name of multus config will be listed before configuration of azure cni.

**Comment by SaschaJohn** [comment]
@VasylR did you ever get this working?
