### ISSUE TITLE
CNI/IPAM plugin on Ubuntu 17.10 breaks DNS

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-container-networking#118]
**Is this a request for help?**: 
---
yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**Which release version?**:
---
v1.0.3

**Which componenet (CNI/IPAM/CNM/CNS)**:
---
CNI/IPAM

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

**What happened**:
Activating the CNI plugin on Ubuntu 17.10 breaks name resolution (DNS). The switch from `eth0` to `azure0` leaves DNS in an unusable state. 

**What you expected to happen**:
DNS should continue to work

**How to reproduce it** (as minimally and precisely as possible):
1. Provision a Kubernetes cluster with an Ubuntu 17.10 node and CNI/IPAM configured
2. Schedule a pod
3. Pod starts to run and errors with `ErrImagePull` due to being unable to resolve `docker.io` to pull images

At this point, the node must be rebooted for DNS to work again.

**Anything else we need to know**:
Ubuntu 17.10 uses `systemd-resolved` as a caching, stub nameserver. More info here: http://manpages.ubuntu.com/manpages/xenial/man8/systemd-resolved.service.8.html

cc @lachie83

**Comment by seanknox** [comment]
Worse, tried on Ubuntu 16.10 and CNI/IPAM knocks the VM completely off the network.

**Comment by sharmasushant** [comment]
@seanknox is this a self managed k8s cluster, or setup via acs-engine? If you are using acs-engine, can you please share cluster config?

Also, is it kube-dns that breaks, or default azure dns, or are you specifying dns in your Vnet config?

**Comment by sharmasushant** [comment]
@seanknox if you are working on self manages cluster, please ensure you have ebtables installed on nodes before using cni. Otherwise, layer 2 operations fails and vm can loose connectivity.

**Comment by seanknox** [comment]
@sharmasushant it's a self-managed cluster (built using terraform: http://github.com/seanknox/acstack). layer 3 and layer 4 continues to work fine: I can ping and connect to sockets on the internet. the issue with Ubuntu 17.10 is DNS resolution fails once CNI kicks in on the node.

**Comment by seanknox** [comment]
@sharadagarwal do you need any additional information? Considering the gravity of the breakage this is a big deal.

**Comment by sharadagarwal** [comment]
@seanknox did you mean to ask someone else?

**Comment by sharmasushant** [comment]
@saiyan86 can you take a look?
@seanknox can you please try v1.0.2 to unblock while we look at 1.0.3
v1.0.2 has been working well with ace-engine for some time now.

**Comment by seanknox** [comment]
@sharmasushant just tried v1.0.2 and same problem. Note that acs-engine uses Ubuntu 16.04-LTS, which is older.

**Comment by saiyan86** [comment]
@sharmasushant I just saw this. Will take a look.

**Comment by saiyan86** [comment]
This should come from a systemd bug: [Bug #1624320](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320)

**Comment by seanknox** [comment]
I don't think this is the case, as the bug refers to adding the local caching nameserver to a list of existing nameservers in `resolv.conf.` In my case, I'm only using the default nameserver that comes with Ubuntu 17.10 (`nameserver 127.0.0.53`).

**Comment by tamilmani1989** [comment]
@seanknox - Can you change nameserver to 168.63.129.16 in resolv.conf and check if its working? Also please share /var/log/azure-vnet.log and /var/log/azure-vnet-ipam.log

**Comment by sharmasushant** [comment]
@seanknox can you please share an update if your issue is still there?

**Comment by saiyan86** [comment]
Closing stale issue

**Comment by cpressland** [comment]
Could we reopen this? In my investigation of implementing Azure-CNI into our own cluster  #344 we've run into the same issue. I worked-around it with this:

```shell
apt -y install resolvconf

cat <<EOF | tee /etc/resolvconf/resolv.conf.d/head
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolv
conf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual namese
rvers.
nameserver 168.63.129.16
EOF

systemctl restart resolvconf.service
```

While the above works, it still feels like a hack.

**Comment by saiyan86** [comment]
@tamilmani1989 @cpressland would #345 fix this?

**Comment by cpressland** [comment]
Turned out it was actually much easier to solve than the above. The Kubelet has an option specifically for this and we've set it as follows in the Kubelet config YAML: `resolvConf: "/run/systemd/resolve/resolv.conf"`

**Comment by tamilmani1989** [comment]
@cpressland #345 should fix this.
