### ISSUE TITLE
The project is not vendored

### ISSUE THREAD

**Issue by jose-bigio** [Azure/azure-container-networking#124]
**Is this a request for help?**:

Not really

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**Which release version?**:
All versions
---

**Which componenet (CNI/IPAM/CNM/CNS)**:

All components

---

The dependencies that are being used to build binaries are not checked into this repository. 
For reproducible builds across forks, and over time it would be helpful to have the dependencies ( / libraries) vendored, and checked into this repository.

**Comment by jose-bigio** [comment]
Is this desirable for the project?

**Comment by sharmasushant** [comment]
@jose-bigio Sure. We can take a work item to get dependencies vendored in.
