### ISSUE TITLE
NetworkPolicy does not create correct iptables rules

### ISSUE THREAD

**Issue by mthebridge** [Azure/azure-container-networking#1256]
**What happened:**  

Using flux and gitops Helm to install Deployments and NetworkPolicy objects.  On one node, NPM failed to install the correct iptables rules and never retried.  Traffic was therefore blocked.

This is happening on ~50% of clusters we deploy in Uk South since yesterday afternoon.  We had not seen it before then, and nothing much has changed.

It appears that UK South was upgraded to v 1.4.18 of NPM yesterday, which seems suspicious.

**What you expected to happen:**  

Correct iptables rules installed, traffic not blocked.

**How to reproduce it:**  

Unclear.  Happens on ~50% of our deployments where we install this Helm chart onto a fresh AKS cluster.

**Kubernetes Version:**  
1.21.7

**Kernel (e.g. `uname -a`):**  
Linux aks-nodepool-16241653-vmss000000 5.4.0-1068-azure #71~18.04.1-Ubuntu SMP Thu Jan 20 08:21:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know?:**

I see error logs soon after the affected NetworkPolicy is created from NPM controller:

```
2022/02/21 13:59:44 [1] Error: There was an error running command: [iptables -w 60 -I AZURE-NPM-INGRESS-PORT -m set --match-set azure-npm-530439631 src -m set --match-set azure-npm-2403546470 src -m set --match-set azure-npm-515672145 dst -m set --match-set azure-npm-2167340500 dst -m set --match-set azure-npm-4283926721 dst -m set --match-set azure-npm-1159271841 dst -p TCP --dport 6692 -j MARK --set-mark 0x2000 -m comment --comment ALLOW-all-namespaces-AND-mvmtc-client:-AND-TCP-PORT-6692-TO-app:mvm-AND-release:mvm-mvm-AND-service:mvmtc-IN-ns-mvm] Stderr: [exit status 2, iptables v1.8.4 (legacy): Set azure-npm-4283926721 doesn't exist.
```

I have an internal Azure support ticket covering this issue - #2202220050002263 - but this feels so like an NPM bug I'm raising here as well.

**Comment by huntergregory** [comment]
Resolving a race condition for your cluster in #1257
