### ISSUE TITLE
[CNS] Duplicate IP

### ISSUE THREAD

**Issue by Pluggi** [Azure/azure-container-networking#1259]
**What happened:** 
After AzureCNS daemon-set restarted, several pods were running with the same IP, breaking all connectivity inside the cluster and generating multiple errors in azure-cns-xxxx pods.

**What you expected to happen:**  
After restarting, we would expect azure-cns to recover from its previous state and not re-use an already allocated podIp.

**How to reproduce it:**  
N/A

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
Kubernetes 1.20.9

**Operating System (Linux/Windows):**  
Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

Node pool image: AKSUbuntu-1804gen2containerd-2021.12.07

Linux version 5.4.0-1067-azure (buildd@lcy02-amd64-037) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #70~18.04.1-Ubuntu SMP Thu Jan 13 19:46:01 UTC 2022

**Anything else we need to know?:**

We found this issue because we lost all connectivity in our cluster. We still had access to the K8S API server so we were able to gather some infos.
This happened on 3 different clusters today (Feb 28th), and last month (Jan 28th) it happened on 5 clusters.
We found that azure-cns pods were all newly created and in version 1.4.15.

We made the issue go away by restarting all nodes of our cluster, to ensure that new pods would be scheduled and given new IPs.

Get all running pods and their associated IPs, and find duplicates:

```
$ kubectl get pods -o wide -A  | grep Running | grep -o '10\.11[^ ]*' | sort | uniq -c | grep '^   2'
   2 10.11.0.166
   2 10.11.0.174
   2 10.11.0.175
```

CNS logs:
```
2022/02/28 10:31:06 [1] Starting IPAM Pool Monitor
2022/02/28 10:31:06 [1] [ipam-pool-monitor] Starting CNS IPAM Pool Monitor
2022/02/28 10:31:06 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:31:06 [1] initializing CNS from CNI
2022/02/28 10:31:06 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:31:17 [1] initializing CNS from CNI
2022/02/28 10:31:17 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:31:18 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:31:38 [1] initializing CNS from CNI
2022/02/28 10:31:38 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:31:39 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:32:19 [1] initializing CNS from CNI
2022/02/28 10:32:19 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:32:19 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:33:19 [1] initializing CNS from CNI
2022/02/28 10:33:19 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:33:20 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:34:20 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:34:20 [1] initializing CNS from CNI
2022/02/28 10:34:21 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:35:21 [1] initializing CNS from CNI
2022/02/28 10:35:21 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:35:21 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:36:21 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:36:21 [1] initializing CNS from CNI
2022/02/28 10:36:22 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:37:22 [1] initializing CNS from CNI
2022/02/28 10:37:22 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:37:22 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:38:22 [1] initializing CNS from CNI
2022/02/28 10:38:22 [1] Setting cmd to CNI_COMMAND=GET_ENDPOINT_STATE
2022/02/28 10:38:23 [1] [Azure CNS] Failed to init cns with err: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
2022/02/28 10:38:23 [1] Failed to start CRD Controller, err:All attempts fail:
#1: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#2: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#3: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#4: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#5: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#6: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#7: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#8: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#9: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization
#10: failed to initialize CNS state: err in CNS initialization: 10.11.0.127: duplicate IP detected in CNS initialization.
```

We can provide the full log file if necessary.

**Comment by rbtr** [comment]
@Pluggi, thanks for the detailed report. I think we have already identified and fixed this issue in #1236, and it is rolling out with CNS [v1.4.19](https://github.com/Azure/azure-container-networking/releases/tag/v1.4.19). It should make it worldwide within a week or two.

**Comment by Pluggi** [comment]
I'm glad there is a fix for this issue!
What is the release process like? We are still running 1.4.15 on our K8S 1.20.9 cluster, which was released in November. Is it tied to Kubernetes' version? Can we update ourselves?

Additionally, are the pods restarting because of an update? Are there any mitigations we can implement until 1.4.19 is rolled out?

This bug is really critical to us and has a huge business impact since it basically breaks all networking.

**Comment by rbtr** [comment]
@Pluggi unfortunately you can't update it yourselves, the update process is owned by AKS. It's not related to the Kubernetes version, and it's not unusual to skip some CNS versions due to how our release and rollout processes work - 1.4.15 is the previous version that your cluster should have, so that is ok (except for it having this bug).
CNS v1.4.19 with the bugfix has started rolling out already - it is released region by region, so it will take some time to be available everywhere. Your cluster will automatically be upgraded when it hits your region.

I am not sure why your CNS pods restarted initially, but you should be able to mitigate this by restarting the problematic Nodes.
