### ISSUE TITLE
CNS & NPM port 10091 collision

### ISSUE THREAD

**Issue by kratkyzobak** [Azure/azure-container-networking#1268]
**What happened:** 
When NPM and CNS enabled in one cluster, CNS will occasionally fail to start and node become unusable (but ready - it's another long term issue).

CNS tries to publish metrics on port 10091 which is already in use by NPM as both are daemonsets which gets PodIP = NodeIP so them are sharing tcp stack.

**What you expected to happen:**  
Ability to use NPM and CNS on same cluster

**How to reproduce it:**  
Use AKS with NPM and CNS

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
AKS 1.21.9
NPM = 1.4.9
CNS = 1.4.15

**Operating System (Linux/Windows):**  
Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
I use workaround with deleting CNS and NPM pods on that node so they are rescheduled. If rescheduled in right order, CNS gets the port and NPM does not fail to start (but don't know it's state without possiiblity to take this port)

**Comment by rbtr** [comment]
this has been fixed
