### ISSUE TITLE
No pod connection, no internet

### ISSUE THREAD

**Issue by elchead** [Azure/azure-container-networking#1337]
**What happened:** 
I used calico CNI and switched to Azure CNI and got everything smoothly working. The next day, after VM restart, I could not connect to the network inside the pods anymore.

**What you expected to happen:**  
Pods can connect inside and outside the private net.

**How to reproduce it:**  
Set up Ubuntu (20.10 or 21.04) VM in private network (mine is 192.168.0.0/16).
 
 ```
apt update
apt install kubectl kubeadm kubelet containerd
alias k=kubectl
```
 
Install CNI plugin as described here for Kubernetes: https://docs.microsoft.com/en-us/azure/virtual-network/deploy-container-networking#download-and-install-the-plug-in:
```
./scripts/install-cni-plugin.sh v1.4.20 v1.0.1 (v1.4.23 does not work either)
```
 
```
kubeadm init --upload-certs  --cri-socket "/run/containerd/containerd.sock"
```
 
Pod cannot connect to Azure DNS:
```
root@jakob-k8s:/home/adrian# k logs -n kube-system coredns-64897985d-rz8t7
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[ERROR] plugin/errors: 2 6624486010305281932.1728699848247201413. HINFO: read udp 192.168.0.35:48232->168.63.129.16:53: i/o timeout
 ```

Pod cannot ping (e.g. VM IP) inside vnet:
```
kubectl taint nodes --all [node-role.kubernetes.io/master-](http://node-role.kubernetes.io/master-)
k run b --image busybox --rm -it
ping 192.168.0.20
 ```

Outbound connection is also not working inside the pod:
```
ping 8.8.8.8
```
 
When I applied source NAT rule:
```
iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 192.168.0.0/16 -j MASQUERADE
```
 
Not even the VM can connect to the internet nor private network anymore.
I need to remove the rule to make it work again:
```
iptables -t nat -D POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 192.168.0.0/16 -j MASQUERADE
```
 
I reproduced the issue on 2 different VMs in the same private net.
No firewall rules are applied inside the VM.

The log of the CNI plugin also looks suspicious. The CNI Plugin seems to stop soon after machine launch without any error:
```
root@kube-master-3:/home/adrian# tail -f /var/log/azure-vnet.log
2022/04/19 08:25:27 [16631] Get number of endpoints for ifname eth0 network azure
2022/04/19 08:25:27 [16631] Execution mode :
2022/04/19 08:25:27 [16631] Trying to retrieve endpoint id 6a2330fc-eth0
2022/04/19 08:25:27 [16631] [cni-net] Failed to query endpoint: Endpoint not found
2022/04/19 08:25:27 [16631] Release ip by ContainerID (endpoint not found):6a2330fcee50fcceef9481c4ee5b91ec02d9d520fd831a637e1a6673f8665874
2022/04/19 08:25:27 [16631] [cni] Calling plugin azure-vnet-ipam DEL nwCfg:&{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:transparent Master: AdapterName: Bridge: LogLevel: LogTarget: InfraVnetAddressSpace: IPV6Mode: ServiceCidrs: VnetCidrs: PodNamespaceForDualNetwork:[] IPsToRouteViaHost:[169.254.20.10] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false DisableHairpinOnHostInterface:false DisableIPTableLock:false CNSUrl: ExecutionMode: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:192.168.0.0/16 Address: QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} WindowsSettings:{EnableLoopbackDSR:false} AdditionalArgs:[]}.
2022/04/19 08:25:27 [16631] [cni] Plugin azure-vnet-ipam returned err:<nil>.
2022/04/19 08:25:27 [16631] [cni-net] DEL command completed for pod pdnsutilsm with err:<nil>.
2022/04/19 08:25:27 [16631] [cni-net] Plugin stopped.
2022/04/19 08:25:27 [16631] Released process lock
```

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
Kubernetes v1.23

**Operating System (Linux/Windows):**  
Ubuntu 20.10

**Kernel**
5.4.0-1068-azure
and 
5.11.0-1027-azure

**Anything else we need to know?:**
Azure support advised me to open an issue here.

When using Calico CNI, coredns service works in Kubernetes and I can ping pods on the same node and other VM IPs inside the private net, but pods on different nodes cannot communicate and internet inside pods also does not work.

**Comment by elchead** [comment]
> Reference

I reproduced the issue on another machine without Calico and I am not using AKS.

**Comment by elchead** [comment]
I reproduced the issue on another machine without Calico and I am not using AKS.

**Comment by tamilmani1989** [comment]
@elchead  can you check if ipforwarding enabled on your VM? `sysctl net.ipv4.ip_forward`
If enabled, can you paste output of  `sudo iptables -t filter -L FORWARD`
Also can you take packet capture of VM eth0. Run this cmd in VM `sudo tcpdump -ni eth0 -e icmp` and ping from pod. Destination should be vnet ip. It can be different VM ip or pod ip in different VM.

**Comment by elchead** [comment]
@tamilmani1989 ipforwarding is enabled. It's also enabled in the Azure network interface.

```
root@kube-master-3:/home/adrian# root@kube-master-3:/home/adrian# sudo iptables -t filter -L FORWARD
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
```

When pinging the vnet ip (of the VM running the pod) inside the pod, I don't receive any traffic

**Comment by elchead** [comment]
I gave up on Azure plugin, but got it to work with calico. Thanks for your help!
