### ISSUE TITLE
Will ipvlan and hardware offloading be used for Linux container networking in azure?

### ISSUE THREAD

**Issue by xukai286** [Azure/azure-container-networking#134]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature request
---

**Which release version?**:

---

**Which componenet (CNI/IPAM/CNM/CNS)**:
Cni
---

the current version uses Linux bridge to forward eth package. There’re so many implements can do this. Do we have a benchmark about Linux bridge vs ipvlan l2, macvtap...etc I saw some ipvlan code footprint in the repos. But why we don’ Use it?

Does azure have some plan to use ethcard to do some offloading to improve the container networking performance?

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
K8s cni

**What happened**:
Ebtables and software bridge

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by saiyan86** [comment]
Closing stale issue. Can revisit later if anything changes.
