### ISSUE TITLE
will vnet plugin support multi-subnet 

### ISSUE THREAD

**Issue by xukai286** [Azure/azure-container-networking#135]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**Which release version?**:
1.0.4
---

**Which componenet (CNI/IPAM/CNM/CNS)**:
CNI/IPAM
---

will vnet plugin support multi-subnet in a k8s cluster in acs-engine and aks?
do we have the roadmap

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by tamilmani1989** [comment]
@xukai286 Can you please eloborate the requirement with a scenario/usecase?

**Comment by xukai286** [comment]
yes.just like some pods and nodes have subnet A, and some pods on other  nodes have different subnet B. both subnet A and subnet B are in the same vnet.

**Comment by tamilmani1989** [comment]
Yes Azure CNI supports that. You can bring your own vnet and specify different subnets for different agent nodes in cluster config yaml  of acs-engine.

**Comment by xukai286** [comment]
yep.  I can bring my own subnets and my question is could acs-engine create and define multiple subnets and set route for them?

**Comment by tamilmani1989** [comment]
To my knowledge, ACS engine won't create multi subnets. If you use default cluster config, it will create a vnet and a subnet for you. If you want to have different subnet for each agent, then the only way is to bring your own subnets.

**Comment by sharmasushant** [comment]
I think the better place for this issue is github.com/azure/acs-engine
It will get better visibility over there.

**Comment by ashraf345** [comment]
i am having two different subnet i.e 172.16.1.0/24 and 172.16.2.0/24 on a single VM.
So is it possible to run 2 docker container on 2 different subnet using the CNI plugin by creating two different azure vnet.
Because while i am running azure-vnet plugin i am able to configure on one vnet on a single subnet and if i am trying for other subnet showing error that the address cannot be allocated.
