### ISSUE TITLE
default mode of Microsoft Azure Container Networking plugin

### ISSUE THREAD

**Issue by xukai286** [Azure/azure-container-networking#136]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**Which release version?**:
1.0.2
---

**Which componenet (CNI/IPAM/CNM/CNS)**:
cni
---

the configurations generated by acs-engine would just copy the file https://github.com/Azure/azure-container-networking/blob/master/cni/azure-linux.conflist.  which define the mode is bridge.
this make me confuse the docs in https://github.com/Azure/azure-container-networking/blob/master/docs/network.md  is mentioned that the tunnel is default.

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

**What happened**:
if I do nothing. the default mode is bridge

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by tamilmani1989** [comment]
@xukai286 - You are right. In CNM, the default mode is tunnel and in CNI, the conflist will define the mode as bridge. If nothing is defined in conflist, then the default option is tunnel. We will update the doc to be more clearer.

**Comment by saiyan86** [comment]
Closing stale issue. Can revisit later if anything changes.
