### ISSUE TITLE
Windows container not pulling DNS server from VNET

### ISSUE THREAD

**Issue by tlessard** [Azure/azure-container-networking#141]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**Which release version?**:

1.04

**Which componenet (CNI/IPAM/CNM/CNS)**:

CNM

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker  (Windows with Containers)

**What happened**:
Container receives IP address, subnet mask and gateway but not DNS servers from Azure Virtual Network

**What you expected to happen**:
Expected to have DNS servers set on vEthernet interface.

**How to reproduce it** (as minimally and precisely as possible):
1. Create Azure VM running Windows Server 2016 Datacenter with Containers image.
2. Execute azure-vnet-plugin.exe and create docker network named azure
3. Create "ip-config" in Azure Portal for NIC associated with Azure VM.
4. Create windowsservercore container using --network=azure
5. Connect to container PowerShell (docker exec -i containername powershell.exe)
6. Issue Get-DNSClientServerAddress command and note that IPv4 DNS servers are blank

**Anything else we need to know**:
I have not seen any other configuration in Azure ip-config settings that would allow me to specify DNS settings so I would assume the Virtual network DNS servers would be pulled.  The ip-config created in step 3 sets the address that the container pulls from the VNET.

thanks for any help.

**Comment by tlessard** [comment]
![image](https://user-images.githubusercontent.com/15464728/40125837-7a07becc-58f1-11e8-9df0-a8f069564d06.png)

**Comment by coreywagehoft** [comment]
Any updates on this @sharmasushant ?

**Comment by AceHack** [comment]
Yes any updates?

**Comment by tamilmani1989** [comment]
fixed this in #305
