### ISSUE TITLE
error response from daemon plugin azure-vnet not found

### ISSUE THREAD

**Issue by arunprasad3049** [Azure/azure-container-networking#1423]
**What happened:**  Installed azure cni plugin on standalone docker VM. Unable to create docker network with azure vnet.

**What you expected to happen:**  

**How to reproduce it:**  

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  redhat7.7 and Unbuntu 18.04

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rbtr** [comment]
Hi @arunprasad3049, could you provide some basic information on your setup including how you installed azure-vnet, how you are using it, how you have configured your env/docker/etc, the specific error(s) that you are getting, and anything else that you think might be useful here?
