### ISSUE TITLE
getting error while launching pods on cluster

### ISSUE THREAD

**Issue by rk365040** [Azure/azure-container-networking#1425]
**What happened:** 
 Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               22s   default-scheduler  Successfully assigned default/nginx-pod to ip-172-31-29-203
  Warning  FailedCreatePodSandBox  21s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9b2f37a7dfdbe85ad18efbc71c164a3054eb306c142cdec4d31f0f4026dbf1b3": open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  11s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "92cad9b6520dec70dc8c4780d4deb22fb0d22b25b2d7e8df16a9e0a9f01857a0": open /run/flannel/subnet.env: no such file or directory

**What you expected to happen:**  

**How to reproduce it:**  

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rbtr** [comment]
@rk365040 what platform is this? AKS? It looks like you have some flannel misconfiguration, is it possible this is not related to azcni?
