### ISSUE TITLE
mac " 12:34:56:78:9a:bc" in tunnel mode of CNI

### ISSUE THREAD

**Issue by xukai286** [Azure/azure-container-networking#144]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:
ALL
---

**Which componenet (CNI/IPAM/CNM/CNS)**:
CNI
---

in the k8s cni plugin. if I use the tunnel mode.
2 nodes and 4 pods:
azureuser@k8s-master-34676867-0:~$ kubectl  get  pods -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP            NODE
nginx-7c87f569d-2222p   1/1       Running   0          30s       10.240.0.81   k8s-agentpool1-34676867-0
nginx-7c87f569d-lhh7p   1/1       Running   0          30s       10.240.0.43   k8s-agentpool1-34676867-1
nginx-7c87f569d-nhh4t   1/1       Running   0          30s       10.240.0.86   k8s-agentpool1-34676867-0
nginx-7c87f569d-zndr2   1/1       Running   0          30s       10.240.0.55   k8s-agentpool1-34676867-1

the ebtables will be like:
root@k8s-agentpool1-34676867-1:~# ebtables -t nat -L
Bridge table: nat

Bridge chain: PREROUTING, entries: 11, policy: ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.240.0.34 -j arpreply --arpreply-mac 0:d:3a:30:47:42
-p ARP -i eth0 --arp-op Reply -j dnat --to-dst ff:ff:ff:ff:ff:ff --dnat-target ACCEPT
-i az+ -j dnat --to-dst 12:34:56:78:9a:bc --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.240.0.45 -j arpreply --arpreply-mac 12:34:56:78:9a:bc
-p IPv4 -i eth0 --ip-dst 10.240.0.45 -j dnat --to-dst da:63:e7:2e:d0:be --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.240.0.37 -j arpreply --arpreply-mac 12:34:56:78:9a:bc
-p IPv4 -i eth0 --ip-dst 10.240.0.37 -j dnat --to-dst ce:b9:fd:c5:36:79 --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.240.0.43 -j arpreply --arpreply-mac 12:34:56:78:9a:bc
-p IPv4 -i eth0 --ip-dst 10.240.0.43 -j dnat --to-dst 3e:90:86:28:e5:39 --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.240.0.55 -j arpreply --arpreply-mac 12:34:56:78:9a:bc
-p IPv4 -i eth0 --ip-dst 10.240.0.55 -j dnat --to-dst 86:f9:28:da:36:27 --dnat-target ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT

Bridge chain: POSTROUTING, entries: 1, policy: ACCEPT
-s Unicast -o eth0 -j snat --to-src 0:d:3a:30:47:42 --snat-arp --snat-target ACCEPT

all the traffic between pods in the same host will go to the -to-dst 12:34:56:78:9a:bc
-i az+ -j dnat --to-dst 12:34:56:78:9a:bc --dnat-target ACCEPT

and all the arp reply from pods will also be 12:34:56:78:9a:bc

what's the 12:34:56:78:9a:bc ,Is it the  a special device in the azure VFP?

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sharmasushant** [comment]
@xukai286 The value 12:34:56:78:9a:bc is what Azure platform returns in the ARP response when a VM sends the ARP request for any ip-address in the virtual network.
