### ISSUE TITLE
kube-dns should be first and only DNS server for Windows pods

### ISSUE THREAD

**Issue by PatrickLang** [Azure/azure-container-networking#147]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**Which release version?**: v1.0.3

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**:

Windows Server version 1803

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

**What happened**:

168.x.x.x was first in the DNS server list. It can't resolve DNS within the k8s cluster.

**What you expected to happen**:

On Linux, 10.0.0.10 is the first and only server. This should be the same on Windows

```
/etc # cat resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local lje1130gi5iehkdbexza4ptcba.xx.internal.cloudapp.net
```

**How to reproduce it** (as minimally and precisely as possible):
Deploy a Windows cluster using acs-engine v0.17

**Comment by sharmasushant** [comment]
#155 fixes this
