### ISSUE TITLE
Bring your own CNI general availability 

### ISSUE THREAD

**Issue by allensiho** [Azure/azure-container-networking#1488]
**Component (Azure NPM or Azure CNI):**

**Describe in detail the feature/behavior/change you'd like to see:**  

**Orchestrator(e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

**Comment by allensiho** [comment]
Hi,

When is it expected that this feature will be released as General availability. 

I work like to see if Cilium is a good fit.
Thanks

**Comment by rbtr** [comment]
This repo is for Azure CNI, if you are looking for information on AKS features I suggest you check [Azure/AKS](https://github.com/azure/aks).
