### ISSUE TITLE
Azure-NPM: Requests and Limits Are Configured Too High

### ISSUE THREAD

**Issue by johnbailey-transactcampus** [Azure/azure-container-networking#1509]
**What happened:**
azure-npm instances requested 250m, per instance, and this consumes  a "considerable" (relatively speaking) amount of CPU (3 instances means 750m of CPU).

`kube-system:azure-npm-4s9ws azure-npm:250m`
`kube-system:azure-npm-n5gq7 azure-npm:250m`
`kube-system:azure-npm-w2rh7 azure-npm:250m`

**What you expected to happen:**  
Since CPU usage peaks at around 0.0075m within the cluster, I would expect the limits to be far lower - reflecting where they are defined [elsewhere](https://github.com/Azure/aks-engine/blob/a76a7e840da13d2026cbfcda4a593901988f4612/pkg/api/addons.go#L341).

![image](https://user-images.githubusercontent.com/84570553/182859084-3855c867-0b5a-4121-9e16-404ca62319a9.png)

**How to reproduce it:**  
Create an AKS cluster, add AAD Identity PODs. 

**Kubernetes Version:**  
1.23.5

**Kernel (e.g. `uname -a`):**  
`Linux aks-default-22527922-vmss000078 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

Previous Instance[s]: This was reported, previously, [here](https://github.com/Azure/AKS/issues/2033) but it was under AKS, so you might not have had visibility.
Root-cause:  Appears to be [here](https://github.com/Azure/azure-container-networking/blob/master/npm/azure-npm.yaml#L85).

**Comment by 0xakihiko** [comment]
So the old topic was closed as solved, when it wasn't.

And this still exists, without seemingly the ability to override it. 

This is costing people unnecessarily large amounts of money, and consuming way more resources than it should. I guess that's why they aren't prioritizing what seems to be a simple fix?
