### ISSUE TITLE
CNM, --ipam-query-url switch missing from cmd

### ISSUE THREAD

**Issue by olljanat** [Azure/azure-container-networking#151]
**Is this a request for help?**:
Yes

**Which release version?**:
v1.0.3

**Which component (CNI/IPAM/CNM/CNS)**:
CNM

**Which environment (Azure/MAS)**
MAS

**Which Operating System (Linux/Windows)**:
Windows, 10.0.17134.1 (WinBuild.160101.0800)

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker CE 18.03.1-ce

**What happened**:
Not able to get subnets from MAS as it not listening hardcoded http://169.254.169.254:6642/ListNetwork address and there is no cmd option to specify this.

**What you expected to happen**:
To be able to specify correct URL using --ipam-query-url cmd switch.

**How to reproduce it** (as minimally and precisely as possible):
- Look [docs/cnm.md](https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md) and see that there is no --ipam-query-url switch available.
- Look [ipam/mas.go](https://github.com/Azure/azure-container-networking/blob/master/ipam/mas.go) and see that hardcoded masQueryUrl will be used if anything else is not specified.

**Anything else we need to know**:
I implemented fix to this one already on #140 but it is waiting for review.

**Comment by tamilmani1989** [comment]
@olljanat  Approved the PR. We will merge and release in next few days.
