### ISSUE TITLE
Add PR build jobs to test the code before merge

### ISSUE THREAD

**Issue by andrewhsu** [Azure/azure-container-networking#170]
**Is this a request for help?** : Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

**Which release version?**: all future versions

**Which component (CNI/IPAM/CNM/CNS)**: all

**Which Operating System (Linux/Windows)**: all

**Which Orchestrator and version (e.g. Kubernetes, Docker)**: N/A

**What happened**: On PRs to this repo, there are no tests run automatically.

**What you expected to happen**: PR build jobs to verify the code of the PR before merge.

**How to reproduce it** (as minimally and precisely as possible): Open a PR to this repo.

**Anything else we need to know**

Having PR build jobs will help prove new code works as expected and prevent regressions. I see this repo has code that is desired to execute on windows and linux. For contributors who only develop on one of those systems, the PR build job will also help double-check the code works on the other system.

Basic tests:
* unit tests (`go test`)
* formatting (`gofmt`)
* code coverage

More sophisticated tests (for bonus points):
* stress tests
* fuzz testing

You can use [appveyor](https://www.appveyor.com/) to run a windows build job for PRs. Microsoft has an example setup for the [hcsshim](https://github.com/Microsoft/hcsshim) repo: https://github.com/Microsoft/hcsshim/blob/master/appveyor.yml

You can use [circleci](https://circleci.com/) or [travis](https://travis-ci.org/) to setup a linux build job for PRs. For example, [cni](https://github.com/containernetworking/cni) uses travis:
https://github.com/containernetworking/cni/blob/master/.travis.yml

**Comment by andrewhsu** [comment]
cc @abhi @carlfischer1

**Comment by saiyan86** [comment]
CircleCI is added and we'll have Azure Pipeline soon. Closing this.
