### ISSUE TITLE
Support for Hubble and Cilium network policy

### ISSUE THREAD

**Issue by akselleirv** [Azure/azure-container-networking#1705]
**Component (Azure NPM or Azure CNI):** 
Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  
Do you have a roadmap for the Cilium integration? I’m missing features such as Hubble, Cilium network policy and the service mesh features found in full version of Cilium.

Where can I track the progress for these features?

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

**Comment by rbtr** [comment]
@tamilmani1989 is there any public roadmap for these features?

**Comment by akselleirv** [comment]
Any updates for this issue?

**Comment by RSE132** [comment]
Even I am looking for the same.. any roadmap would be appreciated

**Comment by tamilmani1989** [comment]
Don't have a definite date. Hubble support will be enabled as preview-feature within few months. will share an update once i get confirmation on this

**Comment by akselleirv** [comment]
@tamilmani1989 thank you for the update! No need to a date from my side. I was just curious to know what will be supported in the offering. 

What about other features such as service-mesh, cluster-mesh and L7 network policies? Will that too be supported in the future?

**Comment by tamilmani1989** [comment]
@akselleirv sorry for delay. yes we will support those features in future. Regarding hubble, it will be supported as part of our network observability tool with basic metrics https://github.com/Azure/Kappie @vakalapa

**Comment by jblsk** [comment]
any updates on the Hubble preview?

**Comment by jblsk** [comment]
> Don't have a definite date. Hubble support will be enabled as preview-feature within few months. will share an update once i get confirmation on this
Any updates on the Hubble preview?
