### ISSUE TITLE
Docker plugin and access to the internet

### ISSUE THREAD

**Issue by MariuszFerdyn** [Azure/azure-container-networking#1721]
I installed docker plugin in Linux and Windows, but containers doesn't have access to the internet. I installed them according to this: https://github.com/Azure/azure-container-networking/issues/1719 (Windows).

Linux:
`install-cni-plugin.sh v1.4.20`
`iptables -t nat -A POSTROUTING -m addrtype ! --dst-type local ! -d 10.224.0.0/16 -j MASQUERADE`
I created IPConfig:
`az network nic ip-config create --name container01 --nic-name cni-test-linux829 --private-ip-address 10.224.0.6 --resource-group CNI-Test02
`
When I execute:
```
./docker-run.sh vnetdockerdemo default alpine
sudo docker exec -it vnetdockerdemo /bin/sh

ifconfig
```
than I see proper IP

but the conatiner doesn't have access to the Internet.

**Comment by tamilmani1989** [comment]
please update your mode to `bridge` instead of `tunnel` in conflist

**Comment by tamilmani1989** [comment]
similar issue: https://github.com/Azure/azure-container-networking/issues/1725

**Comment by tdihp** [comment]
@Tamilman1989 just to mention [the documentation](https://learn.microsoft.com/en-us/azure/virtual-network/deploy-container-networking#download-and-install-the-plug-in) currently includes entry:

> The installed plug-in comes with a simple network configuration file that works after installation. **It doesn't need to be updated**.

It pretty much seems to be contradicting to the documentation.

**Comment by tamilmani1989** [comment]
@tdihp you are right that doc is pretty old and outdated. It was written for acs-engine clusters which was deprecated long back. Installing cni through daemonset(host process) is in progress .. Meanwhile can you use this script to install cni in your setup. https://github.com/Azure/azure-container-networking/blob/master/scripts/Install-CniPlugin.ps1  . Update azure cni version to 1.4.39 in script.

**Comment by tdihp** [comment]
@tamilman1989 thanks for the reply. I'm also doing a similar test and will update if I get stuck. I have fully scripted environment for the sake of repro.

**Comment by tdihp** [comment]
With my current setup (https://github.com/tdihp/lxd-azurecni), I'm not able to access an nginx:latest pod in the same VM which I installed CNI plugin. The installation script (provision.sh) basically adds a Ubuntu 20.04 VM, configure the nic with multiple private IPs, and the cloud-init.txt installs jq, docker and the CNI, then use rsync to copy the "bridge" config.

`bash docker-run.sh foobar default nginx:latest` works, and I can find the container address with `nsenter -n -t <> ip addr`, however curl from host fails with connection timeout. I'm able to see the syn packet tretransmitting inside the container network namespace.

**Comment by tdihp** [comment]
BTW I also tried Ubuntu 22.04, it fails due to not able to find `systemd-resolve`, apparently this is needed for the "bridge" implementation.

**Comment by tamilmani1989** [comment]
@tdihp for linux, use this script to install cni and conflist: https://github.com/Azure/azure-container-networking/blob/master/scripts/install-cni-plugin.sh

**Comment by tdihp** [comment]
@tamilmani1989 I double checked that the script you shared is the same thing I used in repro: https://github.com/tdihp/lxd-azurecni/blob/main/cloud-init.txt#L22

**Comment by tamilmani1989** [comment]
@tdihp check version of cni installed by running `./azure-vnet -v`.. also check mode field in conflist, it should be set to transparent.. if not, then you are not using latest conflist file.... if you have already used older of version of cni with bridge mode in that VM, reboot your VM after installing latest cni

**Comment by tdihp** [comment]
After reverting mode to "transparent" according to @tamilmani1989 's advice and starting `nginx` command explicitly (`docker-run.sh` itself only starts a sleep thread, not the entrypoint), I'm able to reach the internal service from the host, will check further on whether it works on remote

**Comment by tdihp** [comment]
Connecting from a different VM didn't work at first, but worked after I reconfigured iptables to unblock by `iptables -t filter -P FORWARD ACCEPT`, as Docker installation configures the filter chain which default to drop.
