### ISSUE TITLE
Add `prometheus.io/scrape: 'true'` annotation to the `azure-cns` Kubernetes workload

### ISSUE THREAD

**Issue by jcleavel** [Azure/azure-container-networking#1747]
**Component (Azure NPM or Azure CNI):**
`azure-cns`

**Describe in detail the feature/behavior/change you'd like to see:** 

The `azure-cns` DaemonSet definition doesn't include a `prometheus.io/scrape: 'true'` annotation in the Pod template metadata block.
Adding this annotation to the Pod template will make it much less of an ordeal to configure 3rd party tools to scrape the IP utilization metrics from the service's metrics server.

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  
N/A

**Comment by rbtr** [comment]
@jcleavel do you mean when CNS is deployed in AKS? if not, where is the ds spec you're referring to?

**Comment by jcleavel** [comment]
Yes @rbtr, this is in regards to the CNS workload that is automatically installed in an AKS cluster.

**Comment by rbtr** [comment]
@paulgmiller any reason for us not to add this?

**Comment by paulgmiller** [comment]
No reason not to add thought it won't get you scraped by our internal stuff. (there was a brief time whre **aks**.prometheus.io/scrape was respected but that seems dead.

**Comment by jcleavel** [comment]
The [latest AKS release notes](https://github.com/Azure/AKS/releases/tag/2022-12-04) states that your team has enabled the default annotation on the managed Cilium workload:

> In Azure CNI powered by Cilium clusters, AKS now sets prometheus.io/port and prometheus.io/scrape annotations on the cilium-operator deployment as well as the prometheus container ports on the cilium and cilium operator manifests.

Both of these tools seem to serve equivalent purposes. Why not keep this part consistent?

**Comment by rbtr** [comment]
We could have customers who are running that default kube-prometheus config and scraping anything that has the `prometheus.io/scrape=true` annotation. I can't add that annotation to one of my system components and start sending my metrics to their Prometheus instance without making it, in some way, opt-in. A worst-case scenario could be that the additional load knocks over their metrics/alerting infrastructure and makes them blind to a production outage.
The Cilium scenario is still in Preview, and we don't have the same potential impact when making the change there.
If I could go back and add the annotation to CNS from the beginning, I would. But it's a bigger ask to add it now.

**Comment by jcleavel** [comment]
Is there a way for users to set this annotation on the workloads in our individual clusters in a reliable/safe manner?

**Comment by rbtr** [comment]
No, any changes to the AKS-managed components will be reverted to our target state.
We do already have the `prometheus.io/port: "10092"` annotation on CNS for internal use; could you add a scrape-config targeting that annotation?

**Comment by jcleavel** [comment]
I can give it a try.
I'll go ahead and close this. I think that I can work with my monitoring tool's support to get this path to work.
Thanks!
