### ISSUE TITLE
can not complie with the latest code https://github.com/containernetworking/cni 

### ISSUE THREAD

**Issue by honcao** [Azure/azure-container-networking#178]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:
The latest code
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI
---

**Which Operating System (Linux/Windows)**:
Fedora
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux localhost.localdomain 4.16.16-300.fc28.x86_64 #1 SMP Sun Jun 17 03:02:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---

**What happened**:
1. go get -d github.com/Azure/azure-container-networking
2. go get -d github.com/containernetworking/cni
3. make all-binaries
I got the following errors:
chmod 0755 output/linux_amd64/cnm/azure-vnet-plugin
cd output/linux_amd64/cnm && tar -czvf azure-vnet-cnm-linux-amd64-v1.0.6-3-ge29adde.tgz azure-vnet-plugin
azure-vnet-plugin
chown 1000:1000 output/linux_amd64/cnm/azure-vnet-cnm-linux-amd64-v1.0.6-3-ge29adde.tgz
go build -v -o output/linux_amd64/cni/azure-vnet -ldflags "-X main.version=v1.0.6-3-ge29adde -s -w" cni/network/plugin/*.go
github.com/Azure/azure-container-networking/cni
# github.com/Azure/azure-container-networking/cni
cni/plugin.go:107:35: not enough arguments in call to invoke.DelegateAdd
        have (string, []byte)
        want (string, []byte, invoke.Exec)
cni/plugin.go:129:29: not enough arguments in call to invoke.DelegateDel
        have (string, []byte)
        want (string, []byte, invoke.Exec)
make: *** [Makefile:106: output/linux_amd64/cni/azure-vnet] Error 2
---

**What you expected to happen**:

Compile the code successfully
---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by madhanrm** [comment]
Yes, seeing the same for windows

**Comment by madhanrm** [comment]
```
github.com/Azure/azure-container-networking$ GOOS="windows"  make azure-cni-plugin
go build -v -o output/windows_amd64/cni/azure-vnet.exe -ldflags "-X main.version=v1.0.6-7-gdadfe84 -s -w" cni/network/plugin/*.go
github.com/Azure/azure-container-networking/log
github.com/Azure/azure-container-networking/network/policy
github.com/Azure/azure-container-networking/platform
github.com/containernetworking/cni/pkg/types
github.com/Microsoft/hcsshim/internal/guid
golang.org/x/sys/windows
github.com/Microsoft/hcsshim/internal/schema1
github.com/Microsoft/hcsshim/internal/hcserror
github.com/Microsoft/hcsshim/internal/mergemaps
github.com/Microsoft/hcsshim/internal/longpath
github.com/Azure/azure-container-networking/store
github.com/containernetworking/cni/pkg/types/020
github.com/Azure/azure-container-networking/common
github.com/containernetworking/cni/pkg/types/current
github.com/containernetworking/cni/pkg/version
github.com/Azure/azure-container-networking/telemetry
github.com/containernetworking/cni/pkg/invoke
github.com/containernetworking/cni/pkg/skel
github.com/Azure/azure-container-networking/cni
# github.com/Azure/azure-container-networking/cni
cni/plugin.go:107:35: not enough arguments in call to invoke.DelegateAdd
        have (string, []byte)
        want (string, []byte, invoke.Exec)
cni/plugin.go:129:29: not enough arguments in call to invoke.DelegateDel
        have (string, []byte)
        want (string, []byte, invoke.Exec)
github.com/Microsoft/go-winio
github.com/Microsoft/hcsshim/internal/interop
golang.org/x/crypto/ssh/terminal
github.com/sirupsen/logrus
github.com/Microsoft/hcsshim/internal/safefile
github.com/Microsoft/hcsshim/internal/hcs
github.com/Microsoft/hcsshim/internal/hns
github.com/Microsoft/hcsshim/internal/wclayer
github.com/Microsoft/hcsshim
github.com/Azure/azure-container-networking/network
Makefile:106: recipe for target 'output/windows_amd64/cni/azure-vnet.exe' failed
make: *** [output/windows_amd64/cni/azure-vnet.exe] Error 2
```

**Comment by madhanrm** [comment]
Fix can be picked up from https://github.com/Azure/azure-container-networking/pull/174/files to unblock
