### ISSUE TITLE
Make CNI Network Monitor part of CNI

### ISSUE THREAD

**Issue by sharmasushant** [Azure/azure-container-networking#179]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI
---

**Which Operating System (Linux/Windows)**:
Linux
---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes
---

**Comment by goatmale** [comment]
What does CNI network monitor even do? It seems unclear from the documentation, both in github and on Dockerhub.
