### ISSUE TITLE
Is Azure NPM for Windows Server 2022 node in Preview or GA?

### ISSUE THREAD

**Issue by liamfoneill** [Azure/azure-container-networking#1803]
On the https://github.com/Azure/azure-container-networking readme file is states that only Linux is supported 
![image](https://user-images.githubusercontent.com/1243172/218734482-c4e577c0-ab53-4a0c-8396-7ba7e47e495d.png)

but on the Azure docs it states that Azure NPM is supported for Windows Server 2022 nodes https://learn.microsoft.com/en-us/azure/aks/use-network-policies#differences-between-azure-network-policy-manager-and-calico-network-policy-and-their-capabilities 

![image](https://user-images.githubusercontent.com/1243172/218734625-8c8f0e74-3b31-4673-b21e-36cff25477cb.png)

However further down the page, the quickstart for Windows has (preview) in the title. Is the feature in preview or just the method of deploying it? 

![image](https://user-images.githubusercontent.com/1243172/218734098-65819f17-98e0-44ae-986f-7c9c24dba87c.png)

Please be clear if Azure NPM for Windows 2022 is Generally Available or not.

**Comment by huntergregory** [comment]
Hi @liamfoneill, Azure NPM is in Public Preview on Windows Server 2022. 

Thanks for letting us know about the discrepancy in our Readme. We will update this
