### ISSUE TITLE
ipam plugin aks assignes duplicate ips 

### ISSUE THREAD

**Issue by digeler** [Azure/azure-container-networking#181]
**Is this a request for help?**:YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issu
---

**Which release version?**:
AKS latest version with cni
---

**Which component (CNI/IPAM/CNM/CNS)**:

---IPAM

**Which Operating System (Linux/Windows)**:
linux
---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---Kubernetes 

**What happened**:

---we see ipam is sending duplicate ips 

**What you expected to happen**:

---unique ip 

**How to reproduce it** (as minimally and precisely as possible):

---we create new cluster and we see this behavior 

**Anything else we need to know**:

---
from the cluster 

[cin@l004 ~]$ kubectl get pods -o=wide --all-namespaces
NAMESPACE              NAME                                                              READY     STATUS                  RESTARTS   AGE       IP              NODE
kube-system            azureproxy-6496d6f4c6-qkk86                                       0/1       CrashLoopBackOff        749        2d        10.128.16.133   aks-agentpool-66686873-5
kube-system            heapster-5f7c7df649-84zhx                                         2/2       Running                 9          3d        10.128.16.50    aks-agentpool-66686873-4
kube-system            kube-dns-v20-7c556f89c5-d8xgt                                     3/3       Running                 3          5d        10.128.16.87    aks-agentpool-66686873-2
kube-system            kube-dns-v20-7c556f89c5-zdm54                                     3/3       Running                 3          5d        10.128.16.21    aks-agentpool-66686873-3
kube-system            kube-proxy-28576                                                  1/1       Running                 1          5d        10.128.16.66    aks-agentpool-66686873-2
kube-system            kube-proxy-c2tc9                                                  1/1       Running                 1          5d        10.128.16.97    aks-agentpool-66686873-1
kube-system            kube-proxy-hr7wh                                                  1/1       Running                 1          5d        10.128.16.159   aks-agentpool-66686873-0
kube-system            kube-proxy-j5w2s                                                  1/1       Running                 2          5d        10.128.16.252   aks-agentpool-66686873-8
kube-system            kube-proxy-n28vl                                                  1/1       Running                 2          5d        10.128.16.35    aks-agentpool-66686873-4
kube-system            kube-proxy-qj7x8                                                  1/1       Running                 1          5d        10.128.16.128   aks-agentpool-66686873-5
kube-system            kube-proxy-qxx66                                                  1/1       Running                 1          5d        10.128.16.4     aks-agentpool-66686873-3
kube-system            kube-proxy-tqhd2                                                  1/1       Running                 2          5d        10.128.16.190   aks-agentpool-66686873-7
kube-system            kube-state-metrics-599b4df445-4tk49                               2/2       Running                 3          5d        10.128.16.163   aks-agentpool-66686873-0
kube-system            kube-svc-redirect-8crml                                           1/1       Running                 653        5d        10.128.16.190   aks-agentpool-66686873-7
kube-system            kube-svc-redirect-hnvbd                                           0/1       CrashLoopBackOff        676        5d        10.128.16.159   aks-agentpool-66686873-0
kube-system            kube-svc-redirect-jdsd5                                           1/1       Running                 293        5d        10.128.16.128   aks-agentpool-66686873-5
kube-system            kube-svc-redirect-ldvbd                                           1/1       Running                 678        5d        10.128.16.97    aks-agentpool-66686873-1
kube-system            kube-svc-redirect-prgnk                                           0/1       CrashLoopBackOff        673        5d        10.128.16.35    aks-agentpool-66686873-4
kube-system            kube-svc-redirect-vm886                                           0/1       CrashLoopBackOff        676        5d        10.128.16.66    aks-agentpool-66686873-2
kube-system            kube-svc-redirect-z6cwh                                           0/1       CrashLoopBackOff        677        5d        10.128.16.252   aks-agentpool-66686873-8
kube-system            kube-svc-redirect-z9cxf                                           1/1       Running                 680        5d        10.128.16.4     aks-agentpool-66686873-3
kube-system            kubernetes-dashboard-d876d4cdf-z7rtl                              0/1       CrashLoopBackOff        636        2d        10.128.16.75    aks-agentpool-66686873-2
kube-system            omsagent-cxsfg                                                    1/1       Running                 0          3d        10.128.16.178   aks-agentpool-66686873-0
kube-system            omsagent-dc52f                                                    0/1       CrashLoopBackOff        893        3d        10.128.17.0     aks-agentpool-66686873-8
kube-system            omsagent-nb7pj                                                    1/1       Running                 0          3d        10.128.16.31    aks-agentpool-66686873-3
kube-system            omsagent-rs-6c5d58b44c-kd884                                      1/1       Running                 895        3d        10.128.16.45    aks-agentpool-66686873-4
kube-system            omsagent-t2qqj                                                    0/1       CrashLoopBackOff        895        3d        10.128.16.41    aks-agentpool-66686873-4
kube-system            omsagent-t99t2                                                    1/1       Running                 411        3d        10.128.16.153   aks-agentpool-66686873-5
kube-system            omsagent-twkfr                                                    1/1       Running                 179        3d        10.128.16.199   aks-agentpool-66686873-7
kube-system            omsagent-ws9wn                                                    1/1       Running                 0          3d        10.128.16.125   aks-agentpool-66686873-1
kube-system            omsagent-xzwlx                                                    1/1       Running                 0          3d        10.128.16.75    aks-agentpool-66686873-2
kube-system            tiller-deploy-6dcb966466-mnnrf                                    1/1       Running                 150        2d        10.128.16.131   aks-agentpool-66686873-5
kube-system            tunnelfront-74c8d6658c-pb9qf                                      1/1       Running                 266        2d        10.128.16.134   aks-agentpool-66686873-5
nexus-dev-monitoring   grafana-687699bc96-wn79p                                          0/1       Running                 107        2d        10.128.16.151   aks-agentpool-66686873-5
nexus-dev-monitoring   prometheus-alertmanager-85d944f874-hthh7                          1/2       Running                 4          5d        10.128.17.9     aks-agentpool-66686873-8
nexus-dev-monitoring   prometheus-blackbox-exporter-5856c85b8-cpv6b                      1/1       Running                 1          5d        10.128.16.103   aks-agentpool-66686873-1
nexus-dev-monitoring   prometheus-kube-state-metrics-566669df8c-zzfdw                    1/1       Running                 3          5d        10.128.16.19    aks-agentpool-66686873-3
nexus-dev-monitoring   prometheus-node-exporter-8lj6z                                    1/1       Running                 1          5d        10.128.16.66    aks-agentpool-66686873-2
nexus-dev-monitoring   prometheus-node-exporter-flhnh                                    1/1       Running                 1          5d        10.128.16.4     aks-agentpool-66686873-3
nexus-dev-monitoring   prometheus-node-exporter-gqlk7                                    1/1       Running                 1          5d        10.128.16.159   aks-agentpool-66686873-0
nexus-dev-monitoring   prometheus-node-exporter-l52zq                                    1/1       Running                 2          5d        10.128.16.252   aks-agentpool-66686873-8
nexus-dev-monitoring   prometheus-node-exporter-nrm6n                                    1/1       Running                 1          5d        10.128.16.128   aks-agentpool-66686873-5
nexus-dev-monitoring   prometheus-node-exporter-t959r                                    1/1       Running                 2          5d        10.128.16.190   aks-agentpool-66686873-7
nexus-dev-monitoring   prometheus-node-exporter-w8mcl                                    1/1       Running                 2          5d        10.128.16.35    aks-agentpool-66686873-4
nexus-dev-monitoring   prometheus-node-exporter-whdgt                                    1/1       Running                 1          5d        10.128.16.97    aks-agentpool-66686873-1
nexus-dev-monitoring   prometheus-pushgateway-585bdfdcd5-lm2fx                           1/1       Running                 1          5d        10.128.16.172   aks-agentpool-66686873-0
nexus-dev-monitoring   prometheus-server-79d4f794cc-qqn4j                                2/2       Running                 324        5d        10.128.16.119   aks-agentpool-66686873-1
nexus-dev              api-gateway-5796bf487-5r2zs                                       0/1       CrashLoopBackOff        1252       5d        10.128.16.45    aks-agentpool-66686873-4
nexus-dev              api-gateway-5796bf487-tk9j5                                       0/1       Running                 764        5d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              api-server-8579dbf5cb-9tqhr                                       0/2       Init:CrashLoopBackOff   1015       3d        10.128.16.103   aks-agentpool-66686873-1
nexus-dev              api-server-8579dbf5cb-cnbn6                                       0/2       Init:CrashLoopBackOff   883        3d        10.128.16.67    aks-agentpool-66686873-2
nexus-dev              assignments-service-7f8b8d4c4f-6zv7m                              2/2       Running                 0          2d        10.128.16.44    aks-agentpool-66686873-4
nexus-dev              auth-server-76754f9cf5-ftm95                                      0/1       Running                 134        2d        10.128.16.133   aks-agentpool-66686873-5
nexus-dev              basic-sftp-f7479796d-tq549                                        1/1       Running                 2          5d        10.128.16.253   aks-agentpool-66686873-8
nexus-dev              caseflow-unity-7745d7dbfc-q2hh2                                   2/2       Running                 0          4d        10.128.16.166   aks-agentpool-66686873-0
nexus-dev              caseflow-unity2-868f8d4665-s84ff                                  2/2       Running                 0          4d        10.128.16.9     aks-agentpool-66686873-3
nexus-dev              caseflow-unity3-6f94558bdf-6svsb                                  0/2       Init:CrashLoopBackOff   1218       4d        10.128.17.25    aks-agentpool-66686873-8
nexus-dev              caseflow-unity3-7b4f6c875f-xm6z4                                  2/2       Running                 2          5d        10.128.16.14    aks-agentpool-66686873-3
nexus-dev              cassandra-0                                                       2/2       Running                 2          5d        10.128.16.163   aks-agentpool-66686873-0
nexus-dev              cassandra-1                                                       2/2       Running                 2          5d        10.128.16.100   aks-agentpool-66686873-1
nexus-dev              cassandra-2                                                       1/2       Running                 857        5d        10.128.17.10    aks-agentpool-66686873-8
nexus-dev              citizen-registry-5dbf5945cd-rqsdk                                 1/1       Running                 23         4d        10.128.16.51    aks-agentpool-66686873-4
nexus-dev              digital-letter-microservice-7744554b78-gnk78                      1/2       CrashLoopBackOff        792        5d        10.128.17.0     aks-agentpool-66686873-8
nexus-dev              dst-microservice-65bfb998b7-lqbkk                                 0/1       CrashLoopBackOff        486        2d        10.128.16.58    aks-agentpool-66686873-4
nexus-dev              email-delivery-service-c5c567d6-dlnnr                             1/1       Running                 8          5d        10.128.16.61    aks-agentpool-66686873-4
nexus-dev              eop-microservice-67786f85cb-72sf2                                 2/2       Running                 0          2d        10.128.16.13    aks-agentpool-66686873-3
nexus-dev              eop-microservice-8659c5474-x6mkl                                  0/2       ContainerCreating       0          1m        <none>          aks-agentpool-66686873-5
nexus-dev              eop-ui-54595468f4-jm779                                           1/1       Running                 0          2d        10.128.16.43    aks-agentpool-66686873-4
nexus-dev              esb-central-5cf9c64d65-xmmzr                                      0/1       Terminating             0          3d        10.128.16.141   aks-agentpool-66686873-5
nexus-dev              external-dns-ccb88ddb4-r6qjn                                      1/1       Running                 2          5d        10.128.16.255   aks-agentpool-66686873-8
nexus-dev              file-conversion-clear-directories-1530514800-qqx84                1/1       Running                 0          33s       10.128.16.194   aks-agentpool-66686873-7
nexus-dev              file-conversion-microservice-6c8675865b-rjg4r                     1/1       Running                 0          2d        10.128.16.24    aks-agentpool-66686873-3
nexus-dev              finance-microservice-79685d496b-4krdc                             0/1       Init:0/1                371        3d        10.128.16.143   aks-agentpool-66686873-5
nexus-dev              finance-microservice-845b897594-5xcdt                             0/1       Running                 668        3d        10.128.16.49    aks-agentpool-66686873-4
nexus-dev              flower-chart-service-646cd899f6-rq82l                             1/1       Running                 0          2d        10.128.16.64    aks-agentpool-66686873-4
nexus-dev              fmk-microservice-54569445b-qb92d                                  0/1       CrashLoopBackOff        940        3d        10.128.16.49    aks-agentpool-66686873-4
nexus-dev              fmk-microservice-654c4868f9-4n2ss                                 0/1       Running                 625        5d        10.128.16.138   aks-agentpool-66686873-5
nexus-dev              fmk-microservice-654c4868f9-k59tp                                 0/1       CrashLoopBackOff        519        2d        10.128.16.255   aks-agentpool-66686873-8
nexus-dev              formbuilder-6d69fcccbd-8w7g6                                      1/1       Running                 110        5d        10.128.16.150   aks-agentpool-66686873-5
nexus-dev              fs3-classifications-77fb87b96b-tptl8                              1/1       Running                 0          2d        10.128.16.7     aks-agentpool-66686873-3
nexus-dev              grant-offer-portal-microservice-57d567b5d8-l4bw2                  0/1       RunContainerError       744        2d        10.128.16.129   aks-agentpool-66686873-5
nexus-dev              hcl-catalog-ccfffcbd8-8sk5v                                       1/1       Running                 595        5d        10.128.16.152   aks-agentpool-66686873-5
nexus-dev              hcl-catalog-ccfffcbd8-xh7r7                                       1/1       Running                 68         5d        10.128.16.39    aks-agentpool-66686873-4
nexus-dev              hcl-logistics-ui-77fbc67f85-jbwxj                                 1/1       Running                 0          2d        10.128.16.47    aks-agentpool-66686873-4
nexus-dev              hcl-logistics-ui-77fbc67f85-p7bgc                                 1/1       Running                 1          5d        10.128.16.147   aks-agentpool-66686873-5
nexus-dev              hcl-matching-ui-7f6b958bcb-r7skf                                  1/1       Running                 1          5d        10.128.16.150   aks-agentpool-66686873-5
nexus-dev              hcl-matching-ui-7f6b958bcb-v27wq                                  1/1       Running                 1          5d        10.128.16.133   aks-agentpool-66686873-5
nexus-dev              hcl-search-elasticsearch-client-895968fdb-cdxp5                   1/1       Running                 1          5d        10.128.16.112   aks-agentpool-66686873-1
nexus-dev              hcl-search-elasticsearch-data-0                                   1/1       Running                 22         5d        10.128.16.42    aks-agentpool-66686873-4
nexus-dev              hcl-search-elasticsearch-kibana-5d4b595d95-d7sff                  1/1       Running                 1          5d        10.128.16.101   aks-agentpool-66686873-1
nexus-dev              hcl-search-elasticsearch-master-0                                 1/1       Running                 11         5d        10.128.16.63    aks-agentpool-66686873-4
nexus-dev              html2pdf-microservice-57647f95-9dxms                              0/1       Running                 281        2d        10.128.16.134   aks-agentpool-66686873-5
nexus-dev              internal-ingress-controller-nginx-plus-ingress-controller-78rvr   1/2       Running                 6          5d        10.128.16.68    aks-agentpool-66686873-2
nexus-dev              kafka-kafka-0                                                     1/1       Running                 4          5d        10.128.16.104   aks-agentpool-66686873-1
nexus-dev              kafka-kafka-1                                                     0/1       CrashLoopBackOff        1218       5d        10.128.16.19    aks-agentpool-66686873-3
nexus-dev              kafka-zookeeper-0                                                 1/1       Running                 1          5d        10.128.16.32    aks-agentpool-66686873-3
nexus-dev              kafka-zookeeper-1                                                 1/1       Running                 2          5d        10.128.16.41    aks-agentpool-66686873-4
nexus-dev              kafka-zookeeper-2                                                 1/1       Running                 1          5d        10.128.16.72    aks-agentpool-66686873-2
nexus-dev              keycloak-9c8ff78f9-68fqn                                          2/2       Running                 1          2d        10.128.16.74    aks-agentpool-66686873-2
nexus-dev              kmd-care-citizen-updater-6ddbdbf976-hh4t5                         1/1       Running                 0          2d        10.128.16.51    aks-agentpool-66686873-4
nexus-dev              letter-layout-toolkit-5bd49585d-sr566                             0/1       Running                 415        2d        10.128.16.41    aks-agentpool-66686873-4
nexus-dev              logviewer-auth-proxy-547f8bd6f6-q6xh8                             0/1       Running                 548        5d        10.128.16.129   aks-agentpool-66686873-5
nexus-dev              logviewer-curator-1530234120-tm588                                0/1       CrashLoopBackOff        465        2d        10.128.16.67    aks-agentpool-66686873-2
nexus-dev              logviewer-curator-1530320520-llwv7                                1/1       Running                 339        2d        10.128.16.76    aks-agentpool-66686873-2
nexus-dev              logviewer-curator-1530406920-rvv8q                                0/1       CrashLoopBackOff        329        1d        10.128.16.215   aks-agentpool-66686873-7
nexus-dev              logviewer-curator-1530493320-ls5hr                                0/1       CrashLoopBackOff        69         6h        10.128.16.208   aks-agentpool-66686873-7
nexus-dev              logviewer-elasticsearch-client-797f78855-8ht2p                    0/1       Running                 1307       5d        10.128.16.55    aks-agentpool-66686873-4
nexus-dev              logviewer-elasticsearch-client-797f78855-smf4f                    0/1       CrashLoopBackOff        1377       5d        10.128.16.81    aks-agentpool-66686873-2
nexus-dev              logviewer-elasticsearch-data-0                                    1/1       Running                 1          5d        10.128.16.154   aks-agentpool-66686873-5
nexus-dev              logviewer-elasticsearch-data-1                                    1/1       Running                 2          5d        10.128.16.46    aks-agentpool-66686873-4
nexus-dev              logviewer-elasticsearch-master-0                                  1/1       Running                 1          5d        10.128.16.8     aks-agentpool-66686873-3
nexus-dev              logviewer-elasticsearch-master-1                                  1/1       Running                 1          5d        10.128.16.177   aks-agentpool-66686873-0
nexus-dev              logviewer-elasticsearch-master-2                                  1/1       Running                 1          5d        10.128.16.83    aks-agentpool-66686873-2
nexus-dev              logviewer-fluentd-6546579d87-r6tpb                                1/1       Running                 1          5d        10.128.16.176   aks-agentpool-66686873-0
nexus-dev              logviewer-kibana-586d8b69cf-dfvk9                                 1/1       Running                 1          5d        10.128.16.34    aks-agentpool-66686873-3
nexus-dev              medcom-microservice-687bd86b58-kbnsl                              0/1       CrashLoopBackOff        1196       4d        10.128.16.50    aks-agentpool-66686873-4
nexus-dev              mobile-disentangler-microservice-66bd6f6695-gjcj7                 1/1       Running                 2          5d        10.128.17.3     aks-agentpool-66686873-8
nexus-dev              mobile-disentangler-microservice-66bd6f6695-wft7w                 0/1       CrashLoopBackOff        727        5d        10.128.17.13    aks-agentpool-66686873-8
nexus-dev              mobile-workforce-management-7db94f5b97-vh55c                      0/1       Running                 1239       5d        10.128.17.10    aks-agentpool-66686873-8
nexus-dev              mobility-aids-cf6c9f6cd-czmrf                                     0/1       Running                 1380       5d        10.128.16.46    aks-agentpool-66686873-4
nexus-dev              mock-cpr-service-platform-7fbbbdcd5f-xhbvm                        1/1       Running                 2          5d        10.128.16.36    aks-agentpool-66686873-4
nexus-dev              mysql-proxy-apiserver-58fdccf6f-tk4hr                             1/1       Running                 958        5d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              mysql-proxy-apiserver-dbaas-5ff9b4f49d-vg5b5                      1/1       Running                 1          5d        10.128.16.10    aks-agentpool-66686873-3
nexus-dev              mysql-proxy-microservices-5c6f9997-lp68f                          0/1       CrashLoopBackOff        1591       5d        10.128.16.45    aks-agentpool-66686873-4
nexus-dev              mysql-proxy-microservices-dbaas-6c587cd888-whpfb                  1/1       Running                 1          5d        10.128.16.33    aks-agentpool-66686873-3
nexus-dev              nas-microservice-77845784cf-skrzj                                 0/1       Running                 223        2d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              nas-microservice-7ff6c79c95-n4rj7                                 0/1       CrashLoopBackOff        419        2d        10.128.16.58    aks-agentpool-66686873-4
nexus-dev              nas-publish-1530515100-zjqsb                                      0/1       ContainerCreating       0          23s       <none>          aks-agentpool-66686873-7
nexus-dev              nexus-offline-data-service-576dcc477c-fx5mp                       0/1       Running                 101        4d        10.128.16.142   aks-agentpool-66686873-5
nexus-dev              nexus-offline-data-service-576dcc477c-k6lzg                       0/1       CrashLoopBackOff        807        2d        10.128.16.253   aks-agentpool-66686873-8
nexus-dev              nexus-queue-rabbitmq-ha-0                                         1/1       Running                 6          5d        10.128.16.182   aks-agentpool-66686873-0
nexus-dev              nexus-queue-rabbitmq-ha-1                                         0/1       Running                 13         5d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              nexus-queue-rabbitmq-ha-2                                         1/1       Running                 5          5d        10.128.16.11    aks-agentpool-66686873-3
nexus-dev              nexus-ui-68d88fb65f-6lc9f                                         1/1       Running                 0          2h        10.128.16.191   aks-agentpool-66686873-7
nexus-dev              nexus-ui-68d88fb65f-l9zpv                                         0/1       ContainerCreating       0          2h        <none>          aks-agentpool-66686873-5
nexus-dev              nexus-ui-core-bdf6479cf-v6jcz                                     1/1       Running                 0          2d        10.128.16.52    aks-agentpool-66686873-4
nexus-dev              nginx-plus-ingress-controller-5c4f8f877f-qvhgn                    1/2       Running                 8          5d        10.128.16.69    aks-agentpool-66686873-2
nexus-dev              nginx-plus-ingress-controller-5c4f8f877f-scvsm                    1/2       CrashLoopBackOff        1551       5d        10.128.16.16    aks-agentpool-66686873-3
nexus-dev              outgoing-messages-service-7fc659fb84-wsgf9                        1/1       Running                 3          5d        10.128.17.24    aks-agentpool-66686873-8
nexus-dev              professional-shift-microservice-7ff9954fc8-msn7n                  1/1       Running                 184        2d        10.128.17.13    aks-agentpool-66686873-8
nexus-dev              push-to-exchange-microservice-7b74d4cc6c-rcffr                    1/1       Running                 14         5d        10.128.17.9     aks-agentpool-66686873-8
nexus-dev              qampo-microservice-b6b6f6944-8kwgg                                1/1       Running                 20         2d        10.128.16.220   aks-agentpool-66686873-7
nexus-dev              smdb-microservice-7bc66b8b9d-6njn7                                1/1       Running                 92         2d        10.128.16.209   aks-agentpool-66686873-7
nexus-dev              sms-service-6c6d7bdf87-d9tjf                                      0/1       CrashLoopBackOff        1465       5d        10.128.16.129   aks-agentpool-66686873-5
nexus-dev              sms-service-6c6d7bdf87-vbg2f                                      1/1       Running                 3          5d        10.128.16.253   aks-agentpool-66686873-8
nexus-dev              user-data-access-577675f6d6-c9jwd                                 0/1       Running                 698        5d        10.128.16.129   aks-agentpool-66686873-5

I’ve checked ipam logs for address 10.128.16.130 and this address is being allocated and de-allocated from Azure, despite the fact it’s already used by other pods:

2018/06/29 15:15:39 [ipam] Address request completed with address:10.128.16.130/20 err:<nil>.
2018/06/29 15:15:39 [cni-ipam] Allocated address 10.128.16.130/20.
2018/06/29 15:15:39 [cni-ipam] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.128.16.130 Mask:fffff000} Gateway:10.128.16.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.128.16.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/06/29 15:16:10 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.128.16.0/20 Address:10.128.16.130 QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2018/06/29 15:16:11 [ipam] Releasing address with address:10.128.16.130 options:map[].
2018/06/29 15:16:11 [ipam] Address release completed with address:10.128.16.130 err:<nil>.
2018/06/29 15:16:21 [ipam] Address request completed with address:10.128.16.130/20 err:<nil>.
2018/06/29 15:16:21 [cni-ipam] Allocated address 10.128.16.130/20.
2018/06/29 15:16:21 [cni-ipam] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.128.16.130 Mask:fffff000} Gateway:10.128.16.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.128.16.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/06/29 15:16:53 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.128.16.0/20 Address:10.128.16.130 QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2018/06/29 15:16:53 [ipam] Releasing address with address:10.128.16.130 options:map[].
2018/06/29 15:16:53 [ipam] Address release completed with address:10.128.16.130 err:<nil>.
2018/06/29 16:05:06 [ipam] Address request completed with address:10.128.16.130/20 err:<nil>.
2018/06/29 16:05:06 [cni-ipam] Allocated address 10.128.16.130/20.
2018/06/29 16:05:06 [cni-ipam] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.128.16.130 Mask:fffff000} Gateway:10.128.16.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.128.16.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/06/29 16:06:34 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.128.16.0/20 Address:10.128.16.130 QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2018/06/29 16:06:35 [ipam] Releasing address with address:10.128.16.130 options:map[].
2018/06/29 16:06:35 [ipam] Address release completed with address:10.128.16.130 err:<nil>.
2018/06/29 16:17:18 [ipam] Address request completed with address:10.128.16.130/20 err:<nil>.
2018/06/29 16:17:18 [cni-ipam] Allocated address 10.128.16.130/20.
2018/06/29 16:17:18 [cni-ipam] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.128.16.130 Mask:fffff000} Gateway:10.128.16.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.128.16.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/06/29 16:17:44 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.128.16.0/20 Address:10.128.16.130 QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2018/06/29 16:17:44 [ipam] Releasing address with address:10.128.16.130 options:map[].
2018/06/29 16:17:44 [ipam] Address release completed with address:10.128.16.130 err:<nil>.
2018/06/30 03:00:37 [ipam] Address request completed with address:10.128.16.130/20 err:<nil>.
2018/06/30 03:00:37 [cni-ipam] Allocated address 10.128.16.130/20.
2018/06/30 03:00:37 [cni-ipam] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.128.16.130 Mask:fffff000} Gateway:10.128.16.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.128.16.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/06/30 03:05:08 [cni-ipam] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.128.16.0/20 Address:10.128.16.130 QueryInterval:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} AdditionalArgs:[]}.
2018/06/30 03:05:09 [ipam] Releasing address with address:10.128.16.130 options:map[].
2018/06/30 03:05:09 [ipam] Address release completed with address:10.128.16.130 err:<nil>.

[cin@l004 .kube]$ kubectl get pods -o=wide --all-namespaces | grep aks-agentpool-66686873-5 | grep 130
nexus-dev              api-gateway-5796bf487-tk9j5                                       0/1       Running                 764        5d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              mysql-proxy-apiserver-58fdccf6f-tk4hr                             1/1       Running                 958        5d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              nas-microservice-77845784cf-skrzj                                 0/1       Running                 223        2d        10.128.16.130   aks-agentpool-66686873-5
nexus-dev              nexus-queue-rabbitmq-ha-1                                         0/1       Running                 13         5d        10.128.16.130   aks-agentpool-66686873-5

**Comment by CecileRobertMichon** [comment]
@sharmasushant @tamilmani1989 please take a look, we have aks customers running into this issue

**Comment by tamilmani1989** [comment]
@digeler - can you please send us entire /var/log/azure-vnet.log? because I didn't see any logs between  2018/06/30 03:00:37 and 2018/06/30 03:05:08. I wanted to make sure if KUBERNETES is calling del for that ip.

**Comment by sharmasushant** [comment]
This is fixed in v1.0.7
