### ISSUE TITLE
A hand to the hac

### ISSUE THREAD

**Issue by Sul55** [Azure/azure-container-networking#1876]
**What happened:**  

**What you expected to happen:**  

**How to reproduce it:**  

**Kubernetes Version:**  

**Kernel (e.g. `uname -a`):**  

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]
Deleat

**Comment by rbtr** [comment]
@Sul55 are you having an issue?
Closing since there is no information provided, if you reopen please provide some detail.
