### ISSUE TITLE
Intermittent "Store is locked vnet" on azure-cni 1.0.7

### ISSUE THREAD

**Issue by PatrickLang** [Azure/azure-container-networking#194]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): issue 

---

**Which release version?**: 1.0.7

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**: Windows (maybe Linux too)

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**   10.0.17134.112

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**: Kubernetes v1.11

---

**What happened**:

I'm getting this intermittently in the logs with no apparent failures. Pods still start eventually and I'm not out of IPs

```
2018/07/11 22:47:05 [cni] Timed out on locking store, err:Store is locked.
2018/07/11 22:47:05 Failed to initialize key-value store of network plugin, err:Store is locked.
```

---

**What you expected to happen**:

No errors from CNI

---

**How to reproduce it** (as minimally and precisely as possible):
Deploy k8s cluster using acs-engine v0.19.2
Deploy 16 pods to a Windows node (https://raw.githubusercontent.com/PatrickLang/Windows-K8s-Samples/master/iis/iis-1803.yaml)

---

cc @CecileRobertMichon

**Comment by jhowardmsft** [comment]
Suspect root cause is as described in https://github.com/Azure/azure-container-networking/issues/232#issuecomment-420824623

**Comment by PatrickLang** [comment]
Closing, this hasn't been seen in a while.
