### ISSUE TITLE
overlay IPAM not reporting version

### ISSUE THREAD

**Issue by matmerr** [Azure/azure-container-networking#2081]
**What happened:** 
when on newly deployed node, checking ipam version shows unknown

![image](https://github.com/Azure/azure-container-networking/assets/6521405/af13e998-f826-4d14-8907-e476a25badb9)

using
mcr.microsoft.com/containernetworking/cni-dropgz:v0.0.9
mcr.microsoft.com/containernetworking/azure-cns:v1.5.5

maybe @rbtr?

**Comment by rbtr** [comment]
@nddq can you take a look at this?

**Comment by nddq** [comment]
![image](https://github.com/Azure/azure-container-networking/assets/28567936/7259790a-1cdb-4da5-a9c2-b84ecf80cc63) Looks like this is the source of the problem. How is the BuildVersion being overwritten in the linker script?

**Comment by rbtr** [comment]
Yeah, we do something like `-ldflags "-X main.version=$(CNI_VERSION)"` 
For azure-ipam I guess we need to change the `main.version` to whatever this <CNI pkg>.BuildVersion is

**Comment by nddq** [comment]
currently it is `buildinfo.Version` in azure-ipam. Changing the package name to `buildversion` and the var to `BuildVersion` should do it?
