### ISSUE TITLE
failed to setup network

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-container-networking#209]
**Is this a request for help?**:

---

**ISSUE**
---

**Which release version?**:
1.0.8

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Linux

---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux kubetest-worker0 4.15.0-1013-azure #13-Ubuntu SMP Thu May 24 14:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes
---

**What happened**:
can't spin up a container. receive the following error message in jurnalctl

>Jul 24 18:20:36 kubetest-worker0 kubelet[1147]: E0724 18:20:36.959668    1147 pod_workers.go:186] Error syncing pod ce7c5890-8f6d-11e8-b231-000d3ab3eb34 ("kube-dns-598d7bf7d4-hn2g4_kube-system(ce7c5890-8f6d-11e8-b231-000d3ab3eb34)"), skipping: failed to "CreatePodSandbox" for "kube-dns-598d7bf7d4-hn2g4_kube-system(ce7c5890-8f6d-11e8-b231-000d3ab3eb34)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-598d7bf7d4-hn2g4_kube-system(ce7c5890-8f6d-11e8-b231-000d3ab3eb34)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"51f9b733e40b8d12e5a0c5b4825303adbe54376f4820f8bcff4dafa938afe31c\": **incompatible CNI versions; config is \"0.3.1\", plugin supports [\"0.1.0\" \"0.2.0\"]"**

>andrei@kubetest-worker0:~$ cat /etc/cni/net.d/10-azure.conflist
{
   "cniVersion":"0.3.0",
   "name":"azure",
   "plugins":[
      {
         "type":"azure-vnet",
         "mode":"bridge",
         "bridge":"azure0",
         "ipam":{
            "type":"azure-vnet-ipam"
         }
      },
      {
         "type":"portmap",
         "capabilities":{
            "portMappings":true
         },
         "snat":true
      }
   ]
}

container stuck on creation
---

**Anything else we need to know**:

---

**Comment by sharmasushant** [comment]
@eosfor Which version of KUBERNETES are you using? Did you setup the cluster using acs-engine, or is it a self managed cluster? Can you please share logs from /var/log/azure-vnet*

**Comment by eosfor** [comment]
i followed [this guide](https://github.com/kelseyhightower/kubernetes-the-hard-way) trying to adopt it to Azure. I stuck [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#configure-cni-networking) when trying to setup CNI plugin on the first worker. I installed in successfully, but immediately after installing CNI using sh script i tried to spin up the container and started receiving this error message

**Comment by eosfor** [comment]
i've updated the plugin to v1.0.10 but issue is still the same.
