### ISSUE TITLE
Occasionally pods cannot create outbound connections

### ISSUE THREAD

**Issue by AaronFriel** [Azure/azure-container-networking#211]
**Is this a request for help?**: Yes, please. I'm trying to increase visibility on a networking issue with AKS: https://github.com/Azure/AKS/issues/568 that I suspect is related to the CNI plugin.

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

**Which release version?**: Whatever is used with v0.19.2-aks

**Which component (CNI/IPAM/CNM/CNS)**: Probably CNI

**Which Operating System (Linux/Windows)**: Linux

**For Linux: Include Distro and kernel version using "uname -a"** n/a (whatever AKS deploys)

**Which Orchestrator and version (e.g. Kubernetes, Docker)** Kubernetes, 1.10.5

# From this point on, most of this is copied from https://github.com/Azure/AKS/issues/568 

**What happened**:

Pods running on AKS occasionally are unable to connect to external hosts, as in these logs from a GitLab runner:

```
...
Checking out 4cd6c87a as master...
Skipping Git submodules setup
$ # Azure Container Registry Build variable overrides # collapsed multi-line command
$ # Auto DevOps variables and functions # collapsed multi-line command
$ check_kube_domain
$ install_dependencies
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/2) Installing gzip (1.8-r0)
(2/2) Installing tar (1.29-r1)
Executing busybox-1.27.2-r7.trigger
OK: 55 MiB in 56 packages
wget: bad address 'raw.githubusercontent.com'
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

Restarting the pod in question (or retrying the job) eventually resolves the issue.

**What you expected to happen**:

All pods should be able to connect to external hosts by default.

**How to reproduce it** (as minimally and precisely as possible):

I have no idea. It appears the problems began when I scaled the cluster up to two nodes from one. The cluster was created using the ARM template at the following gist: 

https://gist.github.com/AaronFriel/c6f4c56602ab167ff996969374aaada5

**Anything else we need to know**: idk

**Comment by sharmasushant** [comment]
@AaronFriel  Are you sure its related to Azure CNI. From your logs, it appears that the runner was able to reach dl-cdn.alpinelinux.org to download some packages? Does the get resolved on its own (e.g., you mention that retries work sometimes)? 
We can take a look at logs of Azure CNI if you can share files from /var/log/azure-vnet*

Can you also share if you used basic or advanced networking while creating aks cluster?

**Comment by sharmasushant** [comment]
@AaronFriel Please close if issue is resolved or if help from us is no longer needed.

**Comment by AaronFriel** [comment]
I'm closing this issue for the time being, here is the issue I created on the gitlab-runner project: https://gitlab.com/gitlab-org/gitlab-runner/issues/3485
