### ISSUE TITLE
Change MTU?

### ISSUE THREAD

**Issue by holmesb** [Azure/azure-container-networking#215]
I can't see this documented anywhere, so thus the question:  Is it possible to change the MTU (Maximum transmission unit) setting using Azure CNI?  I see other network plugins, eg [Calico](https://docs.projectcalico.org/v2.2/usage/configuration/mtu) have this functionality.  Sometimes it's necessary to adjust for compatibility with routers\firewalls.  If not, then this issue is a feature request.

**Comment by holmesb** [comment]
Further to this, this is what happens when I try to change a container's MTU from default (1500) to 1400:
```
sudo ifconfig eth0 mtu 1400 up
SIOCSIFMTU: Operation not permitted
SIOCSIFFLAGS: Operation not permitted 
```

**Comment by sharmasushant** [comment]
@holmesb  we do not have a plan to support this right now. if there is a valid scenario for this in Azure, we are open to revisit the requirement with the reason.
