### ISSUE TITLE
Azure CNI breaks with Linux kernel 6.2

### ISSUE THREAD

**Issue by tamilmani1989** [Azure/azure-container-networking#2156]
**What happened:** 
Azure CNI fails to run successfully in newly released 6.2 kernel. Investigating further reveals that Azure CNI returns `operation not supported` error on netlink delete route request calls. The flag (`NLM_F_EXCL`) that used for netlink delete route got repurposed and kernel netlink api started to throw this error if that flag is passed. This resulted in Azure CNI to throw error on CNI Add call which led to pod creation failures.

**What you expected to happen:**  

**How to reproduce it:**  
Create a kubernetes cluster in Azure and upgrade your nodes to 6.2 kernel and then try to create pods and it should fail with Azure CNI error.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  
Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**
6.2

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by paulgmiller** [comment]
Techincally its the 5.19 kernel but 6.2 is scheduled to be pushed to ubuntu security pocket end of month thats the more important news. 

Beware if you're vms have ubuntu unattended upgrades on.
