### ISSUE TITLE
question iptables vs firewalld / non(AKS) Kubernetes

### ISSUE THREAD

**Issue by lightmans2** [Azure/azure-container-networking#2198]
Hello together

In your Documentation is described that we have to do some iptables settings if we use a non AKS Kubernetes Cluster with AzureCNI
see here -> [https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#using-cni-in-non-aks-environment-linux](https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#using-cni-in-non-aks-environment-linux)

in our Azure VMs we installed a vanilla kubernetes and the azure cni. 
Kubernetes and crio and Pods are working BUT the Pods does not have internet outbound connectivity.

we use rhel8 as OS and Firewalld as Firewall Service

sysctl net.ipv4.ip_forward shows 1 and its ok and set
sudo iptables -t filter -L FORWARD shows FORWARD Policy ACCEPT and its ok and set

if we use this command "iptables -t nat -A POSTROUTING -m addrtype ! --dst-type local ! -d 10.88.0.0/16 -j MASQUERADE"
the internet outbound for the pods still not work!

if i use iptables -L we can not see the POSTROUTING Chain or MASQUERADE Chain.

Is it possible that we need to convert the iptables command to firewalld? 
can somebody help to translate this command  "iptables -t nat -A POSTROUTING -m addrtype ! --dst-type local ! -d 10.88.0.0/16 -j MASQUERADE" from iptables into firewalld?

thx in advance

**Comment by rbtr** [comment]
does it work if you disable firewalld?

unfortunately I don't think we can provide any help here as this is not one of our supported scenarios.
