### ISSUE TITLE
Azure CNI & Accelerated Networking/Azure Route tables

### ISSUE THREAD

**Issue by sylr** [Azure/azure-container-networking#222]
I'm wondering if Azure CNI is compatible with `Accelerated Networking`.

I've deployed a cluster several time with both accelerated networking enabled and disabled on the agent `VMSS` and each time `Accelerated Networking` was enabled I ended up having problem with the network.

The observed problem was the impossibility to contact a pod hosted on one node from a second pod hosted on a second node.

Today I've been able to reproduced the problem with `Accelerated Networking` **disabled**.

After deploying a brand new cluster we forgot to add the agent subnet to the cluster `Azure Route table` and the cluster started to behave like if `Accelerated Networking` was enabled.

As soon as we added the agent subnet to the cluster route table everything started working normally.

So I'm wondering if enabling Accelerated Networking leads to bypass Azure Route tables.

Regards

**Comment by sharmasushant** [comment]
@sylr Are you sure you are using Azure CNI? It does not require a route table to work. You can confirm if azure cni was used to setup PODs by looking at the log files on the agent nodes @ /var/log/azure-vnet*

**Comment by sylr** [comment]
Hi, @sharmasushant 

Very interesting question, I'm not at work anymore so I can't answer you clearly.

What I know is that I've some Azure CNI components installed on my nodes (it's part of the acs-engine deployment) but I can't be certain it is used.

What I know it that I use the `networkPolicy None` in my acs-engine deployment so maybe @jackfrancis could tell us if I use it in such cluster.

**Comment by sharmasushant** [comment]
If you used latest or recent acs-engine, then you should be using Azure cni, and you should not require route table setup for communication to work. What version of acs-engine you used?

**Comment by sharmasushant** [comment]
@sylr Any update? Please share acs-engine version? And the Azure CNI logs from /var/log/azure-vnet* so that we can validate Azure CNI version as well.

**Comment by sylr** [comment]
Like I said I use `networkPolicy None` and after some research it means it uses Kubenet so I'm not using CNI even if it has been installed on the nodes:

```
root@k8s4-euw-dev-agent-vmss-000000:~# ll /opt/cni/bin
total 49016
drwxr-xr-x 2 root root     4096 Apr 12 09:22 ./
drwxr-xr-x 3 root root     4096 Jul 31 09:38 ../
-rwxr-xr-x 1 root root  4028260 Apr 12 09:21 bridge*
-rwxr-xr-x 1 root root 10232415 Apr 12 09:22 dhcp*
-rwxr-xr-x 1 root root  2856252 Apr 12 09:21 flannel*
-rwxr-xr-x 1 root root  3127363 Apr 12 09:21 host-device*
-rwxr-xr-x 1 root root  3036768 Apr 12 09:22 host-local*
-rwxr-xr-x 1 root root  3572685 Apr 12 09:21 ipvlan*
-rwxr-xr-x 1 root root  3084347 Apr 12 09:21 loopback*
-rwxr-xr-x 1 root root  3613497 Apr 12 09:21 macvlan*
-rwxr-xr-x 1 root root  3550877 Apr 12 09:21 portmap*
-rwxr-xr-x 1 root root  3993428 Apr 12 09:21 ptp*
-rwxr-xr-x 1 root root  2641877 Apr 12 09:22 sample*
-rwxr-xr-x 1 root root  2850029 Apr 12 09:21 tuning*
-rwxr-xr-x 1 root root  3568537 Apr 12 09:21 vlan*
```
So I guess my problem is not related to Azure CNI after all.

Sorry to have bothered you.
