### ISSUE TITLE
Azure NPM error on AKS 1.10.5 - ErrorMessage:exit status 4 EventMessage:Delete network policy

### ISSUE THREAD

**Issue by Daryltp** [Azure/azure-container-networking#237]
ISSUE
**Which release version?**: 1.0.9
**Which component (CNI/IPAM/CNM/CNS)**:CNI

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes v1.10.5 on AKS

---

**What happened**: I get the following error in the azure npm pod when I install the Azure NPM Daemonset and NetworkPolicies do not behave as expected. IE a deny all rule give a timed out error rather than connection refused.

azure-npm-sz57l azure-npm 2018/08/17 14:50:28 Going to send Telemetry report to hostnetagent http://169.254.169.254/machine/plugins?comp=netagent&type=npmreport
azure-npm-sz57l azure-npm 2018/08/17 14:50:28 Report: &{StartFlag:false ClusterID:11854310 NodeName:aks-agentpool-11854310-1 InstanceName: NpmVersion:v1.0.9 KubernetesVersion:v1.10.5 ErrorMessage:exit status 4 EventMessage:Delete network policy UpTime: ClusterState:{PodCount:-44 NsCount:9 NwPolicyCount:13}}

---

**What you expected to happen**: Not to receive and error and for network policies to work as expected.

---

**How to reproduce it** (as minimally and precisely as possible): install azure npm using the following command on AKS 1.10.5 and then view the logs of the azure-npm pod.

kubectl apply -f https://raw.githubusercontent.com/Azure/acs-engine/master/parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml

**Comment by saiyan86** [comment]
@Daryltp Thanks for the feedback. Will take a look!

**Comment by saiyan86** [comment]
@Daryltp This is by design. The attacker will know the port is listening if we reject the connection instead of silently dropping it.
