### ISSUE TITLE
Missing upgrade instructions

### ISSUE THREAD

**Issue by carlpett** [Azure/azure-container-networking#239]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature request

---

**Which release version?**: N/A

---

It would be helpful if there were upgrade instructions for how to upgrade from one version of the plugin to another, including impact on the system during upgrade and any precautions to take (like if the node should be cordoned). Also if there are any post-upgrade steps, such as restarting kubelet.

**Comment by sharmasushant** [comment]
@carlpett 
Have you tried the following script: https://github.com/Azure/azure-container-networking/blob/master/scripts/install-cni-plugin.sh 

You need to cordon the node before upgrading using the script. The script requires only one parameter

./install-cni-plugin.sh v1.0.11

There are n opost upgrade steps (Except uncordon the node).

**Comment by sharmasushant** [comment]
Instruction were added here: [Upgrade Azure cni Instructions](https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#upgrading-cni-on-existing-kubernetes-cluster-deployed-using-acs-engine)

**Comment by AceHack** [comment]
These instructions require full cluster down time, please create docs that explain how to upgrade with 0 down time at a cluster level.
