### ISSUE TITLE
Make All-Binaries on WSL Failing to build NPM

### ISSUE THREAD

**Issue by plooploops** [Azure/azure-container-networking#241]
**Is this a request for help?**:
Yes, it's a request for help.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue.
---

**Which release version?**:
Latest
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNM
---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux MININT-7P8IGVC 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

WSLAMD64
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker
---

**What happened**:
![image](https://user-images.githubusercontent.com/2498998/44547318-8c794900-a6cf-11e8-9fac-43b2952acb26.png)

I'm unable to do a full make all-binaries.  See the screenshot.  Not sure if it's an issue with vendoring, but it appears that the are getting downloaded, but perhaps not picked up as part of the make file.

We are using go 1.10.3 Linux amd 64
We use git reset --hard as well and are on the latest version.
---

**What you expected to happen**:
Make all-binaries would complete in WSL environment.
---

**How to reproduce it** (as minimally and precisely as possible):
We are using go 1.10.3 Linux amd 64
We use git reset --hard as well and are on the latest version.
![image](https://user-images.githubusercontent.com/2498998/44547252-59cf5080-a6cf-11e8-95bc-b806831e96f9.png)

---

**Anything else we need to know**:

---

**Comment by plooploops** [comment]
Looks like resetting the environment to look like what's in the Dockerfile.build and in the Dockerfile.cnm will help resolve the WSL environment.

Here's what I did locally:
```
Cd ~
curl -O https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz

tar -xvzf go1.10.3.linux-amd64.tar.gz

sudo mv go /usr/local

export PATH=$PATH:/usr/local/go/bin

export GOPATH='/mnt/c/Users/myid/source/repos/go'
export GOROOT='/usr/local/go'

sudo apt-get update && sudo apt-get install -y zip && sudo apt-get install -y sudo libltdl-dev
sudo apt-get update && sudo apt-get install -y ebtables
```

**Comment by sharmasushant** [comment]
Thanks for sharing resolution steps.
