### ISSUE TITLE
Azure CNI dynamic ip allocation batch size does not starts with 16

### ISSUE THREAD

**Issue by n-y-kim** [Azure/azure-container-networking#2462]
**What happened:** 
Followed [this](https://learn.microsoft.com/en-us/azure/aks/configure-azure-cni-dynamic-ip-allocation) documentation, configured monitoring to fetch info about subnet ip usage.
Got 17 from the start. When the pods increased, the increase of ip allocation did happen in 16 batch size. But since it started with 17, it became 17 + 16 = 33 ips.
<img width="679" alt="Screenshot 2023-12-29 at 1 45 04 PM" src="https://github.com/Azure/azure-container-networking/assets/76769919/60c785e4-4a02-41a8-a636-3cb3ee3ad883">

**What you expected to happen:**  
16 ip allocations from the start as the documentation.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
Cluster info:
k8s: 1.27.7

**Operating System (Linux/Windows):**  
Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**
`Linux aks-nodepool1-38556063-vmss000000 5.15.0-1052-azure #60-Ubuntu SMP Mon Nov 6 10:08:16 UTC 2023 x86_64 GNU/Linux`

**Anything else we need to know?:**
Would like to know if starting off with 17 is normal or bug that is in progress of fixing.

**Comment by rbtr** [comment]
@n-y-kim Sorry for the confusion here - this is expected. The scaling is in batches of 16 (we call these "Secondary IPs"). However, each Node reserves one additional IP from the Subnet for routing purposes (we call this the "Primary IP"), and this is the extra IP you are seeing in the initial metric.

**Comment by rbtr** [comment]
@n-y-kim Sorry for the confusion here - this is expected. The scaling is in batches of 16 (we call these "Secondary IPs"). However, each Node reserves one additional IP from the Subnet for routing purposes (we call this the "Primary IP"), and this is the extra IP you are seeing in the initial metric.
