### ISSUE TITLE
VNET in App Services Container

### ISSUE THREAD

**Issue by JarekToro** [Azure/azure-container-networking#250]
**Is this a request for help?**:

This is a Clarification uses of this software

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue kind of I need to understand if I can use this in an  app services container.

**Which release version?**:

CNI 0.6.0

**Which component (CNI/IPAM/CNM/CNS)**:

CNI/IPAM

**Which Operating System (Linux/Windows)**:

Linux

**For Linux: Include Distro and kernel version using "uname -a"**

Linux c42a986b2bb9 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

None. Is this only usable in an orchestrator? We are trying to use this in a App Services Container

**Comment by sharmasushant** [comment]
@JarekToro You cannot at the moment. I believe we do have plans that will allow you to create azure webapps for containers and connect to specific Vnet. But I am not sure about the timeline.

**Comment by sharmasushant** [comment]
I believe this is released for windows here; [Web Apps for Windows](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet)

For linux, I know there are plans, but i am not sure about the timeline.
