### ISSUE TITLE
Azure CNI fails to startup/teardown pods with a parse failure error

### ISSUE THREAD

**Issue by MarcPow** [Azure/azure-container-networking#260]
**Is this a request for help?**: Yes.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**: (Version of CNI plugin included with ACS-Engine 0.22.4)

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**: Windows

---

**For Linux: Include Distro and kernel version using "uname -a"**

N/A
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

(Windows 1803)
---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.2", GitCommit:"5a80e28431c7469d677c5b17277266d1da4e5c8d", GitTreeState:"clean", BuildDate:"2018-09-21T21:52:36Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
---

**What happened**:

Events:
  Type     Reason                  Age                 From                   Message
  ----     ------                  ----                ----                   -------
  Normal   Scheduled               47m                 default-scheduler      Successfully assigned default/powerflowclient-94b86489f-pvcrh to 71973k8s9001
  Warning  FailedCreatePodSandBox  47m                 kubelet, 71973k8s9001  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "b451fef5e7fef10184181f46494ccf0656db6e4bf9393e7657b70f5eb0c30136" network for pod "powerflowclient-94b86489f-pvcrh": NetworkPlugin cni failed to set up pod "powerflowclient-94b86489f-pvcrh_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "b451fef5e7fef10184181f46494ccf0656db6e4bf9393e7657b70f5eb0c30136" network for pod "powerflowclient-94b86489f-pvcrh": NetworkPlugin cni failed to teardown pod "powerflowclient-94b86489f-pvcrh_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]
  Normal   SandboxChanged          2m (x178 over 47m)  kubelet, 71973k8s9001  Pod sandbox changed, it will be killed and re-created.

---

**What you expected to happen**:

Reliable container startup/teardown
---

**How to reproduce it** (as minimally and precisely as possible):

Deploy a 1.11.3 or 1.12.0-rc2 Kubernetes cluster with ACS Engine 0.22.4
---

**Anything else we need to know**:

---

**Comment by MarcPow** [comment]
This may be related to #195

**Comment by ashvindeodhar** [comment]
@MarcPow Does this happen specifically after reboot or do you see this as a general issue?
We have resolved the issue seen after reboot in CNI latest release https://github.com/Azure/azure-container-networking/releases/tag/v1.0.16

**Comment by MarcPow** [comment]
> @MarcPow Does this happen specifically after reboot or do you see this as a general issue?
> We have resolved the issue seen after reboot in CNI latest release https://github.com/Azure/azure-container-networking/releases/tag/v1.0.16

Thanks, I'll re-test.
