### ISSUE TITLE
Support hostPorts in Azure CNI

### ISSUE THREAD

**Issue by MarcPow** [Azure/azure-container-networking#261]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Feature Request 
---

**Which release version?**: 

1.0.13
---

**Which component (CNI/IPAM/CNM/CNS)**:

CNI
---

**Which Operating System (Linux/Windows)**:

Windows (1803)
---

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

I was using a test bed in Azure to evaluate a software Ingress solution - but I discovered that hostPort is not working:

       ports:
        - name: http
          containerPort: 80
          hostPort: 5001
        - name: admin
          containerPort: 8080

I'd like Azure CNI to support this scenario.

---
**Which Orchestrator and version (e.g. Kubernetes, Docker)**:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
---

**What happened**:

The host port (5001) for example, was not exposed on the host.

  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       988
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING       2808
  TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING       544
  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:5986           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:10250          0.0.0.0:0              LISTENING       5036
  TCP    0.0.0.0:10255          0.0.0.0:0              LISTENING       5036
  TCP    0.0.0.0:10256          0.0.0.0:0              LISTENING       5116
  TCP    0.0.0.0:47001          0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING       552
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING       1644
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING       1564
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING       2016
  TCP    0.0.0.0:49670          0.0.0.0:0              LISTENING       2208
  TCP    0.0.0.0:49672          0.0.0.0:0              LISTENING       736
  TCP    0.0.0.0:49674          0.0.0.0:0              LISTENING       668
  TCP    10.240.0.35:139        0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:3735         0.0.0.0:0              LISTENING       5036
  TCP    127.0.0.1:10248        0.0.0.0:0              LISTENING       5036
  TCP    127.0.0.1:10249        0.0.0.0:0              LISTENING       5116
  TCP    127.0.0.1:49715        0.0.0.0:0              LISTENING       5036
  TCP    172.22.176.1:53        0.0.0.0:0              LISTENING       2328
  TCP    172.22.176.1:139       0.0.0.0:0              LISTENING       4
  TCP    [::]:135               [::]:0                 LISTENING       988
  TCP    [::]:445               [::]:0                 LISTENING       4
  TCP    [::]:2179              [::]:0                 LISTENING       2808
  TCP    [::]:3389              [::]:0                 LISTENING       544
  TCP    [::]:5985              [::]:0                 LISTENING       4
  TCP    [::]:5986              [::]:0                 LISTENING       4
  TCP    [::]:10250             [::]:0                 LISTENING       5036
  TCP    [::]:10255             [::]:0                 LISTENING       5036
  TCP    [::]:10256             [::]:0                 LISTENING       5116
  TCP    [::]:47001             [::]:0                 LISTENING       4
  TCP    [::]:49664             [::]:0                 LISTENING       552
  TCP    [::]:49665             [::]:0                 LISTENING       1644
  TCP    [::]:49666             [::]:0                 LISTENING       1564
  TCP    [::]:49667             [::]:0                 LISTENING       2016
  TCP    [::]:49670             [::]:0                 LISTENING       2208
  TCP    [::]:49672             [::]:0                 LISTENING       736
  TCP    [::]:49674             [::]:0                 LISTENING       668

---

**What you expected to happen**:

A connection listening on 5001

---

**How to reproduce it** (as minimally and precisely as possible):

AFAIK, any use of hostPort under Azure CNI

**Comment by MarcPow** [comment]
This may have been implicitly fixed by #256

**Comment by MarcPow** [comment]
Linking to https://github.com/kubernetes/kubernetes/issues/23920 (in case anyone else comes across this problem)

**Comment by saiyan86** [comment]
@MarcPow Thanks for reporting the issue! Could you please fill out all required fields in the template? Thanks!

**Comment by saiyan86** [comment]
@MarcPow If the platform is Windows, then I think it is fixed by #256. Closing this.
