### ISSUE TITLE
Remove CNM Code

### ISSUE THREAD

**Issue by QxBytes** [Azure/azure-container-networking#2648]
**What happened:** 
CNM Code is deprecated and will be removed soon once migrations away from it complete.

**What you expected to happen:**  

**How to reproduce it:**  

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**

**Comment by rbtr** [comment]
@QxBytes please don't let issues like this be closed for stale
