### ISSUE TITLE
Add a version option for each of the bins

### ISSUE THREAD

**Issue by malachma** [Azure/azure-container-networking#267]
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**Which release version?**:
any
---

**Which component (CNI/IPAM/CNM/CNS)**:
any
---

**Which Operating System (Linux/Windows)**:
any

For support engineers and admins it would be quit handy to know the current version installed, in order to determine whether the latest Version has been already installed.

Think About replacing the existing CNI bins by following this docu:
https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#upgrading-cni-on-existing-kubernetes-cluster-deployed-using-acs-engine

Support engineers are not able to determine what Version is already installed. Maybe we are on the latest already but could be also a version in between. So it is not known whether a specific bug is included or not.
For AKS Installations this Can also be usefull to know if there are doubts of the installed version

**Comment by sharmasushant** [comment]
this was added for azure cni

`azure-vnet --version`
