### ISSUE TITLE
Unable to send packets from pods on certain nodes to certain pods in the rest of the cluster.

### ISSUE THREAD

**Issue by nberkley-gp** [Azure/azure-container-networking#2672]
**What happened:** 
We've started seeing (node, pod) pairs such that pods on the node cannot send packets to the pod. Packets that attempt to traverse one of these routes instead seem to be repeatedly sent back to the original node (see attached pcap). Both pods and nodes that are members of a (node, pod) pair tend to be members of multiple such pairs.

**What you expected to happen:**  
Any pod in the cluster able to send packets to any other pod in the cluster.

**How to reproduce it:**  
We haven't been able to figure out how to induce the formation of one of these pairs (it seems to be a random low probability event at pod creation time), but once one is identified any attempt to send a packet from a pod on the node side to the pod side fails.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
AKS 1.27.9 (also seen on 1.26.10)
Azure CNI Version v1.4.39.1

**Operating System (Linux/Windows):**  
Linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**
Linux aks-general1az3-23172486-vmss000005 5.15.0-1059-azure #67-Ubuntu SMP Sat Mar 9 03:28:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know?:**
We've been seeing several seemingly related issues since Azure pushed some changes to the azure-cns daemonset last week, though we only managed to finally isolate some of these pods last weekend so hard to say with certainty that it's all the same issue.

Packet capture taken from the node side of a pair, initial SYN packet comes from the pod side:
[bad.pcap.gz](https://github.com/Azure/azure-container-networking/files/14858538/bad.pcap.gz)

**Comment by nberkley-gp** [comment]
Sorry, what's a CRI?

**Comment by rbtr** [comment]
https://azure.microsoft.com/en-us/support/create-ticket/ against AKS so that you can share things like your cluster FQDN and we can get logs etc

**Comment by nberkley-gp** [comment]
Oh, a support ticket, got it. We already have one open. Request ID 2404020040012796

**Comment by nberkley-gp** [comment]
Learnings/speculation since first filing this:

A bad (pod, node) pair persists through a node reboot, but not a redeploy. This implies a couple of things:
1. The bad state lives on the node side of the pair (seemed likely, but this confirms it)
2. The bad state lives on the underlying host, not the VM. The bug leading to the bad state could still live in a number of levels, though.

This lines up with out theory that the issue boils down to route propagation failing when new pods start up and never converging (except as part of VM migration?). Still not clear why that's happening, though.
