### ISSUE TITLE
Invalid CIDR address

### ISSUE THREAD

**Issue by mersadk** [Azure/azure-container-networking#271]
I have VM on Azure and run Docker containers in it. I want to connect Docker containers directly to Azure VNET. I've downloaded azure-vnet-cnm-windows-amd64-v1.0.14, started plugin and followed steps from https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md

When I run following command
`docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.0.0.0/24 azure`
I get error

> Error response from daemon: invalid CIDR address:

Host is Windows 10 Pro.

What I am doing wrong?

**Comment by mersadk** [comment]
I was able to solve this by creating new IP configuration. It's mentioned [here](https://github.com/Azure/azure-container-networking/blob/master/docs/ipam.md) in documentation, but it can be easily done using portal.azure.com (find your _Network Interface_, go to _IP configurations_ and add new).     
I also had to run _azure-vnet-plugin.exe_ as admin.

But it still doesn't work, now I have issue described in #235.

**Comment by sharmasushant** [comment]
Lets track #235 separately. I am closing this one.
