### ISSUE TITLE
Random Windows node stops working with "NetworkPlugin cni failed to set up pod ..." error

### ISSUE THREAD

**Issue by ai2admin** [Azure/azure-container-networking#272]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**:
acs-engine v0.25.3
kubernetes v1.10.9
CNI v0.3.0
Windows Server 1709

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Linux master, Windows agent

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

10.0.16299.371 (WinBuild.160101.0800)

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

---

**What happened**:
Nodes randomly start failing in a few days of use. New pods stop being created on a particular node, with the error being Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "my-pod-648b47bcc-hj8tm_t-1ea5c65c-0824-4d63-8f5f-f8e820322e28" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

Same deployment succeeds on other nodes.

kubectl get nodes returns node status as "Ready".

Restarting the node doesn't help. Recreating the cluster fixes the issue for a few days, then a random node goes bad again

---

**What you expected to happen**:
Nodes should be stable and available

---

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with a few Windows nodes, use it with a few pods. One of the nodes will stop creating new pods in a few days.

---

**Anything else we need to know**:
The failed node shows no resource stress.

---

**Comment by tamilmani1989** [comment]
Thank you @ai2admin . We are working on that

**Comment by ashvindeodhar** [comment]
@ai2admin this is fixed in the latest CNI release : https://github.com/Azure/azure-container-networking/releases/tag/v1.0.16
