### ISSUE TITLE
no json in C:\cni\netconf

### ISSUE THREAD

**Issue by PleachiM** [Azure/azure-container-networking#274]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**Which release version?**:
v1.0.12
---

**Which component (CNI/IPAM/CNM/CNS)**:
cni
---

**Which Operating System (Linux/Windows)**:
Windows 
---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

10.0.17763.168 (WinBuild.160101.0800)
---

From the documentation 
CNI network configuration file
The CNI network configuration file is described in JSON format. It is, by default, present in /etc/cni/net.d for Linux and c:\cni\netconf for Windows. The file specifies the configuration of the plug-in and is different for Windows and Linux. The json that follows is a sample Linux configuration file, followed by an explanation for some of the key settings. You don't need to make any changes to the file:

there is no json file for windows. 

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker
---

**What happened**:
That I can find a json file like in described in the documentation
---

**What you expected to happen**:
To find a json config example for windows or even a guide for this
---

**How to reproduce it** (as minimally and precisely as possible):
Just follow the guide here ... 
https://docs.microsoft.com/en-us/azure/virtual-network/deploy-container-networking#cni-network-configuration-file
---

**Anything else we need to know**:

---

**Comment by ashvindeodhar** [comment]
Please check it under C:\k\azurecni\netconf\ as 10-azure.conflist
