### ISSUE TITLE
Create K8s deployment for upgrades

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-container-networking#277]
Please create a K8s deployment file that can do CNI upgrades like Amazon.

https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

What would be even better would to be to go one step further and make this capable of auto upgrades.

**Comment by MikeMichel** [comment]
What is the release flow anyway? It seems it is not a node reboot. Does a new aks node will get the latest azure-npm? Do I need to change all daemonsets myself?

**Comment by matmerr** [comment]
Tagging in @paulgmiller from AKS.

Currently upgrades happen through cluster/agentpool upgrades.

**Comment by paulgmiller** [comment]
AKS is working on an auto upgrade feature we're trying to preview in the fall. That would bring up your azure cni when the node upgrades.
