### ISSUE TITLE
Getting an error "failed to set gateway while updating gateway: route for the gateway could not be found: network is unreachable"

### ISSUE THREAD

**Issue by RahulMetangale** [Azure/azure-container-networking#280]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:
1.0.15
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNM
---

**Which Operating System (Linux/Windows)**:
Ubuntu 16.04
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux AZLXSPTSYNDEVTSTAP01 4.15.0-1035-azure #36~16.04.1-Ubuntu SMP Fri Nov 30 15:25:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**
NA
---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker version 18.09.0, build 4d60db4
---

**What happened**:
Getting following error while connecting containers to Azure Virtual Network
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2018-12-18T13:41:15Z\\\\\\\" level=fatal msg=\\\\\\\"failed to set gateway while updating gateway: route for the gateway X.X.X.1 could not be found: network is unreachable\\\\\\\"\\\\n\\\"\"": unknown.
---

**What you expected to happen**:
Container should get IP address from Azure VNET
---

**How to reproduce it** (as minimally and precisely as possible):
Install Azure Container Networking driver
$ PLUGIN_VERSION="v1.x.x"
$ curl -OsSL https://github.com/Azure/azure-container-networking/releases/download/${PLUGIN_VERSION}/azure-vnet-cnm-linux-amd64-${PLUGIN_VERSION}.tgz
$ tar xzvf azure-vnet-cnm-linux-amd64-${PLUGIN_VERSION}.tgz
$ ./azure-cnm-plugin&

Added additional IP address to docker host.

Created docker network
docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=[subnet] azure

Create container in network
docker run -it --rm --net=azure ubuntu:latest /bin/bash
---

**Anything else we need to know**:

---

**Comment by tamilmani1989** [comment]
@RahulMetangale Can you send me /var/log/azure-vnet.log file? Also let me know the timestamp you tried to create container

**Comment by RahulMetangale** [comment]
@tamilmani1989 if you are available now we can do a screen share. Else please let me know a suitable time to discuss this.

**Comment by RahulMetangale** [comment]
@tamilmani1989 Hi Please let me know when we can do a screen sharing session.

**Comment by RahulMetangale** [comment]
@tamilmani1989 can you please let me know on which linux OS and version this driver is texted. I can try using the same OS.

**Comment by tamilmani1989** [comment]
@RahulMetangale we are not supporting CNM currently. Why don't you try CNI?

**Comment by RahulMetangale** [comment]
@tamilmani1989 I am not using Kubernetes or DC/OS hence i can not use CNI. Most recent release v1.0.17 also has CNM drivers, but it is not supported?

**Comment by tamilmani1989** [comment]
You don't need kuberentes/DCOS setup to run CNI. Please look at [scripts/docker-run.sh.](https://github.com/Azure/azure-container-networking/blob/master/scripts/docker-run.sh)

place azure-vnet and azure-vnet-ipam under /opt/cni/bin

`docker-run.sh <container-name> <namespace> <image>`

Give namespace as **default**.

Even I can repro the issue in CNM. Right now we don't have any timeline for that fix.

**Comment by tamilmani1989** [comment]
@RahulMetangale  does that work for you?

**Comment by RahulMetangale** [comment]
@tamilmani1989 Thank you it worked!. i have posted the detailed steps to use CNI network  of this driver with docker on [my blog](https://medium.com/@rahul.metangale/connecting-docker-container-to-azure-virtual-network-ff8a19913574) 
If documentation contribution is allowed i will be happy to send a PR.

**Comment by ninzavivek** [comment]
We are investigating the issue.

**Comment by guddutopper** [comment]
I have follow up on this issue, i am able to assigned IP address to the containers from the azure Vnet as the steps given in the [blog](https://medium.com/@rahul.metangale/connecting-docker-container-to-azure-virtual-network-ff8a19913574)

But I am not able to communicate between the containers, for examples I assigned IP addresses to two container from the same subnet of a vnet but they are not able to communicate to each other, any help ?
