### ISSUE TITLE
KillPodSandbox errors relating to CNI after windows node reboot

### ISSUE THREAD

**Issue by carlsoncoder** [Azure/azure-container-networking#287]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**Which release version?**:
1.0.15
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI
---

**Which Operating System (Linux/Windows)**:
Windows - Datacenter-Core-1803-with-Containers-smalldisk
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**
10.0.17134.471 (WinBuild.160101.0800)
---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes 1.13.1
---

**What happened**:

I deployed a cluster with Windows Worker nodes on the 1803 image.  They were working fine for a while, until Windows Update automatically rebooted the nodes to apply updates.  After this, every single pod on the windows node went into an "Error" state (as shown in kubectl get pods), and if you describe the pod in kubectl, you'll see each pod on that node has thousands of these errors:

Normal SandboxChanged 112s (x6216 over 34h) kubelet, 4149k8s000 Pod sandbox changed, it will be killed and re-created.

The kubelet.err logs on the machine show thousands of these errors:

```
E0110 13:01:52.842808    5932 cni.go:345] Error deleting jott102-live_worker-services-deployment-7fdcb87489-cntlx/c6283daf1034ddef06ec3538258d8794f297984f660dd17d9bbc4c86a0db6f63 from network azure-vnet/azure: Failed to delete endpoint: HNS failed with error : The endpoint was not found. 
E0110 13:01:52.842808    5932 remote_runtime.go:119] StopPodSandbox "c6283daf1034ddef06ec3538258d8794f297984f660dd17d9bbc4c86a0db6f63" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "worker-services-deployment-7fdcb87489-cntlx_jott102-live" network: Failed to delete endpoint: HNS failed with error : The endpoint was not found. 
E0110 13:01:52.842808    5932 kuberuntime_manager.go:815] Failed to stop sandbox {"docker" "c6283daf1034ddef06ec3538258d8794f297984f660dd17d9bbc4c86a0db6f63"}
E0110 13:01:52.842808    5932 kuberuntime_manager.go:610] killPodWithSyncResult failed: failed to "KillPodSandbox" for "c78ecc4a-139a-11e9-99f9-000d3a1405e7" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"worker-services-deployment-7fdcb87489-cntlx_jott102-live\" network: Failed to delete endpoint: HNS failed with error : The endpoint was not found. "
E0110 13:01:52.842808    5932 pod_workers.go:190] Error syncing pod c78ecc4a-139a-11e9-99f9-000d3a1405e7 ("worker-services-deployment-7fdcb87489-cntlx_jott102-live(c78ecc4a-139a-11e9-99f9-000d3a1405e7)"), skipping: failed to "KillPodSandbox" for "c78ecc4a-139a-11e9-99f9-000d3a1405e7" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"worker-services-deployment-7fdcb87489-cntlx_jott102-live\" network: Failed to delete endpoint: HNS failed with error : The endpoint was not found. "
```

The azure-vnet.log files show errors with the endpoints as well:

```
2019/01/11 13:21:11 [cni-net] Plugin started.
2019/01/11 13:21:11 [cni-net] Processing DEL command with args {ContainerID:88acde57b56d1699533cc07b00633e4fccb0174e192869c1ec3df1006ce6dd42 Netns:none IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=jott102-live;K8S_POD_NAME=web-services-deployment-85759b89c5-vsg48;K8S_POD_INFRA_CONTAINER_ID=88acde57b56d1699533cc07b00633e4fccb0174e192869c1ec3df1006ce6dd42 Path:c:\k\azurecni\bin}.
2019/01/11 13:21:11 [cni-net] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: InfraVnetAddressSpace: PodNamespaceForDualNetwork:[] MultiTenancy:false EnableSnatOnHost:false EnableExactMatchForPodName:false CNSUrl: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[10.0.0.10 168.63.129.16] Domain: Search:[svc.cluster.local] Options:[]} RuntimeConfig:{PortMappings:[]} AdditionalArgs:[{Name:EndpointPolicy Value:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Name:EndpointPolicy Value:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}]}.
2019/01/11 13:21:11 Trying to retrieve endpoint id 88acde57-eth0
2019/01/11 13:21:11 [net] Deleting endpoint 88acde57-eth0 from network azure.
2019/01/11 13:21:11 Trying to retrieve endpoint id 88acde57-eth0
2019/01/11 13:21:11 [net] HNSEndpointRequest DELETE id:e5a24a6f-2ac9-47e3-8798-f8041b9c0256
2019/01/11 13:21:11 [net] HNSEndpointRequest DELETE response:<nil> err:HNS failed with error : The endpoint was not found. .
2019/01/11 13:21:11 [net] Failed to delete endpoint 88acde57-eth0, err:HNS failed with error : The endpoint was not found. .
2019/01/11 13:21:11 [azure-vnet] Failed to delete endpoint: HNS failed with error : The endpoint was not found. .
2019/01/11 13:21:11 [cni-net] DEL command completed with err:Failed to delete endpoint: HNS failed with error : The endpoint was not found. .
2019/01/11 13:21:11 Failed to execute network plugin, err:Failed to delete endpoint: HNS failed with error : The endpoint was not found. .
```

(Note:  These logs were from node 4149k8s000 (IP 10.240.0.35))
---

**What you expected to happen**:
I would expect that CNI would function normally and the pods would stay in a running state after a successful node reboot
---

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster using aks-engine v0.28.0, with Windows worker nodes on image Datacenter-Core-1803-with-Containers-smalldisk.  It seems auto-update/reboot is enabled by default, so wait for it to apply the update(s) and reboot.  After that you should see this error.

---

**Anything else we need to know**:
This seems similar to and possibly related to https://github.com/Azure/azure-container-networking/issues/283.  There is a note in there that "We also need to remove the old HNS networks on reboot", which might apply to this issue as well?
---

**Comment by sharmasushant** [comment]
@ashvindeodhar  Will v1.0.16 help with this?

**Comment by ashvindeodhar** [comment]
@carlsoncoder we released a new version https://github.com/Azure/azure-container-networking/releases/tag/v1.0.16 that fixed issue #283. Can you please pick up this release and check?

**Comment by ashvindeodhar** [comment]
@carlsoncoder you are right. Use following in your cluster definition.
			"kubernetesConfig": {
				"azureCNIURLLinux": "https://github.com/Azure/azure-container-networking/releases/download/v1.0.16/azure-vnet-cni-linux-amd64-v1.0.16.tgz",
				"azureCNIURLWindows": "https://github.com/Azure/azure-container-networking/releases/download/v1.0.16/azure-vnet-cni-windows-amd64-v1.0.16.zip"
			}

**Comment by carlsoncoder** [comment]
@ashvindeodhar So far so good.  Have had a cluster running with a few reboots and so far haven't seen any failures!

**Comment by ashvindeodhar** [comment]
@carlsoncoder closing this issue as you have confirmed you don't see this issue anymore. Please reopen if needed.
