### ISSUE TITLE
Snap package support(Feature Request)

### ISSUE THREAD

**Issue by mikeroyal** [Azure/azure-container-networking#288]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by saiyan86** [comment]
@mikeroyal Thanks for the contribution! However, is there any specific reason for doing this? Azure CNI is mainly consumed by AKS/AKS-engine in Azure. Do you have any scenario in which we need this?

**Comment by saiyan86** [comment]
@mikeroyal This is under consideration. But unfortunately we don't have cycles to look into this right now. Will look into this later. Closing this for now.
