### ISSUE TITLE
Add kubernetes annotations for Ip address management

### ISSUE THREAD

**Issue by korallo159** [Azure/azure-container-networking#2881]
**Component (Azure NPM or Azure CNI):**
Azure NPM

**Describe in detail the feature/behavior/change you'd like to see:**  
I would like to add an annotation to a Kubernetes namespace to ensure that pods within that namespace are assigned IP addresses exclusively from a specified range from subnet.

I have one big subnet, and I want to use specific ip addresses on namespace from this subnet.
Node pools share this one subnet.

Example annotation in calico for ip pool object: 
cni.projectcalico.org/ipv4pools: '["pool-1", "pool-2"]'

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  
Linux

**Comment by korallo159** [comment]
Up

**Comment by rbtr** [comment]
@korallo159 I think this needs to be a feature request to [AKS](https://github.com/Azure/AKS)

**Comment by korallo159** [comment]
I created feature request in AKS

**Comment by rbtr** [comment]
we will track it in https://github.com/Azure/AKS/issues/4456
