### ISSUE TITLE
Should the azure-npm work with AKS & Advanced Networking?

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-container-networking#291]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI / azure-npm
---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kuberentes: Azure AKS (1.11.5) with Advanced Networking
---

**What happened**:
Installed

>  kubectl apply -f https://raw.githubusercontent.com/Azure/acs-engine/master/parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml

 but network policies get ignored
---

**What you expected to happen**:
Network Policies get enforced
---

**How to reproduce it** (as minimally and precisely as possible):
Apply  kubectl apply -f https://raw.githubusercontent.com/Azure/acs-engine/master/parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml and try to deny traffic to a namespace.

---

**Anything else we need to know**:

---

**Comment by saiyan86** [comment]
@cmendible Thanks for the feedback! I will take a look.

**Comment by saiyan86** [comment]
Hi @cmendible , could you please share the policy yaml you are applying? Everything in my cluster works fine.

**Comment by cmendible** [comment]
Hi @saiyan86 I was using the policy explained here to deny all traffic:

https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/01-deny-all-traffic-to-an-application.md

**Comment by saiyan86** [comment]
@cmendible 
#307 should address this among a bunch of new changes.
