### ISSUE TITLE
Kubernetes: Windows nodes may break under heavy load

### ISSUE THREAD

**Issue by bclau** [Azure/azure-container-networking#292]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**: v1.0.16

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**: Windows 

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"** 10.0.17763.194 (WinBuild.160101.0800)

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)** Kubernetes v1.13.2

---

**What happened**:

Running dozens of pods per node results in the nodes no longer being usable, and the following can be observed: 

- new pods will no longer be able to enter a ``Running`` state, and executing ``kubectl describe`` on the pods will yield the following:

      Warning  FailedCreatePodSandBox  <invalid>  kubelet, 1924k8s001  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "1b21d82939258f7d3bcba747667d3fdcb400d0e351ae32ed271b6bddd648ac08" network for pod "load-small-4-686657774-skj55": NetworkPlugin cni failed to set up pod "load-small-4-686657774-skj55_load-30-nodepods-1-3440" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

- looking through the ``kubelet`` logs, the following can be seen: https://paste.ubuntu.com/p/mq5r7bVMxw/

- looking through the ``azure-vnet`` logs, the following are seen over and over: https://paste.ubuntu.com/p/GFk7C8NWwh/

- executing ``docker ps -a`` will also reveal quite a few ``kubeletwin/pause`` zombie containers which have not been deleted.

- worst case scenario, some Windows nodes will become unusable and unreachable, even after reboot, which makes diagnosing difficult.

Other observations:

- ``kubelet`` will generate a lot of logs retrying to "clean" the mentioned zombie containers, only to fail because of the mentioned "unexpected end of JSON input" errors.

---

**What you expected to happen**:

Parsing errors should not occur in kubelet or azure-vnet-cni.
Should be able to spawn dozens of pods without breaking the nodes.

---

**How to reproduce it** (as minimally and precisely as possible):

This issue can easily be reproduced by running the following test on a new environment deployed with aks-engine:

    [sig-scalability] Load capacity [Feature:ManualPerformance] should be able to handle 30 pods per node Random with 0 secrets, 0 configmaps and 0 daemons

---

**Anything else we need to know**:

---

**Comment by PatrickLang** [comment]
cc @dineshgovindasamy @daschott

**Comment by sharmasushant** [comment]
@ashvindeodhar  seems like state is messed up: 
[net] Failed to restore state, err:invalid character '\x00' looking for beginning of value

@bclau Can you share the azure-vnet.json file from the node you are seeing the error?

**Comment by bclau** [comment]
@sharmasushant huh. This is quite interesting. The node managed to recover and I could fetch the logs / files. Looked into the `azure-vnet.json` file you mentioned. This is what's there: [1]. No kidding. 28KB of whitespace. The other node had a proper JSON, and did not have any \x00 errors in it.

[1] https://paste.ubuntu.com/p/vw9gJsz8ct/

**Comment by ashvindeodhar** [comment]
@bclau  can you please pick up the latest release that addressed lock store timing out issue: https://github.com/Azure/azure-container-networking/releases/tag/v1.0.17-rc1 . This also addresses the subsequent "unexpected end of JSON input". I don't see these errors anymore. I was never able to repro '\x00' issue.

**Comment by ashvindeodhar** [comment]
@bclau did you get a chance to try v1.0.17-rc1? That one fixed similar issue seen while spawning multiple pods (#289 )

**Comment by ashvindeodhar** [comment]
Released https://github.com/Azure/azure-container-networking/releases/tag/v1.0.17. Closing this issue.
