### ISSUE TITLE
Windows Container does not have any network connectivity when it starts

### ISSUE THREAD

**Issue by bclau** [Azure/azure-container-networking#299]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**Which release version?**: v1.0.17

---

**Which component (CNI/IPAM/CNM/CNS)**: CNI

---

**Which Operating System (Linux/Windows)**: Windows

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

10.0.17763.194 (WinBuild.160101.0800)

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Kubernetes

---

**What happened**:

Networking takes too long to set up after the containers start.

When the container first starts, it doesn't have connectivity for about ~5 seconds [1] (up to ~40 seconds if 4 pods are being spawned simultaneously [2]). Looking at the timestamps in [1] and [3], the container starts to have network connectivity when an endpoint is finally attached to it (at 16:37:16).

This issue does not occur when using flannel l2bridge [4].

For full logs, see [5].

[1] https://paste.ubuntu.com/p/dgBNgCP8Mc/
[2] https://paste.ubuntu.com/p/gQK9tvPS46/
[3] https://paste.ubuntu.com/p/bXQ4ss9rTR/
[4] https://paste.ubuntu.com/p/kcFKgvkTmj/
[5] https://www.dropbox.com/sh/xzktc5y5jejpjdg/AAAEVu-hjqFkdZ2hHdOwD0IMa?dl=0

---

**What you expected to happen**:

The container should have network connectivity when it starts.

---

**How to reproduce it** (as minimally and precisely as possible):

Run the following commands:

    kubectl create namespace test-ns
    kubectl create -n test-ns -f dns_pod.yaml  # the yaml file can be found at [6]
    kubectl logs -n test-ns test-dns-1

See that the container is not able to resolve the Kubernetes DNS name for a few seconds after it starts. Additionally, try spawning several pods on the same node to see that the containers do not have network connectivity for an even longer period of time.

[6] https://paste.ubuntu.com/p/KGXxjHThnt/

---

**Anything else we need to know**:

---

**Comment by zhiweiv** [comment]
I reported this issue before at https://github.com/Azure/aks-engine/issues/189, per https://github.com/Azure/aks-engine/issues/414, it is a bug Windows?

**Comment by bclau** [comment]
From my experience, this is an issue with azure-vnet-cni itself. I have tried this on separate deployments using flannel overlay or l2bridge instead of azure-vnet-cni and this issue was significantly smaller.

**Comment by ashvindeodhar** [comment]
@bclau I have verified that v1.0.18-rc1 helps with the connectivity. Please let me know.

**Comment by ashvindeodhar** [comment]
@bclau can you comment if this issue is still there with latest release?

**Comment by ashvindeodhar** [comment]
Closing the issue as it's resolved with v1.0.18
