### ISSUE TITLE
Failed to start IPAM plugin, err:invalid character '\\x00' looking for beginning of value.

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-container-networking#306]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:
1.0.17-rc1
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI
---

**Which Operating System (Linux/Windows)**:
Windows
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**
10.0.17763.194 (WinBuild.160101.0800)
---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes
---

**What happened**:
All Pods became error on a Windows node, The error was 
`Warning  FailedCreatePodSandBox  59m                 kubelet, 3831k8s001  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e299e18a81aa5cd0b16399bd1d93171d904f8f68e9571479f812c75017e9c779" network for pod "daoinsider-apiweb-fb85b5dfb-b2lr8": NetworkPlugin cni failed to set up pod "daoinsider-apiweb-fb85b5dfb-b2lr8_default" network: Failed to allocate pool: Failed to delegate: netplugin failed but error parsing its diagnostic message "Failed to start IPAM plugin, err:invalid character '\\x00' looking for beginning of value.\n": invalid character 'F' looking for beginning of value`
  
In C:\K, azure-vnet-ipam.json was 3KB with only whitespace in it, azure-vnet.json was missing. The error began to appear since 2019/02/28 07:09:43 in azure-vnet-ipam.log. I attached them to azure-vnet-ipam.zip.
[azure-vnet-ipam.zip](https://github.com/Azure/azure-container-networking/files/2914647/azure-vnet-ipam.zip)

Similiar with #292.

---

**What you expected to happen**:
Pods work well in Windows nodes

**Comment by ashvindeodhar** [comment]
@zhiweiv can you please provide the repro steps? We have tried but could never repro this.

**Comment by zhiweiv** [comment]
@ashvindeodhar 
It is the first time this issue occurred in our environment, it just happend suddenly.  I can see the OS reooted at 2/28/2019, 7:08:05 AM in azure-vnet-ipam.log I provided.

**Comment by zhiweiv** [comment]
I checked kubelet.log, `Cleaning up old HNS network found` was not shown in it. Shall we delete relative files whether the network exists or not in https://github.com/Azure/aks-engine/blob/master/parts/k8s/windowskubeletfunc.ps1?
[kubelet.log](https://github.com/Azure/azure-container-networking/files/2917798/kubelet.log)

**Comment by ashvindeodhar** [comment]
@zhiweiv is this issue reproducible with 1.0.18?

**Comment by zhiweiv** [comment]
Not reproduced with 1.0.18 yet.

**Comment by zhiweiv** [comment]
I plan to upgrade to latest AKS-Engine release this week, close this. I will open another issue if error occurs again.
