### ISSUE TITLE
azure cni support bandwidth plugin

### ISSUE THREAD

**Issue by zhangchl007** [Azure/azure-container-networking#3076]
**Component (Azure NPM or Azure CNI):**
Azure CI

**Describe in detail the feature/behavior/change you'd like to see:**  

azure cni bandwidth plugin support since AWS can enable this feature.

https://github.com/aws/amazon-vpc-cni-k8s

ENABLE_BANDWIDTH_PLUGIN (v1.10.0+)
Type: Boolean as a String

Default: false

Setting ENABLE_BANDWIDTH_PLUGIN to true will update 10-aws.conflist to include upstream [bandwidth plugin](https://www.cni.dev/plugins/current/meta/bandwidth/) as a chained plugin.

NOTE: Kubernetes Network Policy is supported in Amazon VPC CNI starting with version v1.14.0. Note that bandwidth plugin is not compatible with Amazon VPC CNI based Network policy. Network Policy agent uses TC (traffic classifier) system to enforce configured network policies for the pods. The policy enforcement will fail if bandwidth plugin is enabled due to conflict between TC configuration of bandwidth plugin and Network policy agent. We're exploring options to support bandwidth plugin along with Network policy feature and the issue is tracked https://github.com/aws/aws-network-policy-agent/issues/68

**Orchestrator(e.g. Kubernetes, Docker):**  

AKS 1.29

**Operating System (Linux/Windows):**  
ubuntu 22.02/Azure Linux

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

**Comment by rbtr** [comment]
Hey @zhangchl007, this type of Kubernetes configuration/feature request should be filed against [AKS](https://github.com/Azure/aks)
