### ISSUE TITLE
Mariner 2.0 VM host support for docker CNI

### ISSUE THREAD

**Issue by et1975** [Azure/azure-container-networking#3219]
**Component (Azure NPM or Azure CNI):** CNI

**Describe in detail the feature/behavior/change you'd like to see:**  
- The official [docs for provisioning a host for running docker](https://learn.microsoft.com/en-us/azure/virtual-network/deploy-container-networking-docker-linux) don't work for Mariner2.0, which is required for internal compliance.
- Would also be good to see how/if the CNI works for [Management NIC V2](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/452761/Vnet-Injection-V2).

**Orchestrator(e.g. Kubernetes, Docker):**  
Docker

**Operating System (Linux/Windows):**  
Mariner 2.0 Linux.

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]
The installation scripts [attempt to check for etables and install via `apt`](https://github.com/Azure/azure-container-networking/blob/master/scripts/install-cni-plugin.sh#L36).

**Comment by rbtr** [comment]
The CNI does work on Mariner/Azure Linux so maybe this is just a documentation problem. At what point do you have issues?

**Comment by et1975** [comment]
Updated the original description with the link to the specific failing step. 
I have no reason to think that it doesn't work in principle, but I don't see any instructions. Is it available as a standard Mariner distro package?
Also note the second bullet point, the reason I'm looking at this at all is because have to use the management NIC, which seems to be only available for VMs.

**Comment by rbtr** [comment]
Ah, the script expects `apt`. Looks like if you preinstall `ebtables` you could bypass this 
```bash
if [ ! -e /sbin/ebtables ]
then
    printf "Installing ebtables package..."
    apt-get update
    apt-get install -y ebtables
    printf "done.\n"
else
    echo "Package ebtables is already installed."
fi
```
https://github.com/Azure/azure-container-networking/blob/master/scripts/install-cni-plugin.sh#L33

We don't distribute Linux packages.
