### ISSUE TITLE
Encyption in azure-cni? 

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-container-networking#327]
**Is this a request for help?**:
Kind of?

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

---

**Which release version?**:
lateset

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI?

---

**Which Operating System (Linux/Windows)**:
Linux

---

**For Linux: Include Distro and kernel version using "uname -a"**
Ubuntu 16

---

So we're pretty new to cni plugins but we were looking for a way ensure service to service encryption between all pods on an aks cluster. We're looking at service mesh but we were thinking something lower level might offer more garuntees. Seems like calico/weave [might](https://chrislovecnm.com/kubernetes/cni/choosing-a-cni-provider/) offer pod 2 pod encryption. We were wondering if Azure CNI had considered a similar functionality. We've a pretty hard dependency on AKS at this point so azure-cni would be our main option. Even if you have no intention of pursing encryption in the azure-cni plugin that would be helpful info too. 

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes
---

**Comment by tamilmani1989** [comment]
we dont have a plan to support encryption between pods in this cycle. Will consider this workitem in future.
