### ISSUE TITLE
Does Azure CNI have network bandwidth support?

### ISSUE THREAD

**Issue by qianwens** [Azure/azure-container-networking#334]
**Is this a request for help?**:

---yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---feature request

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

---cni

**Which Operating System (Linux/Windows)**:

---Linux

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---Kubernetes

**What happened**:

---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by sharmasushant** [comment]
We do not support restricting bandwidth for individual containers via Azure CNI today.
