### ISSUE TITLE
IPtables filtering drops packets when `sysctl net.bridge.bridge-nf-call-iptables=1`

### ISSUE THREAD

**Issue by kesor** [Azure/azure-container-networking#340]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

---

**Which release version?**:
v1.0.19

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux k8snode3 5.0.0 #1 SMP Mon Mar 4 06:05:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kuberntes v1.13.5

---

**What happened**:

When assigning secondary NIC IPs to PODs, the communication with PODs would work only between the VM and the container - not across containers and other VMs.

When sniffing traffic, it would seem that packets were seen on `azure0` bridge, but not on the `eth0` device. Which led to the conclusion that these packets never left the VM and there might be an issue with `iptables`.

After further investigation, it would seem that `sysctl net.bridge.bridge-nf-call-iptables=1` is at fault here, because it forces packets across the bridge devices to be filtered by various rules of Docker and such.

On the other hand, this setting is probably required when we want the POD IPs to be able to access the public internet. Since according to Microsoft documentation, the Public IP is only assigned to the primary IP of the NIC. Which means that `bridge-nf-call-iptables` must be set to `1` for public internet to work.

---

**What you expected to happen**:
I would expect to find some reference in the documentation shows that in fact `net.bridge.bridge-nf-call-iptables` needs to be disabled, or that the CNI would disable this flag on its own when it is used.

Or, if it is required to leave it enabled for public internet IP, then some detailed documentation is provided to explain how it should work and tips to troubleshoot dropped packets.

**Comment by tamilmani1989** [comment]
@kesor - we can't disable this setting. May be your setup has some iptable filter rules that drops the traffic from bridge. We have this setting enabled and its working e2e in our setup.

**Comment by tamilmani1989** [comment]
closing this since we dint get any response back
