### ISSUE TITLE
Windows Container does not have any network connectivity when it starts

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-container-networking#341]
#299 and Azure/aks-engine#189 are still occurring on v1.0.18.

**Comment by davidmatson** [comment]
Actually, I'm seeing this issue significantly more often on v1.0.18 than I was on v1.0.17.

**Comment by davidmatson** [comment]
I thought I had a workaround, but even that isn't covering all cases. Here's what I'm doing to wait for the network / DNS to be ready:

```c#
ServiceController dnsClientService = new ServiceController("dnscache");
dnsClientService.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromSeconds(30));
```

But here's an example exception I'm still getting sometimes (from code that runs after the code above):
```
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: '<myaccountname>.queue.core.windows.net' ---> System.Net.WebException: The remote name could not be resolved: '<myaccountname>.queue.core.windows.net'
```

Is there a different service I should check before treating the network connection as up? Or some other way to check for "safe to run code in this container that hits the network" besides checking the status of some service?

**Comment by AlexTkatch** [comment]
My team has recently hit this issue. We ended up implementing a simple loop trying Dns.GetHostEntry for a well-known address repetitively until either it succeeds or there is a timeout. I have observed that delays occasionally cross 30 seconds!

**Comment by davidmatson** [comment]
@AlexTkatch - thanks; I thought I had tried that approach and it hit issues with caching inside that API - if I queried too soon, it would never return true because it had cached a "it doesn't work" result. But maybe I'm misremembering, or it's version-specific or something like that.

**Comment by AlexTkatch** [comment]
Dns.GetHostEntry throws when it cannot resolve the name, so the code is a loop with a try/catch and sleep inside it.

**Comment by davidmatson** [comment]
Yeah, I thought it got "stuck" throwing, but I think I was trying an internal DNS name (maybe localhost machine name or something like that). An external DNS name might work differently.

**Comment by ashvindeodhar** [comment]
This is not Azure CNI issue. This is kubernetes issue and here is the link to the issue opened https://github.com/kubernetes/kubernetes/issues/78947

**Comment by davidmatson** [comment]
/remove-stale
(ensuring we keep tracking upstream issue; it was closed)

**Comment by davidmatson** [comment]
@ashvindeodhar - can you re-open the upstream issue? I tried, but it wouldn't let me.

**Comment by zhiweiv** [comment]
I think it is already fixed in Windows Containerd, https://github.com/microsoft/Windows-Containers/issues/132.

**Comment by MostefaKamalLala** [comment]
> I think it is already fixed in Windows Containerd, [microsoft/Windows-Containers#132](https://github.com/microsoft/Windows-Containers/issues/132).

Exactly.

@davidmatson if you cannot upgrade to contrainerd runtime you can simply wait for the host to be resolved. It a good workaround.
