### ISSUE TITLE
Unable to communicate between the docker containers from the same subnet after using CNI to assing IPs from azure vnet

### ISSUE THREAD

**Issue by guddutopper** [Azure/azure-container-networking#352]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**Which release version?**:

1.0.17

**Which component (CNI/IPAM/CNM/CNS)**:

CNI

**Which Operating System (Linux/Windows)**:

Linux

**For Linux: Include Distro and kernel version using "uname -a"**

Linux AZLXSPTFBTDEVAP04 4.15.0-1041-azure #45-Ubuntu SMP Fri Mar 15 14:41:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Docker version 18.09.2, build 6247962

**What happened**:

I was trying to give IP address to docker container using the CNI plugin, I was successfully able to give IP address to containers but they were not communicating with each other

**What you expected to happen**:

container should be able to communicate with other (ping the other container)

**How to reproduce it** (as minimally and precisely as possible):

I followed this [blog](https://medium.com/@rahul.metangale/connecting-docker-container-to-azure-virtual-network-ff8a19913574), which is based on this [document](https://docs.microsoft.com/en-us/azure/virtual-network/deploy-container-networking#deploy-plug-in-for-docker-containers)

using the above steps, i created two containers using command
"`sudo ./docker-run.sh alpine1 default alpine`" and "`sudo ./docker-run.sh alpine2 default alpine`"
I checked that the IP of alpine1 is 10.10.3.59 and IP of alpine2 is 10.10.3.60 which are the IPs I created inside a network interface as given in the above docs. so they did receive the IPs from a subnet inside vnet but when i ping alpine1 from alpine2 as "ping 10.10.3.59", it doesn't work, am i missing something here ? or i have to do some other configuration after this ?

**Anything else we need to know**:

**Comment by sharmasushant** [comment]
1. Can you reach other resources within the Vnet from these containers? e.g., have you tried reaching another VM deployed in same Vnet. 

2. Can you reach Internet from these conatiners. Try wget google.com to see if you can rach internet.

3. I would also check if a firewall is blocking the communication.

**Comment by guddutopper** [comment]
when i deploy these containers using the cni plugin, they don't have a network in common, in the script od 'docker-run.sh', the container by default join 'none' network, is that the reason they are not able to communicate with each other because docker is managing these container not azure.

**Comment by guddutopper** [comment]
and i am still confused whether i should CNI or CNM ?

**Comment by guddutopper** [comment]
Instead of using the CNI plugin, I used the CNM plugin v1.0.8 and I am able to communicate between my docker container on the IPs received from the azure virtual network.
