### ISSUE TITLE
Add pid to log

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-container-networking#354]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

---

**Which release version?**:
1.0.18

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Windows

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

---

**What happened**:
Each cni request starts a new process, but they share same log file. When multi cni requests received at same time, it is difficult to distinguish logs for each request.

---

**What you expected to happen**:
I would like to add process id for each request to its corresponding logs in log file.
A few proposed formats.
a. 2019/05/05 11:19:53 pid LogText
b. 2019/05/05 11:19:53 [pid] LogText
c. pid 2019/05/05 11:19:53 LogText
d. [pid] 2019/05/05 11:19:53 LogText

I can summit a PR with preferred format if this feature is acceptable.

---

**Anything else we need to know**:
Recently I observed lock file left which blocking the following requests, it occurred a few times(need manually delete the lock file). From the logs the request hang at somewhere, I can see the azure-vnet.exe exists which pid is same with the one in azure-vnet.json.lock.

Add pid to logs will help to better troubleshooting this issue.

**Comment by sharmasushant** [comment]
Yes, please feel free to submit the PR. option (b) looks good.
