### ISSUE TITLE
No address returned error on existing containers with pre-allocated ip's available (CNM plugin)

### ISSUE THREAD

**Issue by RHaest** [Azure/azure-container-networking#356]
**Is this a request for help?**:
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

**Which release version?**:
CNM Plugin 1.0.22 (azure-vnet-cnm-windows-amd64-v1.0.22.zip)

**Which component (CNI/IPAM/CNM/CNS)**:
CNM (or IPAM?)

**Which Operating System (Linux/Windows)**:
Windows Server 2016

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**
10.0.14393.2068 (rs1_release.180209-1727)

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       1578dcadd2
  Built:            05/04/2019 02:32:24
  OS/Arch:          windows/amd64
  Experimental:     true

**What happened**:
Followed the example:
1. Created a docker network with the azure-vnet plugin.
2. Pre-allocated IP-adresses in my Azure subnet.
3. Created Docker containers with those IP-addresses. Those containers persist (I only stop and start them).
4. The server reboots every night and the azure-vnet docker network is then recreated.    
5. When restarting the containers, in the beginning they all work but after a while the IP address seems to get "corrupted". The Docker start command then gives an error "No address returned".
Eventvwr:
Handler for POST /containers/39e0daf7e00a265767414eb08582bf69cb1742037de6008e12b6994ee47e5942/start returned error: No address returned
6. Solution is to assign a different ip to the container, then it will start again. However, my IP's are running out so I am looking for a solution with which I can fix the No address returned error. 

**What you expected to happen**:
That containers can always be restarted with the same ip address.

**How to reproduce it** (as minimally and precisely as possible):
1. Create an azure-vnet docker network to a private subnet with secondary ips pre-allocated, as described on this site. Example:
docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.0.50.0/24 myAzureNet
2. Create docker containers and connect those to both the nat network and the azure-vnet network with a fixed ip in the private subnet. Example:
docker network connect --ip 10.0.50.100 myAzureNet myContainer
docker network connect nat myContainer
3. Start the container, normally this would work. Reboot server a few times and perform same steps (do not recreate container, only start container) and after a while the No address returned error arises. Unfortunately I did not found the exact scenario when this error arises.

**Anything else we need to know**:
Tried both updating docker and the CNM plugin to the latest version, the error still occurs unfortunately. I tried searching on this site and the only slightly related issue I can find is this issue, but that only describes the pre-allocation of ip's and that's something I've done: https://github.com/Azure/azure-container-networking/issues/92. Any advice or help is highly appreciated, thanks!

**Comment by guddutopper** [comment]
@RHaest Hi, could you help me out as how you were able to get IP address to your docker container, I am getting stuck after creating the network itself, I am assuming you followed this link to deploy your contaienrs [cnm](https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md),
I have created secondary IPs alreeady in my network interface but unable to assign IP to container

**Comment by RHaest** [comment]
@guddutopper,  with this statement: docker network connect --ip 10.0.50.100 myAzureNet myContainer. So the 10.0.50.100 is the secondary IP on my azure nic and myAzureNet is my docker network (which I indeed created following the instructions in the link you posted).

**Comment by guddutopper** [comment]
ok let me try doing that and see what happens

**Comment by guddutopper** [comment]
btw are you able to join you container with default bridge network in docker along side the network created using azure-vnet driver ? does it create any issue ?

**Comment by RHaest** [comment]
Hi guddutopper, I do not use the bridge network, sorry I forgot to mention that. I first do "docker network prune -f", then I recreate the azure-vnet network (and nat is automatically created). So after that I only have these 3 networks:

PS C:\Windows\system32> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
e30742b881f0        myAzureNet          azure-vnet          local
fa205b890bc6        nat                 nat                 local
32d99ce61bc3        none                null                local

**Comment by guddutopper** [comment]
so you are creating your container first so by default it joins the bridge network or you are specifying "--net=none" flag while creating your container ?

**Comment by RHaest** [comment]
No, container is created with environment variables "--network=myAzureNet","--ip $ip". So by default a new container is directly joined to the azure-vnet network and is afterwards connected to the nat network.

**Comment by guddutopper** [comment]
I did a fresh install of the plugin on a newly created azure vm, i was able to create a network using command `sudo docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.10.3.0/24 azurenet`
after this i created a secondary IP configuration in my network interface `10.10.3.70`
now I tried to create my docker container as `sudo docker run -d  --name alpine1 --net=azurenet --ip=10.10.3.70 alpine /bin/sleep 1000000`
this is the response I get on my terminal 

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2019-05-09T07:36:42Z\\\\\\\" level=fatal msg=\\\\\\\"failed to set gateway while updating gateway: route for the gateway 10.10.3.1 could not be found: network is unreachable\\\\\\\"\\\\n\\\"\"": unknown. `

this is the response of `ifconfig -a`

`azure2    Link encap:Ethernet  HWaddr 00:0d:3a:17:56:04
          inet addr:10.10.3.15  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::20d:3aff:fe17:5604/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2752 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3507 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3497831 (3.4 MB)  TX bytes:707949 (707.9 KB)

docker0   Link encap:Ethernet  HWaddr 02:42:59:8e:05:03
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:59ff:fe8e:503/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:88 errors:0 dropped:0 overruns:0 frame:0
          TX packets:112 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:54756 (54.7 KB)  TX bytes:35479 (35.4 KB)

eth0      Link encap:Ethernet  HWaddr 00:0d:3a:17:56:04
          inet6 addr: fe80::20d:3aff:fe17:5604/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:76208 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22585 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:88738993 (88.7 MB)  TX bytes:4151810 (4.1 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:726 errors:0 dropped:0 overruns:0 frame:0
          TX packets:726 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:930045 (930.0 KB)  TX bytes:930045 (930.0 KB)

veth51ead5c Link encap:Ethernet  HWaddr 1a:7f:81:da:76:cd
          inet6 addr: fe80::187f:81ff:feda:76cd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:88 errors:0 dropped:0 overruns:0 frame:0
          TX packets:127 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:55988 (55.9 KB)  TX bytes:36625 (36.6 KB)`

could you tell me what is going wrong here ?

**Comment by RHaest** [comment]
I am not sure, you are using Linux as host, I use windows server. I assume you have to specify a gateway in your network creation.

**Comment by guddutopper** [comment]
if I try to give gateway, I face this error
`platformdev1@AZLXSPTFBTDEVAP04:~$ sudo docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.10.3.0/24 --gateway=10.10.3.1 azurenet
Error response from daemon: failed to allocate gateway (10.10.3.1): No address returned`

**Comment by RHaest** [comment]
I am sorry, I am not familiar with docker on Linux. On my environment (Windows Server 2016) the scenario works.

**Comment by guddutopper** [comment]
Hi Rhaest, I have switched to windows server just to test this CNM plugin, I have installed docker on machine but when I pull any image it gives me this error - `no matching manifest for windows/amd64 10.0.14393 in the manifest list entries `
could you help me on this? did you follow any document while installing docker on windows server 2016

**Comment by RHaest** [comment]
Hi guddutopper, I just used the default Windows server with containers image as VM image on Azure so I did not have to install docker myself. So unfortunately I am not familiar with your issue.

**Comment by RHaest** [comment]
Hi guddutopper, did you get any further with this? I still get the No address returned error occassionally. Thanks!

**Comment by RHaest** [comment]
Bump on this issue: anyone got any updates on this issue? This is keeping our environment very unstable which is something we want to prevent!

**Comment by tamilmani1989** [comment]
@guddutopper  We had an issue in Linux CNM and this PR #375   will fix it. Also use the following command to create network:
 sudo docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.10.3.0/24 <network_name> (do not pass gateway option)

**Comment by tamilmani1989** [comment]
We released new version with fix
