### ISSUE TITLE
Http request to all pods in one Windows node timeout intermittently

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-container-networking#359]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

---

**Which release version?**:
1.0.18

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Windows
10.0.17763.194 (WinBuild.160101.0800)

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
AKS-Engine with Kubernetes

---

**What happened**:
Every few hours, all pods in a Windows nodes unable to accept http request, for example there is a pod with ip 10.2.0.65 on Windows node 3831k8s014, when the issue occurs, I am able to curl http://10.2.0.65/healthz in the pod(after exec -i podname cmd), but I get timeout by curl http://10.2.0.65/healthz on node 3831k8s014. After some time it comes back to normal, after some time it occurs again.
I can ping 10.2.0.65 successfully on node 3831k8s014 when issue occurs.

---

**What you expected to happen**:
Able to connect to pod.

---

**How to reproduce it** (as minimally and precisely as possible):
Not sure, it keep reproduce every few hours or less.

---

**Anything else we need to know**:
I can collect anything you want when the issue reproduce again.
It is from our monitoring system, 
![ErrorPods](https://user-images.githubusercontent.com/22001089/57531143-61bd4680-736b-11e9-9d1b-34a1fece3cb1.PNG)

**Comment by sharmasushant** [comment]
If ping works, then network connectivity/data path should be good. Do you have any firewall rules on the VM that might be blocking port 80? Any logic in the healthz app to block requests from a certain IP/port?

**Comment by zhiweiv** [comment]
It is just a simple k8s cluster built by AKS-Egnine, there should not be firewall rules and policies, and it occurs intermittently not always, so it should not be caused by firewall.
The healthz is a http handler which does nothing just return http 200.

I plan to rebuild my cluster with a previous version of Windows, deploy a sample asp.net pod.  I joined AKS Windows private preview, I will also monitor the AKS Windows to see if there is same issue in it.

Will update here once I get something new.

**Comment by zhiweiv** [comment]
@sharmasushant 
Here is my latest information.
I deployed a pod with readness probe like this.
```
containers:
      - image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        name: networktest
        readinessProbe:
          httpGet:
            path: /
            port: 80
      nodeSelector:
        kubernetes.io/os: windows
```
In uncertain time, it becomes unready because of readiness probe timeout. At the same time, all pods on this node become unready for same reason. When issue occurs, I can ping the pod ip successfully on the node where pod is in, but curl http://podip will timeout, however I can curl http://podip successfully on other nodes. This issue occurs intermittently on random node.

I can reproduce this on the AKS Windows preview also, from my latest test, I built a one node Windows pool with only one pod on it, I can still reproduce this.
Here is the result from `kubectl describe pod` 
```
Events:
  Type     Reason     Age                 From                    Message
  ----     ------     ----                ----                    -------
  Warning  Unhealthy  36m (x25 over 38m)  kubelet, akswin1000000  Readiness probe failed: Get http://10.10.0.56:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by zhiweiv** [comment]
When issue occured, I tried to run netsh trace on the node from https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/startpacketcapture.cmd, the connection to the node lost immediately, it didn't response ping also, I have to restart it.

When it is in normal state, netsh trace runs without problem.

**Comment by MikkelHegn** [comment]
Hi, we have identified an issue with readiness probes exhausting ports in Windows. If you disable the readinessProbes, will this go away?

**Comment by zhiweiv** [comment]
@MikkelHegn 
The issue is mainly about probe timeout, if I disable the probe, I think I am unable to identity if there is problem or not.

FYI, from my latest testing, when issue occurred the Internet connection lost also on that node, for example unable to curl http://www.google.com due to timeout.

Will there be a Windows hotfix? Or there will be fix on k8s/cni? I am glad to test it if there is one.

**Comment by MikkelHegn** [comment]
Thanks - please see this issue as well: https://github.com/Azure/AKS/issues/1014

Let me get info to you about how to validate and when we can fix. For now best option is to disable the readiness probes and see if that stabilizes things.

**Comment by zhiweiv** [comment]
OK, I will disable readiness probes temporarily and waiting you fix.

**Comment by zhiweiv** [comment]
@MikkelHegn  
Any updates?

**Comment by MikkelHegn** [comment]
There's a fix for Windows scheduled to be released as part of an upcoming Windows update. We do have a private fix you can try out to help validate this will resolve the issue. Please reach out mikhegn@microsoft.com.

**Comment by zhiweiv** [comment]
The private fix works, I will leave this open until the fix is available offically.

**Comment by zhiweiv** [comment]
@MikkelHegn 
Do you know if the hotfix is released or not?

**Comment by MikkelHegn** [comment]
Not released yet. I'll let you know here when it's out.

**Comment by MikkelHegn** [comment]
It's scheduled for September Windows update release.

**Comment by zhiweiv** [comment]
OK, thanks.
