### ISSUE TITLE
is CNM plugin supported for Docker engine on Azure Linux VMs ?

### ISSUE THREAD

**Issue by guddutopper** [Azure/azure-container-networking#362]
**Is this a request for help?**:
YES
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**Which release version?**:
1.0.22
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNM
---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux AZLXSPTFBTDEVAP04 4.15.0-1041-azure #45-Ubuntu SMP Fri Mar 15 14:41:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker version 18.09.2, build 6247962
---

**What happened**:
I am trying to assign IP Address to docker container from an azure vnet and connect them from a network created using the 'azure-vnet' driver.
Now to achieve this, I have followed your github [link](https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md)
I am getting stuck after creating the network part, when I run the command to create the container, I get the following error 

`Error Log : docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2019-05-09T07:36:42Z\\\\\\\" level=fatal msg=\\\\\\\"failed to set gateway while updating gateway: route for the gateway 10.10.3.1 could not be found: network is unreachable\\\\\\\"\\\\n\\\"\"": unknown`

I have a very basic question, is the CNM plugin supported for linux machines ? Because Many people are able to assign IPs and connect container to network but on a azure windows server machine so I want a clear clarification on this ?

Also to achieve the IP assignment to docker container, which plugin CNM or CNI should be used ?
---

**What you expected to happen**:
To get a clear answer of my question.
---

**How to reproduce it** (as minimally and precisely as possible):
already mentioned in [issue](https://github.com/Azure/azure-container-networking/issues/280) 
---

**Anything else we need to know**:

---

**Comment by guddutopper** [comment]
Plugin version 1.0.8 is working for me so closing this issue.

**Comment by ashraf345** [comment]
Yes CNM plugin does work .
Please follow the below link to see how to do it.

https://netcrosstech.com/index.php/how-to-connect-docker-container-to-azure-vnet-using-cnm-plugin/
