### ISSUE TITLE
Is it possible to create 'azure-vnet' network for secondary Network Interface on an azure VM ?

### ISSUE THREAD

**Issue by guddutopper** [Azure/azure-container-networking#370]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**Which release version?**:
1.0.8
---

**Which component (CNI/IPAM/CNM/CNS)**:
CNM
---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**
Linux AZLXSPTFBTDEVAP04 4.15.0-1041-azure #45-Ubuntu SMP Tue Jun 25 14:41:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Docker version 18.09.2, build 6247962
---

**What happened**:
Using this [article](https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md), I am assigning IPs to my docker containers from azure-vnet. Earlier I was having a single network interface for my azure VM, so after adding IP configuration to that Interface I was getting those IPs for my docker containers, Now I added another network interface to my existing VM and now when I go to create a network of type '`azure-vnet'`, I get an error saying 'Invalid CIDR Address' and sometimes I get 'Subnet not found', What could be the reason for it?
---

**What you expected to happen**:
I should be able to create 'azure-vnet' type network for the subnet used in my secondary Network interface.
---

**How to reproduce it** (as minimally and precisely as possible):
Create an azure vm with a single NIC, using the CNM plugin create a 'azure-vnet' type network and assign IPs to your docker container from that subnet, now add another NIC to your vm and then try to do the same step and you will face error while creating the 'azure-vnet' network
---

**Anything else we need to know**:

---

**Comment by tamilmani1989** [comment]
right now we don't support this scenario

**Comment by guddutopper** [comment]
Thanks for the answer, however you should update the release docs where it is mentioned that you can join a container to multiple virtual networks
[V1.0.8](https://github.com/Azure/azure-container-networking/releases/tag/v1.0.8)

**Comment by tamilmani1989** [comment]
@guddutopper  that support is only for internal customers. sorry for the confusion.
