### ISSUE TITLE
Cluster based on Azure CNI,  POD in error state when start the node, indicate error "docker_sandbox.go:375] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook".

### ISSUE THREAD

**Issue by tiffanyguo721** [Azure/azure-container-networking#372]
Cluster based on Azure CNI, we found POD in error state when start the node, usually stop and start the node, POD statu can back to normal, is it an issue with Azure CNI or Kubernets?

Version:
Azure CNI: v1.0.17
Kubernetes:1.12.7
AKS engine:v0.33.4

node is started at Jul 09 03:49 (UTC), when started many pods are in error state, download the kubernete log and CNI log as below, when stop and start the node, POD status back to normal, this issue can repro whenever the node is started, we found there're similar issues with different CNI other than Azure CNI, but also indicate " failed to read pod IP from plugin/docker", please help investigate, thanks

<img width="639" alt="pod status" src="https://user-images.githubusercontent.com/35485219/60878510-70907e80-a272-11e9-86ed-7b6943ec91c7.png">

[kubenetes error log.txt](https://github.com/Azure/azure-container-networking/files/3372397/kubenetes.error.log.txt)

[Azure CNI log.txt](https://github.com/Azure/azure-container-networking/files/3372400/Azure.CNI.log.txt)

**Comment by tamilmani1989** [comment]
@tiffanyguo721  It looks like you attached azure-vnet-ipam.log. Can you also attach azure-vnet.log?

**Comment by tiffanyguo721** [comment]
@tamilmani1989 Please kindly check the azure-vnet.log, node is started at Jul 09 03:49 (UTC),
 
[azure-vnet.log.txt](https://github.com/Azure/azure-container-networking/files/3395795/azure-vnet.log.txt)

Thanks

**Comment by tamilmani1989** [comment]
@tiffanyguo721   remove if azure-vnet.json.lock or azure-vnet-ipam.json.lock present in /var/run directory..also i recommend you to move to latest cni

**Comment by tiffanyguo721** [comment]
@tamilmani1989 i didn't find any azure-vnet.json.lock or azure-vnet-ipam.json.lock under /var/run directory, what might the issue according to the logs? this issue happened before IP address exausted

**Comment by tiffanyguo721** [comment]
@tamilmani1989 I did some research , according to your comment, suspect it is "timed out locking store" issue, this issue repro today, I found the "azure-vnet.json.lock" file under /var/run directory, pod back to running after deleting this file. 
But I found a fix mentioned regarding this issue:  https://github.com/Azure/azure-container-networking/releases/tag/v1.0.17
It mean issue been fixed in v1.0.17. but my environment is based on v1.0.17, but issue still exist, do we have a permanent fix?

Meanwhile, I will move to latest cni, and then monitor if still exist

**Comment by tamilmani1989** [comment]
can you send us entire logs. /var/run-azure-vnet*.log (like log.1,log.2..etc) all logs. This happens only if CNI crashes/panic in the middle. Wanted to see what happened there.

**Comment by tiffanyguo721** [comment]
@tamilmani1989 

HI ,
Azure vnet logs attached, please help investigate, thanks

[Azure-vnet logs.zip](https://github.com/Azure/azure-container-networking/files/3451039/Azure-vnet.logs.zip)

**Comment by tamilmani1989** [comment]
@tiffanyguo721 This is fixed. We will release v1.0.25 by today.
