### ISSUE TITLE
Azure CNI with AKS to connect to OnPremise ressources

### ISSUE THREAD

**Issue by OneCyrus** [Azure/azure-container-networking#376]
this is not a bug or a feature request. I'm looking for some clarification on the implementation details of Azure CNI in AKS to connect to ressources outside the AKS cluster. I'm not use if this is the right place here but couldn't find a better place to ask the question.

the information on this page are very helpfull for the overall architecture but there are two IP ranges I'm not sure how they interact with the network routing.
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni

With Azure CNI the AKS pods get IPs form the selected VNet/subnet. This makes it easy for us to connect to OnPrem ressources through the connected VPN. But what is exactly the use case/involvement of these two ranges?

#### Kubernetes service address range
in a kubenet scenario the pods would get IPs from this range (if i'm correct?) but I guess with CNI this range is used only for internal AKS communication. So we don't need this range to be routable to the OnPrem network? and what's the minimal subnet size needed for this?

#### Docker bridge address
the same with this. don't need to be routable to OnPremise? But each Pod (container) gets assigned one (just for the network overlay?)

**Comment by tamilmani1989** [comment]
@OneCyrus Kubernetes service address range can be any ip. It can be outside of vnet space also. That works like a proxy IP (load balancer IP) and behind that pods running with actual vnet IPs. The scope of Azure CNI is to allocate only vnet IPs for pods. Service IPs are handled by Kubernetes itself.

If you want to communicate oustide the cluster(non-vnet IP), then destination IP should be either public IP or peered vnet ip.
