### ISSUE TITLE
Invalid character 'T' looking for beginning of value

### ISSUE THREAD

**Issue by yashs-dev** [Azure/azure-container-networking#380]
**Is this a request for help?**:

---
No.

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---
ISSUE

**Which release version?**:

---
v1.0.23

**Which component (CNI/IPAM/CNM/CNS)**:

---
CNI

**Which Operating System (Linux/Windows)**:

---
Windows

**For Linux: Include Distro and kernel version using "uname -a"**

---
NA

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---
10.0.17763.529 (WinBuild.160101.0800)

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---
Kubernetes
v1.15.0

**What happened**:

---
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "feaf9d486be1634b46bcbcbd6e447307eca76bbfdf922ad1f4040971dfe50618" network for pod "overprovisioning-6fdbcc68c-zrwjp": NetworkPlugin cni failed to set up pod "overprovisioning-6fdbcc68c-zrwjp_default" network: invalid character 'T' looking for beginning of value

**Anything else we need to know**:

---
Will provide full logs offline.

**Comment by ashvindeodhar** [comment]
We have added the fix and in the process of releasing 1.0.24. I'll update when that version is available.

**Comment by ashvindeodhar** [comment]
@yashs-dev can you please use the latest release - https://github.com/Azure/azure-container-networking/releases/tag/v1.0.24
