### ISSUE TITLE
Azure CNI connection issues with Azure Loadbalancer Standart

### ISSUE THREAD

**Issue by calvix** [Azure/azure-container-networking#383]
**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

---

**Which release version?**:

k8s 1.14.1

---

**Which component (CNI/IPAM/CNM/CNS)**:

Azure CNI

---

**Which Operating System (Linux/Windows)**:

Linux

---

**For Linux: Include Distro and kernel version using "uname -a"**

CoreOS 
```
Linux 6aeri-worker-00000D 4.19.23-coreos-r1 #1 SMP Mon Feb 25 23:40:01 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz GenuineIntel GNU/Linux
```

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes

---

**What happened**:
We are having issues with outgoing connectivity when using Azure Public Loadblancer with SKU Standart. We are running custom installation of kubernetes and using Azure CNI for networking  ( routes for kubernetes Pods are in `88cbw-RouteTable` resource).

The VM itself has a working outgoing connection to the internet but the pods in the kubernetes don't.  

This issue only occurs with the  LoadBalancer SKU Standart, it works perfectly with the Loadablancer SKU Basic.

My understanding is that there is a difference with the outgoing NAT for the Standart LB.  But I am not sure how ensure that the LB also consider the networks for pods to  be properly NATted when they communciate to public internet.

The outgoing rules in Loadblancer property seem to only accept BackendPool and there is now ay how to specify specific subnet or something else.

---

**What you expected to happen**:
Outgoing conenctivity with Azure CNI  from pods would work with both LBs type.

---

**How to reproduce it** (as minimally and precisely as possible):

Create Kubernetes cluster with Azure CNI and Loadblancer Type Standart, try pod connection to outside

---

**Comment by tamilmani1989** [comment]
@calvix If you haven't deployed kubernetes cluster via AKS or AKS-engine, then you have to add an iptable rule to allow internet connectivity from pod. Please check this link: [
https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#outbound-connectivity-from-pods](url)

**Comment by calvix** [comment]
@tamilmani1989 Thanks, that seems to fix the issue. Its weird that it worked without the NAT rules for Azure LB Basic.
