### ISSUE TITLE
Not found 404 while install CNI with scripts/install_cni_plugin.sh 

### ISSUE THREAD

**Issue by chowmean** [Azure/azure-container-networking#394]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**Which release version?**:

Latest

**Which component (CNI/IPAM/CNM/CNS)**:

CNI

**Which Operating System (Linux/Windows)**:

LINUX
**For Linux: Include Distro and kernel version using "uname -a"**

44-Ubuntu SMP Thu Feb 21 14:24:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Kubernetes
**What happened**:

Got 404 while installing loopback cni plugin. 

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

Run bash scripts/install_cni_plugin.sh 

**Anything else we need to know**:

Getting 404 release itself not present this need to be fixed. Not able to use the CNI. 
```wget https://github.com/containernetworking/cni/releases/download/0.4.0/cni-amd64-0.4.0.tgz
--2019-08-28 17:29:35--  https://github.com/containernetworking/cni/releases/download/0.4.0/cni-amd64-0.4.0.tgz
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found```

**Comment by chowmean** [comment]
Download address is changed to https://github.com/containernetworking/cni/archive/v0.7.1.tar.gz

**Comment by saiyan86** [comment]
#418 fixes this.
