### ISSUE TITLE
How to use network policy

### ISSUE THREAD

**Issue by anujgeek** [Azure/azure-container-networking#410]
For network policy feature, are we required to enable the network policy feature when creating the aks cluster: https://docs.microsoft.com/en-us/azure/aks/use-network-policies

I created the aks cluster using portal, and I couldn't find a way to enable network policies. I applied the plugin using: https://github.com/Azure/azure-container-networking/blob/master/docs/npm.md
```
kubectl apply -f https://raw.githubusercontent.com/Azure/azure-container-networking/master/npm/azure-npm.yaml
```
But after applying a policy, I couldn't see any effect.

**Comment by RossBarnie** [comment]
As far as I can tell you are required to have the networkPolicy and networkPlugin options set to azure, per the docs you linked to:
```
az aks create \
    ...
    --network-plugin azure \
    ...
    --network-policy azure
```
Or equivalent if using ARM templates

**Comment by saiyan86** [comment]
Hi @anujgeek , you have to explicitly declare ```--network-policy azure``` for AKS. @RossBarnie thanks for the reply!

**Comment by saiyan86** [comment]
Closing the issue as it is well documented on  https://docs.microsoft.com/en-us/azure/aks/use-network-policies
