### ISSUE TITLE
Need help on Service mesh with azure CNI

### ISSUE THREAD

**Issue by chowmean** [Azure/azure-container-networking#420]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**Which release version?**:
Latest
---

**Which component (CNI/IPAM/CNM/CNS)**:
All
---

**Which Operating System (Linux/Windows)**:
Linux
---

**For Linux: Include Distro and kernel version using "uname -a"**
inux jumpVM 4.15.0-1037-azure #39~16.04.1-Ubuntu SMP Tue Jan 15 17:20:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

Are there any documentation for using service mess with azure CNI. Need help with this. 

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kuberenetes
---

**What happened**:
Need help. 
---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by saiyan86** [comment]
@chowmean Can you please provide us with more information? We don't know the ask here.

**Comment by chowmean** [comment]
@saiyan86 I want to know is if there is some documentation to use the azure CNI with service mesh like istio or envoy. I want to know what could be the limitations and steps.

**Comment by saiyan86** [comment]
@matmerr

**Comment by aanandr** [comment]
@chowmean  - what kind of help do you need? If you deploy a Kubernetes cluster with Azure CNI and follow the steps to install and run Istio or LinkerD. It should work.
