### ISSUE TITLE
How to build this

### ISSUE THREAD

**Issue by ashutoshishere04** [Azure/azure-container-networking#433]
**Is this a request for help?**:

--- help

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- issue

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

--- cni

**Which Operating System (Linux/Windows)**:

--- linux

**For Linux: Include Distro and kernel version using "uname -a"**

--- Linux azurebaseimage 4.15.0-1059-azure #64-Ubuntu SMP Fri Sep 13 17:02:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

--- 1.12.8

**What happened**:

--- make all-binaries fails

**What you expected to happen**:

--- make all-binaries success

**How to reproduce it** (as minimally and precisely as possible):

---$ git clone https://github.com/Azure/azure-container-networking.git
$cd azure-container-networking
$make all-binaries
go build -v -o output/linux_amd64/cnm/azure-vnet-plugin -ldflags "-X main.version=v1.0.29-RC1-3-g19720a1 -s -w" cnm/plugin/*.go
chmod 0755 output/linux_amd64/cnm/azure-vnet-plugin
cd output/linux_amd64/cnm && tar -czvf azure-vnet-cnm-linux-amd64-v1.0.29-RC1-3-g19720a1.tgz azure-vnet-plugin
azure-vnet-plugin
chown 0:0 output/linux_amd64/cnm/azure-vnet-cnm-linux-amd64-v1.0.29-RC1-3-g19720a1.tgz
go build -v -o output/linux_amd64/cni/azure-vnet -ldflags "-X main.version=v1.0.29-RC1-3-g19720a1 -s -w" cni/network/plugin/*.go
command-line-arguments
# command-line-arguments
cni/network/plugin/main.go:218:45: cannot use netPlugin.Update (type func(*"github.com/Azure/azure-container-networking/vendor/github.com/containernetworking/cni/pkg/skel".CmdArgs) error) as type func(*"github.com/containernetworking/cni/pkg/skel".CmdArgs) error in argument to handleIfCniUpdate
Makefile:159: recipe for target 'output/linux_amd64/cni/azure-vnet' failed
make: *** [output/linux_amd64/cni/azure-vnet] Error 2

**Anything else we need to know**:

---

**Comment by matmerr** [comment]
Closing due to stale, if problem persists, please reopen.

**Comment by hongfeioo** [comment]
any update?

**Comment by hongfeioo** [comment]
export CGO_ENABLED=0; export GOOS=linux    

fix it
