### ISSUE TITLE
[NPM] Handle telemetry connection failures 

### ISSUE THREAD

**Issue by tamilmani1989** [Azure/azure-container-networking#434]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Handle telemetry connection failures. If there is orphaned sock file, npm should clear that up and recreate it
---

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

---

**Which Operating System (Linux/Windows)**:

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---

**What happened**:

---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by jaer-tsun** [comment]
fixed in v1.0.29
