### ISSUE TITLE
no azure-npm logs after deployed in a k8s cluster

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-container-networking#438]
**Is this a request for help?**:

No matter azure-npm is running or failing, there are no logs

```
$ kubectl logs azure-npm-z5v69 -c azure-npm -n kube-system

azure-npm:
    Container ID:   docker://0c589086820837cc4887699984c73c9611bf6af89bebfe33148ab4eb8105a8a7
    Image:          mcr.microsoft.com/containernetworking/azure-npm:v1.0.28
    Image ID:       docker-pullable://mcr.microsoft.com/containernetworking/azure-npm@sha256:c81d70c81eadeb811e66c69d68b2d16195c59c6797c7b5647ec88270e25201e8
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 14 Nov 2019 05:56:53 +0000
      Finished:     Thu, 14 Nov 2019 05:56:53 +0000
    Ready:          False
    Restart Count:  6
    Environment:
      HOSTNAME:   (v1:spec.nodeName)
    Mounts:
      /run/xtables.lock from xtables-lock (rw)
      /tmp from tmp (rw)
      /var/log from log (rw)
      /var/run from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from azure-npm-token-xvgfh (ro)
```

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

---

**Which Operating System (Linux/Windows)**:

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---

**What happened**:

---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by jaer-tsun** [comment]
the logs should exist on the agent nodes under /var/log/azure-npm.log*

**Comment by jaer-tsun** [comment]
NPM will write to stdout after this merges https://github.com/Azure/azure-container-networking/pull/449
