### ISSUE TITLE
azure-npm does not support k8s alpha or beta version

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-container-networking#439]
**Is this a request for help?**:
When we deploy azure npm in a k8s alpha or beta version cluster, azure-npm is always in failing state, k8s version parsing is failing, and there are even on logs showing why it's failing:
https://github.com/Azure/azure-container-networking/blob/36f188cfc9d9947f58a8399b50ec07b471b8f170/npm/util/util.go#L97-L161

failing k8s version could be like this: `1.17.0-beta.1`

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

---

**Which Operating System (Linux/Windows)**:

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---

**What happened**:

---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by jaer-tsun** [comment]
https://github.com/Azure/azure-container-networking/pull/437 addresses this issue and the fix is a part of release v1.0.29
