### ISSUE TITLE
[CNM] Internet not being accessible from containers

### ISSUE THREAD

**Issue by tomleetaiwan** [Azure/azure-container-networking#477]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): 

[Reference issues #79](https://github.com/Azure/azure-container-networking/issues/79), I think it  is a feature request

---

**Which release version?**: 

v1.0.31

---

**Which component (CNI/IPAM/CNM/CNS)**: 

CNM

---

**Which Operating System (Linux/Windows)**: 

Linux

---

**For Linux: Include Distro and kernel version using "uname -a"** : 

5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

---
I want to determine does Azure CNM (libnetwork) support Internet access from a container? If it does not support there is any plan to support it in the future ?

**Which Orchestrator and version (e.g. Kubernetes, Docker)**:

Docker version : 18.09.9

---

**What happened**:

Unable to access Internet from container.

---

**What you expected to happen**:

Able to access Internet from container.

---

**How to reproduce it** (as minimally and precisely as possible):

Follow the [instruction](https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md) can reproduce.

---

**Anything else we need to know**:

N/A

---

**Comment by tamilmani1989** [comment]
Currently Azure CNM cannot support this as it doesn't have knowledge on vnet space of customer. Run the following cmd to allow internet connectivity from containers. We certainly think in future if we can get vnet space from user config.

https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md#outbound-connectivity-from-container

**Comment by tomleetaiwan** [comment]
Thanks for your explain.
