### ISSUE TITLE
Incorrect ARP responses running in AKS

### ISSUE THREAD

**Issue by plwhite** [Azure/azure-container-networking#486]
**ISSUE**

ARP responses sent by the Azure networking have incorrect destination field.

**Which release version?**:

This is AKS, running clusters of version 1.14.8.

**Which component (CNI/IPAM/CNM/CNS)**:

CNI

**Which Operating System (Linux/Windows)**:

Linux

**For Linux: Include Distro and kernel version using "uname -a"**

N/A - this is an AKS issue, and I do not have access to the node.

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

Kubernetes

**What happened**:

Incorrect ARP responses.

- Pod A issues ARP request for IP of pod B.
- ARP response is received at pod A.

If pod B is on the same node as pod A, the ARP response is correct. It contains:

- From: IP of pod B, MAC of pod B
- To: IP of pod A, MAC of pod A.

This is correct behaviour. However, if pod B is on a different node, the ARP response is incorrect. It contains:

- From: IP of pod B, *MAC of node that pod B is running on*
- To: IP of pod A, *MAC of node that pod A is running on*

This doesn't match correct behaviour according to RFC826. I think it is OK that the MAC address for pod B is reported as a gateway MAC, but it is incorrect that the response address is sent to the wrong MAC.

As I understand it the issue is that ARP requests leaving the node are swallowed by some gateway on the node and retransmitted. When that gateway receives an ARP response it sends it on, but does not change it to insert the correct destination MAC address.

---

**What you expected to happen**:

Correct ARP responses.

---

**How to reproduce it** (as minimally and precisely as possible):

See above - spin up some pods and run ping and tcpdump on them to catch ARP traffic.

---

**Anything else we need to know**:

Many applications are not affected by this because they accept ARP data that is sent to any destinations. However, we have an application which needs to explicitly parse ARP, and which is rejecting ARP packets with the wrong MAC address.

---

**Comment by tamilmani1989** [comment]
What;s the wrong mac address you are seeing. if you see mac starting with 12:34.. then its expected

**Comment by plwhite** [comment]
The MAC address in the to field of the ARP response does start with 12:34 normally, yes.

When you say "expected", do you mean this is a known bug?

**Comment by plwhite** [comment]
Here's a slight clarification of what the bug is technically. ARP requests leaving the container go through SNAT, so that their source MAC is changed. When the ARP response arrives, it arrives at the node with destination MAC changed because of the SNAT, but the SNAT is not reversed when the packet is passed on to the pod.

**Comment by saiyan86** [comment]
@plwhite Please refer to https://github.com/Azure/azure-container-networking/issues/144

**Comment by plwhite** [comment]
As I read #144, the final comment appears to confirm the bug, but then that issue was closed. Is that correct? The value of the MAC address isn't the problem, but the fact that it doesn't satisfy RFC826.

**Comment by tamilmani1989** [comment]
@plwhite this is not bug. This is how azure platform works
