### ISSUE TITLE
How to monitor NPM health?

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-container-networking#502]
I did see /network/health endpoint in NPM repo but NPM deployment doesn't come with any liveness probe. 
Can you please let me know what is the recommended way to monitor NPM health?

**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---

**Which release version?**:

---

**Which component (CNI/IPAM/CNM/CNS)**:

---

**Which Operating System (Linux/Windows)**:

---

**For Linux: Include Distro and kernel version using "uname -a"**

---

**For windows: provide output of "$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion"**

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**

---

**What happened**:

---

**What you expected to happen**:

---

**How to reproduce it** (as minimally and precisely as possible):

---

**Anything else we need to know**:

---

**Comment by tamilmani1989** [comment]
In recent version of NPM, we added a metric which will send info periodically. That can be used to check if npm is alive or not. @matmerr  @jaer-tsun

**Comment by yamaszone** [comment]
> In recent version of NPM, we added a metric which will send info periodically. That can be used to check if npm is alive or not. @matmerr @jaer-tsun

@tamilmani1989 Thanks for your note! Can you please send pointers to some docs for above? Also, would it be possible to update [NPM deployment](https://github.com/Azure/azure-container-networking/blob/master/npm/azure-npm.yaml) with liveness for AKS customers, please?

**Comment by tamilmani1989** [comment]
@matmerr / @jaer-tsun can you help @yamaszone

**Comment by matmerr** [comment]
@huntergregory is currently adding Prometheus metrics to NPM. Once that is merged we will post an update. https://github.com/Azure/azure-container-networking/pull/590
