### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dspillmann2016** [Azure/azure-container-networking#53]
make all-binaries
go build -v -o output/linux_amd64/azure-cnm-plugin -ldflags "-X main.version=v0.7-2-gf768da9-dirty -s -w" cnm/plugin/*.go
github.com/Azure/azure-container-networking/log
github.com/Azure/azure-container-networking/store
github.com/Azure/azure-container-networking/platform
# github.com/Azure/azure-container-networking/log
log/logger.go:44: logger.SetTarget undefined (type Logger has no field or method SetTarget)
log/stdapi.go:19: stdLog.SetTarget undefined (type *Logger has no field or method SetTarget)
make: *** [output/linux_amd64/azure-cnm-plugin] Error 2

**Comment by ofiliz** [comment]
@dspillmann2016 I tried to reproduce this error. Confirmed that the repo builds fine on multiple clean build machines. I see that you have made changes to the repo (the build version above is "dirty") before the build. Could it be that something you changes caused this error? Can you please checkout tag v0.7 and build clean?

**Comment by dspillmann2016** [comment]
hi
build env is mac-osx there it fails all the time - it compiles fine on Ubuntu16.4
rm -fr azure-container-networking/
git clone  https://github.com/Azure/azure-container-networking.git
cd azure-container-networking/
make all-binaries
go build -v -o output/linux_amd64/azure-cnm-plugin -ldflags "-X main.version=v0.7-2-gf768da9 -s -w" cnm/plugin/*.go
github.com/Azure/azure-container-networking/log
github.com/Azure/azure-container-networking/store
github.com/Azure/azure-container-networking/platform
# github.com/Azure/azure-container-networking/log
log/logger.go:45: logger.SetTarget undefined (type Logger has no field or method SetTarget)
log/stdapi.go:19: stdLog.SetTarget undefined (type *Logger has no field or method SetTarget)
make: *** [output/linux_amd64/azure-cnm-plugin] Error 2

**Comment by ofiliz** [comment]
osx is not a supported build target OS. But you should be able to use osx as a build environment to build for a target OS (Linux or Windows) by setting the GOOS env variable. Can you please do this?

GOOS=linux make all-binaries

**Comment by dspillmann2016** [comment]
that worked fine.
Thanks
