### ISSUE TITLE
ClusterIPs should also be assigned by Azure SDN

### ISSUE THREAD

**Issue by evillgenius75** [Azure/azure-container-networking#55]
Only POD IP space is assigned by the AzureSDN, but there should also be a mechanism to assign the Service CIDR space from the Azure SDN as well. This allows flexibility to place Load Balancers within Azure SDN, within K8s from internal to Azure only communication or to external services via the LoadBalancer type.

**Comment by ofiliz** [comment]
Thanks for bringing this up. We need to discuss these use cases with ACS team and understand the requirements better. However, it seems to me that any solutions will need to be in [acs-engine](https://github.com/Azure/acs-engine). This repo is for Azure CNI plugins. Can you please move this issue to [acs-engine](https://github.com/Azure/acs-engine) repo and add me there?

Also, please see this PR. You can now customize the Kubernetes service subnet directly in acs-engine.
https://github.com/Azure/acs-engine/pull/473

**Comment by ashb** [comment]
A thing to node about Kubernetes Service IP ranges: They are not actually routed outside of the nodes but are handled by a DNAT rule (at least when kube-proxy is in the default iptables mode). I'm not sure if this behaves differently with CNI-based network plugins?

**Comment by ofiliz** [comment]
Right. That doesn't really have anything to do with CNI plugins. All that the azure-vnet CNI plugin does is to enable IP connectivity in VNET and update the L2 headers so that DNAT'ed frames are switched properly. The Kubernetes service subnet is a logical abstraction implemented by kube-proxy.
