### ISSUE TITLE
[CNI] In AKS make azure-cni pod run with dedicated ServiceAccount instead of default ServiceAccount

### ISSUE THREAD

**Issue by khbafl** [Azure/azure-container-networking#595]
**Component (Azure NPM or Azure CNI):** Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  azure-cni pods run with dedicated ServiceAccount

**Orchestrator(e.g. Kubernetes, Docker):**  Kubernetes

**Operating System (Linux/Windows):**  Linux

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

The azure-cni pods, along with the azure-ip-masq pods, are deployed automatically by Azure when we use the "azure" network policy when creating an AKS cluster. Currently these pods are deployed with the "default" ServiceAccount instead of a dedicated one like it's the case for azure-npm for example, and there seems to be no parameter to set a custom ServiceAccount. 

Is there a justification for using the default SA for azure-cni and azure-ip-masq? If not can you natively deploy it with a dedicated SA please? Meanwhile, how can we set a custom one since these pods are deployed by Azure without available customisation parameters ?  

The reason why I am asking this is because using the "default" SA is against kubernetes security best practices.

Thank you,

**Comment by tamilmani1989** [comment]
@khbafl azure-cni doesn't run in any pod. It runs as a process in vm namespace. Regarding, azure-ip-masq, AKS manages it, can you please open this in aks github https://github.com/Azure/aks
