### ISSUE TITLE
Support Azure CNI with Kured reboot

### ISSUE THREAD

**Issue by tamilmani1989** [Azure/azure-container-networking#639]
**Component (Azure NPM or Azure CNI):**

Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  
With kured reboot, we witnessed files under /var/run persist and cni trying to rehydrate state. We need to detect kured reboot and handle effectively in CNI

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes

**Operating System (Linux/Windows):**  
Linux

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

**Comment by a-rt-works** [comment]
Other semi related issues with Kured on AKS

https://github.com/Azure/AKS/issues/1320

**Comment by palma21** [comment]
Why do you need to treat a kured reboot differently than a regular soft VM reboot? It should just be a basic `systemctl reboot`. Does that issue not happen if you manually do that on the vm?

**Comment by palma21** [comment]
cc @aanandr

**Comment by tamilmani1989** [comment]
We have seen this only with kured setup so far. We saw node wasn't rebooted but reboot time got updated somehow. We couldn't repro this on our own. It would be good if you could provide us repro steps or repro setup so that we can investigate

**Comment by palma21** [comment]
If node wasn't rebooted, then that's a bug in either kured or customer config. Do you have those logs somewhere? we can follow up offline

**Comment by tamilmani1989** [comment]
@palma21  on further investigation, found that `uptime -s` was returning erratic values even if vm  hasn't rebooted. Not sure if this happening in newer azure linux kernel. Nevertheless we don't need this code path to be invoked for cni. If cni, we skip getting reboot time and do any action based on that. That would fix this issue.

**Comment by pranaypathik** [comment]
Hello
I was wondering on the status of this issue.

Pranay
