### ISSUE TITLE
Azure CNI performance

### ISSUE THREAD

**Issue by ouissem** [Azure/azure-container-networking#645]
Hi,

Is there any benchmark on Azure CNI performance compared to Kubelet ?
I keep hearing that Azure CNI has better performance for inter-agent node communication while Kubelet forward frames faster between pods hosted on the same node but if they both leverage Linux bridges, is the difference in performance intra-node that significant ?
Is is all due to the SDN layer that comes into play ?
If no benchmark available, your insight would be much appreciated to answer this, the more details you can provide the better it is.

Thanks,

**Comment by paulgmiller** [comment]
@matt-stam is actually looking at azure cni vs kube**net**. We're looking at ping latencies and iperf measurements. And might publish something. We also have theories but think it might be time to get repeatable data.
