### ISSUE TITLE
IPv6 source IP address is not preserved for LoadBalancer services

### ISSUE THREAD

**Issue by feiskyer** [Azure/azure-container-networking#655]
**What happened:** 

IPv6 source IP address is not preserved for LoadBalancer services. This is because a default POSTROUTING SNAT rule has been added on each node.

**What you expected to happen:**  

IPv6 source IP address should be preserved for LoadBalancer services.

**How to reproduce it:**  

Provision a dualstack aks-engine cluster, create an IPv6 service, then access the service and get the source IP. The source IP is node's IPv6 address instead of real client IP.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

1.19.x.

**Operating System (Linux/Windows):**  

Linux.

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by TonyDou** [comment]
I saw the same issue. The IPv6 source IP couldn't be preserved for LoadBalancer service with externalTrafficPolicy: Local.
