### ISSUE TITLE
Logs are not in documented path for Windows with Containerd

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-container-networking#698]
**What happened:** 
Create an aks-engine cluster with containerd, schedule a pod and look for azure cni logs.  The are not in [documented](https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#logs) location but in `c:\Windows\system32\`

Example https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-19-windows-containerd/1318630275701280768/artifacts/6211k8s000/

**What you expected to happen:**  
Logs to be in c:\k\azure-vnet.log (https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md#logs)

**How to reproduce it:**  
Create windows cluster with containerd.  Example cluster config: https://github.com/kubernetes-sigs/windows-testing/blob/master/job-templates/kubernetes_containerd_1_19.json

On the Containerd machine:
```
PS C:\> Get-ChildItem -Path . -Filter '*azure-vnet*' -Recurse | %{$_.FullName}
C:\k\azurecni\bin\azure-vnet-ipam.exe
C:\k\azurecni\bin\azure-vnet-ipamv6.exe
C:\k\azurecni\bin\azure-vnet-telemetry.config
C:\k\azurecni\bin\azure-vnet-telemetry.exe
C:\k\azurecni\bin\azure-vnet.exe
C:\Windows\System32\azure-vnet-ipam.json
C:\Windows\System32\azure-vnet-ipam.log
C:\Windows\System32\azure-vnet-telemetry.log
C:\Windows\System32\azure-vnet.json
C:\Windows\System32\azure-vnet.log
```

**Orchestrator and Version (e.g. Kubernetes, Docker):**  

**Operating System (Linux/Windows):**  

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]
Looks like the working directory for the executable is not set and the log path is https://github.com/Azure/azure-container-networking/blob/147c4388c80f643fff3138c35a913aba26dc1850/log/logger_windows.go#L14

**Comment by thatmattlong** [comment]
Spoke with @jsturtevant offline - it seems that in the Docker scenario, kubelet invokes CNI, and kubelet's working directory is `C:\k`. In the containerd scenario, containerd invokes the CNI, and its working directory is `C:\Windows\System32`. 

The current behavior of the CNI is to log to the current working directory (on Windows), so @jsturtevant is going to try setting the current working directory of containerd to `C:\k` and see if there are any side-effects.

**Comment by jsturtevant** [comment]
Did a bit more digging and found that:

- In the docker flow, the CNI is invoked by kubelet which has it's working directory in c:\k via nssm's APP Directory command in aks-engine
- In the containerd flow, the CNI is invoked by containerd which is installed via service manager (--register-service flag containerd provides). Services default work directories are C:\system32 which is why the logs are set there.  

As far as I know there isn't a way to set working directory of a service except via the code after the process starts up

**Comment by marosset** [comment]
> As far as I know there isn't a way to set working directory of a service except via the code after the process starts up

In windows 10 you can set it via the AppDirectory service parameter (which is just a reg key)
https://stackoverflow.com/questions/54456689/change-start-in-path-of-windows-service

I'm wondering if we want the logs to show up in the containerd directory or the CNI bin directory (which it sounds like would happen if containerd set a work directory when calling CNI binaries)

**Comment by jsturtevant** [comment]
generic issue for containerd: https://github.com/containerd/containerd/issues/4928
