### ISSUE TITLE
Azure CNI should support seperate pod subnet/cidr

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-container-networking#707]
**Component (Azure NPM or Azure CNI):**

Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  

Right now azure cni always shares one subnet/cidr for nodes and pods. This has some downsides. Customers can't use nsg's to treat nodes/pods differently. Allocation is complicated and sometimes kubernetes wants a pure pod cidr like in this issue:

https://github.com/kubernetes/kubernetes/issues/95555

Been working with @neaggarwMS on this and we hope to have more details soon. 

**Orchestrator(e.g. Kubernetes, Docker):**  
Kubernetes.

**Operating System (Linux/Windows):**  
Both

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]

**Comment by denniszielke** [comment]
Love it! We are hoping this will make it easier to deal with customer networks in which routable ip spaces is scarce.
Two questions:
1.) Will this also remove the need for allocating pod ips in batches of maxpods? It would be great if pod ips would be allocated when requested for pods and not allocated by the number of deployed nodes.
2.) Will it be possible to deploy pods in routable subnet ip space and host in routable subnet? In that sense the pods need to use the host for egress to the azure vnet.

**Comment by paulgmiller** [comment]
1) Yes  ips will be allocated in much smaller batch sizes (~16) and we'll also change the default max pods to something higher if you bring a pod subnet. 

2) Not sure I completely understand the question but pods and hosts will both be full members of the azure vnet

**Comment by denniszielke** [comment]
sorry I forgot the important "non" word. The key idea is that hosts are deployed in routable ip space and pods in non routeable ip space of the same vnet. We will have different ip ranges in the vnet and separate them by subnet.
would it also be possible to deploy hosts and pods in different vnet? (reason being that you cannot change vnet Adress ranges while the vnet is peered). It would be more practical if we could separate them by vnet and not only subnets.

**Comment by paulgmiller** [comment]
I the first iteration subnets have to be in the same vnet but we're looking at removing that restriction in the futther future.

**Comment by denniszielke** [comment]
@paulgmiller : do you have some guidance on how to configure the new cni with AKS-Engine? We would very much like to validate this scenario (since we need to make a decision on network design this year).

**Comment by paulgmiller** [comment]
It won't be available in aks-engine/cluster api until after and because it
needs to run a component in your control plane with access internals for
now.

**Comment by stgrace** [comment]
Is there any update on this?

**Comment by chrisjohnson** [comment]
Not sure how to remove the stale label but this should definitely see some attention, it's a pretty big deal from my org's perspective

**Comment by rbtr** [comment]
commenting is sufficient, but i've also removed the label

**Comment by rbtr** [comment]
@chrisjohnson this has been available in preview for some time, and we are approaching GA of the feature.
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview

**Comment by chrisjohnson** [comment]
> @chrisjohnson this has been available in preview for some time, and we are approaching GA of the feature. https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview

@rbtr

I tried to enable this feature (I found the example in the terraform provider) and it got stuck in pending state. I opened a ticket and was told I should not be using this feature as it's internal-only and can break my environment. The email exchange had this tracking ID (not sure if that helps you) TrackingID#2201180040005377 and I spoke with Xai Thao <v-xaithao@microsoftsupport.com>

Can you help clarify?

**Comment by chrisjohnson** [comment]
This hasn't been resolved

**Comment by paulgmiller** [comment]
@chrisjohnson  I tried to dig up 2201180040005377 but was not allowed to access it because it was too old :( 
Can you create a new tickets and ask support to reach out to paul miller or patrick healy on aks?

**Comment by dthorsen** [comment]
@paulgmiller  Would you be open to a pull request contributing this functionality for Azure CNI and self-managed clusters? I have a prototype working that I'd be happy to clean up and contribute.

**Comment by rbtr** [comment]
this feature is GA: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support

**Comment by rbtr** [comment]
@dthorsen can you open a separate tracking issue and explain your use case/intent and design? I am not sure that the DIY cluster scenario is something we can support right now, but I would love to see how you have approached it.
Feel free to open a PR also, even if only for the benefit of others who might be interested in this.
