### ISSUE TITLE
Move Azure CNI state files to different location in filesystem

### ISSUE THREAD

**Issue by thatmattlong** [Azure/azure-container-networking#708]
**Component (Azure NPM or Azure CNI):**
Azure CNI

**Describe in detail the feature/behavior/change you'd like to see:**  
Currently, Azure CNI writes its state files to `/var/run`, which is a symlink to `/run`, which is part of the VM's `tmpfs`, a volatile, in-memory filesystem. This filesystem cannot be read from ASC because it is not part of the IaaS disk, so we rely on the customer to collect these files during incident investigation. If the files were moved to somewhere on the IaaS disk, such as `/etc/azure-cni`, we could use ASC to collect the files without customer intervention.

**Orchestrator(e.g. Kubernetes, Docker):**  
All

**Operating System (Linux/Windows):**  
Linux

**Anything else you would like to add:**  
[Miscellaneous information that will assist in solving the issue.]
I'm not 100% sure of the implications of using /var/run. I think it would not persist across reboots. If this is the case, we will need to detect a reboot and cycle the state file in the CNI since the IaaS disk contents persist across reboots. This needs further investigation.

Also note that the intended behavior of ASC Inspect IaaS Disk is to pull these files, but it cannot read them because it only has access to the IaaS disk. So, the current implementation of the IaaS report is broken.

**Comment by MikeZappa87** [comment]
Would making this dir configurable via the cni spec be useful?
