### ISSUE TITLE
Additional configuration option: REJECT instead of DROP

### ISSUE THREAD

**Issue by hp598** [Azure/azure-container-networking#723]
Hi, 

We are using azure-npm in an AKS cluster. We had several issues until now, where someone created a networkpolicy that also targeted a pod using hostip. 

As azure-npm cannot differ between a pod and the actual node in this case, an iptables-rule was created that impacted the outgoing/incoming traffic of the node itself.

In AKS, this also causes kubectl logs / port-forward / exec -it commands to run into timeouts. 

Allowing to reject traffic instead of dropping it, would help debugging or recognizing this error sooner (It might also help to add a configuration option, which simply would not include the node ip in ipsets).

**Comment by vakalapa** [comment]
v1.3.2 latest NPM release is stable and ignores hostnetwork traffic, solving this particular issue. Suggestion about REJECT is being reviewed internally.
