### ISSUE TITLE
Possible error with CNI Type error reporting

### ISSUE THREAD

**Issue by tmjd** [Azure/azure-container-networking#747]
**What happened:** 
I was looking at Transparent/Bridge cni mode and noticed that the Transparent and Bridge mode were being used when reporting an error for CNIType/Tenancy setting check. See https://github.com/Azure/azure-container-networking/blob/master/acncli/installer/install.go#L47

**What you expected to happen:**  
I would think that the error should be reporting Multitenancy/Singletenancy instead.

**How to reproduce it:**  
Look at the link I included above.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
My eye balls.

**Operating System (Linux/Windows):**  
I'm running Linux :grinning: 

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by rbtr** [comment]
closed by #748
