### ISSUE TITLE
Failed to start container: FailedSync

### ISSUE THREAD

**Issue by zackliu** [Azure/azure-container-networking#75]
I create ACS by json below:

> {
>   "apiVersion": "vlabs",
>   "properties": {
>     "orchestratorProfile": {
>       "orchestratorType": "Kubernetes",
>       "kubernetesConfig": {
>         "networkPolicy": "azure"
>       }
>     },
>     "masterProfile": {
>       "count": 1,
>       "dnsPrefix": "kubernetescni",
>       "vmSize": "Standard_D2_v2"
>     },
>     "agentPoolProfiles": [
>       {
>         "name": "agentpool",
>         "count": 2,
>         "vmSize": "Standard_D2_v2",
>         "availabilityProfile": "AvailabilitySet"
>       }
>     ],
>     "linuxProfile": {
>       "adminUsername": "chenyl",
>       "ssh": {
>         "publicKeys": [
>           {
>             "keyData": "xxxxxxxxxxx"
>           }
>         ]
>       }
>     },
>     "servicePrincipalProfile": {
>       "servicePrincipalClientID": "xxxxxxxxxxx",
>       "servicePrincipalClientSecret": "xxxxxxxxxxx"
>     }
>   }
> }

Then I run the command `kubectl run nginx --image nginx`
However the container start error:

> Events:
>   FirstSeen     LastSeen        Count   From                                    SubObjectPath   Type            Reason          Message
>   ---------     --------        -----   ----                                    -------------   --------        ------          -------
>   1m            1m              1       default-scheduler                                       Normal          Scheduled       Successfully assigned nginx-2371676037-2qbpj to k8s-agentpool-40914460-0
>   53s           53s             1       kubelet, k8s-agentpool-40914460-0                       Warning         FailedSync      Error syncing pod, skipping: failed to "KillPodSandbox" for "6cdc07e9-9c51-11e7-9b21-000d3aa09b41" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"nginx-2371676037-2qbpj_default\" network: CNI failed to retrieve network namespace path: Error: No such container: a3b7efc4338a4132d832cc122936380bc7e0c67b6a8eba46dce5029115f76141"
> 
>   51s   51s     1       kubelet, k8s-agentpool-40914460-0               Warning FailedSync      Error syncing pod, skipping: failed to "KillPodSandbox" for "6cdc07e9-9c51-11e7-9b21-000d3aa09b41" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"_\" network: CNI failed to retrieve network namespace path: Error: No such container: 38b690d6457f9c0bd707f79d0d8bee6f85abe596bde2f74e6a386e83e2069c1a"
> 
>   1m    1s      39      kubelet, k8s-agentpool-40914460-0               Warning FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "nginx-2371676037-2qbpj_default(6cdc07e9-9c51-11e7-9b21-000d3aa09b41)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-2371676037-2qbpj_default(6cdc07e9-9c51-11e7-9b21-000d3aa09b41)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"nginx-2371676037-2qbpj_default\" network: failed to find plugin \"loopback\" in path [/opt/loopback/bin /opt/cni/bin]"
> 
>   1m    0s      41      kubelet, k8s-agentpool-40914460-0               Normal  SandboxChanged  Pod sandbox changed, it will be killed and re-created.

**Comment by sharmasushant** [comment]
Hi Zackliu, Can you please check if the node (k8s-agentpool-40914460-0) has loopback plugin installed at /opt/cni/bin. Please list the files in /opt/cni/bin directory for the agent node above.

**Comment by sharmasushant** [comment]
Hi Zackliu, Were you able to get the information that was asked and will help us debug this?

**Comment by zackliu** [comment]
Hi, sorry for not replying at once. There is only `azure-vnet` and `azure-vnet-ipam` in `/opt/cni/bin`. And I have another problem that seems I can't add public IP for agent node (When I tried to associate to NIC of agent node, nothing happened).

**Comment by ofiliz** [comment]
@zackliu, acs-engine had a regression a few weeks ago where they uploaded an incorrect package that did not include the loopback plugin. We fixed that as soon as we noticed it. The easiest way to fix this is to git pull your acs-engine and recreate your cluster.

**Comment by zackliu** [comment]
OK, resolved. Thanks.
