### ISSUE TITLE
azure-vnet.json.lock left with empty content

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-container-networking#762]
**What happened:** 
Sometimes azure-vnet.json.lock left with empty content, which make all following cni calls fail with error:
`2020/12/29 06:01:54 [4844] Num bytes read from lock file is 0`

Here is the logs
[k.zip](https://github.com/Azure/azure-container-networking/files/5750608/k.zip)

**How to reproduce it:**  
It happens randomly,

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
AKS 1.19

**Operating System (Linux/Windows):**  
Windows 

**Kernel:**
10.0.17763.1577

**Comment by zhiweiv** [comment]
@AbelHu @daschott 
FYI
Issue reproduced with azure cni 1.2.2

All logs here(including azure cni config)
[k.zip](https://github.com/Azure/azure-container-networking/files/5909799/k.zip)

**Comment by AbelHu** [comment]
It seems like that the file azure-vnet.json.lock is not protected properly. I think that we need azure container networking team's help.

**Comment by zhiweiv** [comment]
Do you know who can help? This has been reported for a long time.

**Comment by AbelHu** [comment]
You are right to file the issue in this repo. We will also ping container networking team to fix it ASAP. cc @keikhara

**Comment by keikhara** [comment]
@aanandr   Can you please take a look at this issue? thanks,.

**Comment by aanandr** [comment]
Tagging Neha - @neaggarwMS

**Comment by zhiweiv** [comment]
Issue not seen recently.
