### ISSUE TITLE
ERROR: failed to allocate gateway (x.x.x.x): No address returned

### ISSUE THREAD

**Issue by jodok** [Azure/azure-container-networking#78]
my docker host has 2 interfaces and i'm using the CNM driver:
 - `eth0` with `10.4.70.11/24`
 - `eth1` with `10.4.71.201` (and in the azure vnet also `10.4.71.11`, `12`, `13`, `14`,... assigned)

when starting a docker container, a bridge name `azure3` on `eth1` and a interface for the container is being created. the container get's an ip from the available ips and i can reach the container from the host and from hosts that are in the `10.4.70.0/24`. so far so good.

however - i can't reach the container from another subnet (and the loadbalancer can't as well). the problem is that the default gateway of the host is `10.4.70.1` which is bound to `eth0`. so the incoming packets will arrive via the `10.4.71.0/24` subnet on `eth1` but it will try to send back the packets on `eth0`.

so i tried to pass the default gateway for the docker container (`docker-compose.yml`):

```
   ...
    networks:
      crate:
        ipv4_address: 10.4.71.11

networks:
  crate:
    driver: azure-vnet
    ipam:
      driver: azure-vnet
      config:
        - subnet: 10.4.71.0/24
          gateway: 10.4.71.1
```

this yields in an error: `ERROR: failed to allocate gateway (10.4.71.1): No address returned`.
the logfile shows:

```
Nov 08 18:25:27 docker-1 azure-vnet-plugin[12111]: 2017/11/08 18:25:27 [ipam] Requesting address with address:10.4.71.1 options:map[azure.address.type:gateway azure.address.id:].
Nov 08 18:25:27 docker-1 azure-vnet-plugin[12111]: 2017/11/08 18:25:27 [ipam] Address request completed with address:<nil> err:Address not found.
Nov 08 18:25:27 docker-1 azure-vnet-plugin[12111]: 2017/11/08 18:25:27 [azure-vnet-ipam] Sent *cnm.errorResponse &{Err:Address not found}.
```

the second approach i tried was modifying the routing table of the host so that traffic originating from the `10.4.71.0` ips is being sent over `eth1`. i created a second route table that sends the traffic from that ip back to that gateway

```
ip route add 10.4.71.0/24 dev azure3 src 10.4.71.201 table 2
ip route add default via 10.4.71.1 dev azure3 table 2
ip rule add from 10.4.71.201/32 table 2
ip rule add to 10.4.71.201/32 table 2
```

after that the main ip (`10.4.71.201`) is reachable from other subnets. but the ip's inside the docker containers are still not reachable.

another problem is that `azure-vnet-plugin` also wipes this routing table and i need to create it again.

what's the best/correct/working approach to get CNM working with two interfaces? how to properly set up routing?

**Comment by sharmasushant** [comment]
@jodok We can take a look, but the return packets not being sent on the same NIC is possibly due to the default weak host routing in the Linux. I am not sure if this issue is specific to the container scenario. Have you looked into setting up strong host routing?

**Comment by jodok** [comment]
ehat do you mean with "strong routing"? creating a route table in the azure portal an route an entire subnet to the host interface?

**Comment by saiyan86** [comment]
Closing stale issue. Can revisit later if anything changes.
