### ISSUE TITLE
Containers in the CNM managed space can't be reached by loadbalancer, can't access internet

### ISSUE THREAD

**Issue by jodok** [Azure/azure-container-networking#79]
after the issues described in https://github.com/Azure/azure-container-networking/issues/78 i decided to go with a simple approach and use only one subnet. Everything works as expected, the only issue is that the container isn't reachable by the azure loadbalancer and also can't access the internet.

Docker hosts:
 - subnet `10.4.70.0/24`
 - docker-1: ip `10.4.70.201` (ips `.11`, `.12`, `.13`, `.14`) as secondary ips in azure portal
 - docker-2: ip `10.4.70.202` (ips `.21`, `.22`, `.23`, `.24`) as secondary ips in azure portal

What works:
- Docker containers on both hosts can connect to each other.
- Hosts on different subnets (e.g. 10.4.69.0/24) can connect to the host ip (`.201`) and also to the containers
- Load balancer can connect to the host ip (`.201`)
- Docker container has connectivity to other subnets
- DNS resolution inside docker container

What doesn't work:
- Load balancer can't connect to services running on the container ips (`.11`,...)
- Docker containers have no connectivity to the internet

**Comment by sharmasushant** [comment]
@jodok For azure loadbalancer, you need to create load balancer such that it load balances traffic on the ip addresses you want. By default, the traffic is only forwarded to the primary ip address that is assigned to the VM interface.

For internet not being accessible from containers, it is a known behavior in our cnm plugin. We are working on getting a change out that will make internet connectivity work. I will provide an update in few days.

**Comment by jodok** [comment]
thanks @sharmasushant!
looking forward to the internet connectivity solution.
on the loadbalancer - i've created it to connect to the secondary ip addresses - but this didn't work either.

**Comment by psathh** [comment]
@sharmasushant 
any news on the Internet connectivity solution? I am trying to connect to an azure database from a docker container connected to an azure vnet using the cnm plugin,
VNET connectivity is working - connectivity to other vnets too, but not to the public azure SQL-Server address/ip.

**Comment by sharmasushant** [comment]
@psathh The native support in CNM for internet connectivity may take a little bit more time. However, if you associate a public-ip with your secondary CA, you will be able to reach internet from the container that gets that secondary IP. This may not be ideal, but may be something that you can use to unblock yourself.

**Comment by psathh** [comment]
@sharmasushant 
thanks for the quick feedback and idea. At the moment I am starting the Container with 2 docker network interfaces - the default interface has internet connectivity and the azure vnet (via CNM) provides the connectivity to the VNET.
I have successfully tested connectivity to an azure database and the vnet with this, but still looking forward to an easier CNM-solution with native Support for Internet connectivity.

**Comment by saiyan86** [comment]
Closing stale issue. Can revisit later if anything changes.
