### ISSUE TITLE
flannel network

### ISSUE THREAD

**Issue by monaminor** [Azure/azure-container-networking#801]
**What happened:** 

flannel is not able to run in AKS

**What you expected to happen:**  

pod to pod communication, pod to service, pod to node communication should happens through flannel on aks

**How to reproduce it:**  

install AKS and run flannel manifest file.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
kubernetes 1.18

**Operating System (Linux/Windows):**  
linux

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**
5.3 azure

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]

there is azure-cni is bydefault installed in aks. but wanted to use flannel for kubernetes networking.
how to delete/disable azure cni from running aks.
how to get to know that pod pod communication is happening through flannel/azure-cni?

**Comment by jsturtevant** [comment]
For AKS specific questions try: https://github.com/Azure/AKS

AFAIK, AKS has limited support of additonal CNI's: https://github.com/Azure/AKS/issues/589.  If you have the requirements for other CNI's you might look at cluster api for azure: https://github.com/kubernetes-sigs/cluster-api-provider-azure
