### ISSUE TITLE
CNI NetworkPolicy support

### ISSUE THREAD

**Issue by edevil** [Azure/azure-container-networking#81]
I have installed a Kubernetes cluster that makes use of the azure vnet and ipam CNI plugins. However, they don't seem to support the NetworkPolicy functionality in order to manage accessibility between containers through kubernetes configuration. Am I right?

Are we supposed to use another tool like Calico for this NetworkPolicy functionality, do they work well together?

Thank you.

**Comment by sharmasushant** [comment]
@edevil You are right that Azure CNI currently do not support specifying network policies via kubernetes configuration. We are planning to add that in our next milestone.
If you are using acs-engine, then you can either specify calico or azure-cni in the cluster-configuration. 
If you are managing your clusters yourself, then you may be able to get both of them to work together. Unfortunately, we have not tested the scenario where both are being used in the cluster.

**Comment by edevil** [comment]
@sharmasushant Thank you for the clarification.

**Comment by dennis-benzinger-hybris** [comment]
@sharmasushant, quick question regarding your comment "We are planning to add that in our next milestone.".

Since which version are network policies supported?
