### ISSUE TITLE
Errors while configuring Azure CNI with DC/OS

### ISSUE THREAD

**Issue by jrx** [Azure/azure-container-networking#82]
Hi, 

I tried to setup the CNI plugin for Azure using Mesosphere DC/OS. For that I adapted the example from the following guide: https://github.com/Azure/azure-container-networking/blob/master/docs/cni.md

The binaries used are from this package: https://github.com/Azure/azure-container-networking/releases/download/v0.91/azure-vnet-cni-linux-amd64-v0.91.tgz

- The files `azure-vnet` and `azure-vnet-ipam` are placed in the directory `/opt/mesosphere/active/cni/`
- The configuration `azure-vnet.cni` is placed under `/opt/mesosphere/etc/dcos/network/cni/` and has the following content:

```
{
  "cniVersion": "0.2.0",
  "name": "azure",
  "type": "azure-vnet",
  "master": "eth0",
  "bridge": "azure0",
  "logLevel": "debug",
  "ipam": {
    "type": "azure-vnet-ipam",
    "environment": "azure"
  }
}
```

The CNI plugins gets loaded, but it seems like, it's not able to allocate IP addresses from the local/private interface `eth0`:

/var/log/azure-vnet.log:
```
2017/12/04 15:45:53 [cni] Calling plugin azure-vnet-ipam ADD nwCfg:&{CNIVersion:0.2.0 Name:azure Type:azure-vnet Mode: Master:eth0 Bridge:azure0 LogLevel:debug LogTarget: Ipam:{Type:azure-vnet-ipam Environment:azure AddrSpace: Subnet: Address: QueryInterval:}}.
2017/12/04 15:45:54 [cni] Plugin azure-vnet-ipam returned result:<nil>, err:Failed to allocate address: No available addresses.
2017/12/04 15:45:54 [azure-vnet] Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses.
2017/12/04 15:45:54 [cni-net] ADD command completed with result:<nil> err:Failed to allocate pool: Failed to delegate: Failed to allocate address: No available addresses.
2017/12/04 15:45:54 [cni-net] Plugin stopped.

```

/var/log/azure-vnet-ipam.log:
```
2017/12/04 15:45:54 [ipam] Refreshing address source.
2017/12/04 15:45:54 [ipam] Requesting address with address: options:map[azure.address.id:efd73ce3-eth0].
2017/12/04 15:45:54 [ipam] Address request completed with address:<nil> err:<nil>.
2017/12/04 15:45:54 [azure-vnet-ipam] Failed to allocate address: No available addresses.
```

Full logs attached to this issue:
- [azure-vnet-ipam.log](https://github.com/Azure/azure-container-networking/files/1527914/azure-vnet-ipam.log)
- [azure-vnet.log](https://github.com/Azure/azure-container-networking/files/1527915/azure-vnet.log)

I'm running CentOS 7.4 machines with DC/OS 1.10.2 on Azure. Is there anything else, I need to configure either directly on the nodes or within the Azure Portal to get this running? Any hints appreciated.

Regards,
Jan

**Comment by sharmasushant** [comment]
@jrx you need to add more than one ip addresses to the interface on the VM from the Vnet address space.
Please see how to do that here: 

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface-addresses

powershell: https://docs.microsoft.com/en-us/powershell/module/azurerm.network/add-azurermnetworkinterfaceipconfig?toc=%2Fazure%2Fvirtual-network%2Ftoc.json&view=azurermps-5.0.0

You can also add more private ip-addresses to an interface from portal.

**Comment by jrx** [comment]
@sharmasushant Many thanks! Yes, now it works perfectly fine. Having more than one IP address on the interface, fixed it. :)

**Comment by guhuajun** [comment]
@sharmasushant Is it possible to get IP addresses without pre-allocataing them?

**Comment by sharmasushant** [comment]
@guhuajun That is not possible today. If you can make calls to azure from your VM, then you can allocate more IPs as needed, but that will require you to create a service principal that you can use from within the VM.

**Comment by guhuajun** [comment]
@sharadagarwal Thanks for updating! This solution works fine in Azure Global.
By the way, is azure-vnet compatible with Azure China (code name, mooncake) or Azure Stack?

**Comment by sharmasushant** [comment]
This works in mooncake and all other national clouds.

**Comment by ashutoshishere04** [comment]
@sharmasushant can we increase ip addresses using mas environment, after node is already a part of cluster?
