### ISSUE TITLE
Seeing "index out of range" error

### ISSUE THREAD

**Issue by fayizk1** [Azure/azure-container-networking#85]
I am seeing following errors on few nodes. 

Plugin Version: 0.91

config:
```

{
  "cniVersion": "0.3.1",
  "name": "azure",
  "type": "azure-vnet",
  "master": "eth0",
  "bridge": "azure0",
   "mode": "bridge",
  "logLevel": "info",
  "ipam": {
    "type": "azure-vnet-ipam",
    "environment": "azure"
  }
}
```

```
2017/12/16 12:40:52 [cni-net] ADD command completed with result:IP:[{Version:4 Interface:<nil> Address:{IP:10.170.128.108 Mask:ffff8000} Gateway:10.170.128.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.170.128.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2017/12/16 12:40:52 [cni] Recovered panic: runtime error: index out of range goroutine 1 [running]:
github.com/Azure/azure-container-networking/cni.(*Plugin).Execute.func1(0xc42011fef0)
	/go/src/github.com/Azure/azure-container-networking/cni/plugin.go:94 +0xbc
panic(0x674a60, 0x804490)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/Azure/azure-container-networking/network.(*networkManager).addBridgeRules(0xc420014500, 0xc42001e900, 0xc420019280, 0xc420011660, 0x6, 0xc420011740, 0x6, 0x0, 0xf)
	/go/src/github.com/Azure/azure-container-networking/network/network_linux.go:155 +0x4eb
github.com/Azure/azure-container-networking/network.(*networkManager).connectExternalInterface(0xc420014500, 0xc42001e900, 0xc420084d80, 0x0, 0x0)
	/go/src/github.com/Azure/azure-container-networking/network/network_linux.go:255 +0x542
github.com/Azure/azure-container-networking/network.(*networkManager).newNetworkImpl(0xc420014500, 0xc420084d80, 0xc42001e900, 0x5, 0x82a160, 0xc42011f8a0)
	/go/src/github.com/Azure/azure-container-networking/network/network_linux.go:36 +0xa2
github.com/Azure/azure-container-networking/network.(*networkManager).newNetwork(0xc420014500, 0xc420084d80, 0x0, 0x0, 0x0)
	/go/src/github.com/Azure/azure-container-networking/network/network.go:149 +0x1f3
github.com/Azure/azure-container-networking/network.(*networkManager).CreateNetwork(0xc420014500, 0xc420084d80, 0x0, 0x0)
	/go/src/github.com/Azure/azure-container-networking/network/manager.go:163 +0x95
github.com/Azure/azure-container-networking/cni/network.(*netPlugin).Add(0xc4200d6620, 0xc42001c230, 0x0, 0x0)
	/go/src/github.com/Azure/azure-container-networking/cni/network/network.go:200 +0x18aa
github.com/Azure/azure-container-networking/cni.(PluginApi).Add-fm(0xc42001c230, 0xc4200114a6, 0x5)
	/go/src/github.com/Azure/azure-container-networking/cni/plugin.go:112 +0x39
github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc420018a00, 0xc42001c230, 0x7e1060, 0xc420017620, 0xc42005feb0, 0x0, 0xc420020000)
	/go/src/github.com/containernetworking/cni/pkg/skel/skel.go:167 +0x19f
github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc420018a00, 0xc42005feb0, 0xc42005fe98, 0x7e1060, 0xc420017620, 0xc42005fe68)
	/go/src/github.com/containernetworking/cni/pkg/skel/skel.go:178 +0x2f8
github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0xc42005feb0, 0xc42005fe98, 0x7e1060, 0xc420017620, 0xc420017620)
	/go/src/github.com/containernetworking/cni/pkg/skel/skel.go:215 +0xed
github.com/Azure/azure-container-networking/cni.(*Plugin).Execute(0xc42000e040, 0x7e0f20, 0xc4200d6620, 0x0, 0x0)
	/go/src/github.com/Azure/azure-container-networking/cni/plugin.go:112 +0x127
main.main()
	/go/src/github.com/Azure/azure-container-networking/cni/network/plugin/main.go:35 +0x328

2017/12/16 12:40:52 [cni-net] Plugin stopped.
```

**Comment by sharmasushant** [comment]
@fayizk1 Can you please share the following log files:  /var/log/azure-vnet.log and /var/log/azure-vnet-ipam.log

**Comment by sharmasushant** [comment]
@fayizk1 Is it still happening with latest CNI? If yes, can you please share above requested two log files? If not, we should close the Issue.

**Comment by kingliantop** [comment]
I encountered the same error with CentOS 7.4, no log files like /var/log/azure-vnet.log or /var/log/azure-vnet-ipam.log on centOS, the error messages from /var/log/messages like below:

Mar 30 16:14:43 localhost systemd: Started libcontainer container a05279f6193142478f5d5ada58c0910820aad32678254535fc484f8ed1116b28.
Mar 30 16:14:43 localhost systemd: Starting libcontainer container a05279f6193142478f5d5ada58c0910820aad32678254535fc484f8ed1116b28.
Mar 30 16:14:43 localhost kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Mar 30 16:14:43 localhost kubelet: 2018/03/30 16:14:43 File not exist /var/run/AzureCNITelemetry.json
Mar 30 16:14:43 localhost kubelet: 2018/03/30 16:14:43 GetReport state file didn't exist. Setting flag to true
Mar 30 16:14:43 localhost kubelet: panic: runtime error: index out of range
Mar 30 16:14:43 localhost kubelet: goroutine 1 [running]:
Mar 30 16:14:43 localhost kubelet: github.com/Azure/azure-container-networking/telemetry.(*Report).GetOSDetails(0xc4200d0640)
Mar 30 16:14:43 localhost kubelet: /go/src/github.com/Azure/azure-container-networking/telemetry/telemetry_linux.go:112 +0x55c
Mar 30 16:14:43 localhost kubelet: github.com/Azure/azure-container-networking/telemetry.(*ReportManager).GetReport(0xc420018340, 0x6ea639, 0x3, 0x70d874, 0x6)
Mar 30 16:14:43 localhost kubelet: /go/src/github.com/Azure/azure-container-networking/telemetry/telemetry.go:138 +0xa3
Mar 30 16:14:43 localhost kubelet: main.main()
Mar 30 16:14:43 localhost kubelet: /go/src/github.com/Azure/azure-container-networking/cni/network/plugin/main.go:65 +0x6e6
Mar 30 16:14:43 localhost kubelet: E0330 16:14:43.982391   65044 cni.go:259] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Mar 30 16:14:43 localhost kubelet: E0330 16:14:43.982411   65044 cni.go:227] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Mar 30 16:14:43 localhost journal: Shutting down, got signal: Terminated
Mar 30 16:14:44 localhost dockerd-current: time="2018-03-30T16:14:44.035845675Z" level=error msg="containerd: deleting container" error="exit status 1: \"container a05279f6193142478f5d5ada58c0910820aad32678254535fc484f8ed1116b28 does not exist\\none or more of the container deletions failed\\n\""


And my network configure file as below:
{
  "cniVersion": "0.3.1",
  "name": "azure",
  "type": "azure-vnet",
  "master": "eth0",
  "bridge": "azure0",
  "logLevel": "info",
  "ipam": {
    "type": "azure-vnet-ipam",
    "environment": "azure"
  }
}


any idea what's happening? Thanks!

**Comment by tamilmani1989** [comment]
@fayizk1 We are not getting what's the exact issue. The first log you shared looks completely different from the one you shared now. This is not the same issue. Can you please open a different ticket for this? Also if the first issue gets fixed, Please close this ticket.

**Comment by sharmasushant** [comment]
Please open a new issue as suggested by Tamilmani. Closing this one.
