### ISSUE TITLE
run CNM sample with Docker on Azure, can't  run docker 

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-container-networking#92]
HI, 
When I follow the example create an Ubuntu VMM, install docker, vnet plugin, and run sample:
docker run -it --rm --net=azure ubuntu:latest /bin/bash

It shows:
docker: Error response from daemon: No address returned.

The docker network creation is successful:
$ sudo docker network create --driver=azure-vnet --ipam-driver=azure-vnet --subnet=10.1.0.0/24 azure
316fa9ad951081a6b7553b7f51b967e50aa5cdbc3b9124761ed5bd47cf5ab352

anything I miss here?

**Comment by sharmasushant** [comment]
You need to configure secondary IP addresses on the interface. These addresses from the Vnet address space will be assigned to the containers. Here is how you can add secondary IP address to the VM interface:

Powershell: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface-addresses

REST Call: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/createorupdate

Also, ensure that the subnet specified is the correct subnet to which the VM interface belongs.

**Comment by kingliantop** [comment]
@sharmasushant Thanks for the help! If I have 10 containers in one VM, should I manually configure the 10 IPs like this? Will not the vnet-plugin get the IP automatically?

**Comment by sharmasushant** [comment]
@kingliantop You can estimate how many containers you will need in the VM, and can add those many secondary ip addresses before hand. The plugin will not be able to get IP address by itself.

**Comment by kingliantop** [comment]
@sharmasushant  Thanks a lot! I will open another issue for connectivity!

**Comment by guddutopper** [comment]
@kingliantop hi, were you able to assign IPs to your docker containers, I am facing the same issue but I have created secondary IP address on the interface so this should not happen
