### ISSUE TITLE
Using CNM on the docker, the containers can not be reached

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-container-networking#93]
Hi,

I created docker network with azure-vnet-plugin, and created few containers like Ubuntu, nginx, they can't be reached via the VM in the same vNet.

The VM IP: 10.1.0.4
The container alping IP: 10.1.0.7
The test VM IP: 10.1.0.6

steven@myubuntutest:~$ sudo docker run -it --net=azure  alpine
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr 5A:E0:6A:AA:15:50  
          inet addr:10.1.0.7  Bcast:10.1.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
/ # ping 10.1.0.6
PING 10.1.0.6 (10.1.0.6): 56 data bytes

From the VM 10.1.0.6, it can not reach alpine container as well, they are in the same vnet, I tried nginx, the same issue. Any idea or advice?

The more information as below:
vnet-plugin version: 1.0.1

steven@myubuntutest:~$ docker --version
Docker version 17.12.0-ce, build c97c6d6
steven@myubuntutest:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
316fa9ad9510        azure               azure-vnet          local

Thanks a lot!

**Comment by sharmasushant** [comment]
@kingliantop Do you have any firewall or Azure NSGs blocking the traffic? These are the most common reasons we have seen so far. Can you please check?

**Comment by EgoAleSum** [comment]
I have the same issue. Actually, not only I can't reach container, but I can't reach anything from within the container either.

I am using Ubuntu 16.04, with Docker CE 17.12. Plugin version 1.0.2. My VM has two NICs, in two separate subnets. I've tried adding the bridge to either NIC, with the same results.

My containers do get an IP, and they appear to be connected to the VNET.

What doesn't work:
1. From within the container, I cannot ping anything. I can ping the container itself (using the IP from the VNET), but I cannot ping the host, another container, another VM or something on the Internet
2. From the host, I cannot connect to a service running inside the container

My NIC has a NSG attached, but the NSG is allowing all outbound connections. It's also allowing all inbound connections from within the VNET.

**Comment by EgoAleSum** [comment]
Just wondering if there's been an update here. I'll be happy to share my code to reproduce the bug, although it's not much more than just running Docker and the plugin on Ubuntu 16.04.

**Comment by EgoAleSum** [comment]
@sharmasushant Just wondering if there's been an update here. I'll be happy to share my code to reproduce the bug, although it's not much more than just running Docker and the plugin on Ubuntu 16.04.

**Comment by sharmasushant** [comment]
@EgoAleSum Sorry for delay. Let us take it up in the coming week. Looks like may be something to do with multi nic VM. Does the issue repro with single NIC VM for you?

**Comment by EgoAleSum** [comment]
@sharmasushant Thanks. Switching to a single-NIC VM doesn't seem to be working either. It worked for a container, then I stopped it and re-created it, and it stopped working.

**Comment by tamilmani1989** [comment]
There is a problem with ipforwarding in newly created VMs. The following is temporary fix steps.

Set `net.ipv4.ip_forward=1` in /etc/sysctl.conf and reboot your VM. Then create the network using azure-vnet driver and use it.

**Comment by EgoAleSum** [comment]
Hi @tamilmani1989 I've tried what you suggested (enabling IPv4 forwarding), on a multi-NIC VM.

After doing that, I tried running an nginx container on the Azure VNET. I can successfully ping and curl that container from the host VM.

Next step, I created another container running centos to get a shell, in the same Azure VNET. Again, from that container I can ping and curl the nginx container.

However, from the centos container I still can't reach the Internet: I can't ping nor connect to any IP outside of the subnet  on which the Azure VNET plugin is enabled. The two NICs are on two separate subnets, and I can ping the IP of the NIC in the same subnet, but not the other one.

Last test: from the Internet, I cannot reach the container using the public IP associated to that container.

Let me know if you need more details about my setup, although it's fairly standard.

**Comment by tamilmani1989** [comment]
@EgoAleSum Outbound Connection won't work with CNM. Using CNM you can connect to VM/Container within Azure VNET. So earlier you mentioned that container to container communication or container to VM communication is not working. So did it get resolved now?

**Comment by EgoAleSum** [comment]
1. Container-to-container within the same CNM network is working
2. Container-to-host and host-to-container is working, but only if they're within the same VNET (e.g. from a container in a VNET, I can ping the host using the IP of the NIC in the same VNET, but not in another one).
3. Outside-to-container is NOT working, which is the key here for me. A container seems reachable only from within the same VNET. I can't reach this from the Internet.

**Comment by sharmasushant** [comment]
@EgoAleSum Thanks for your patience. In order to reach internet from the containers, the outbound packets have to have the source ip as the one in the ip-config that is primary. This is the current Azure behavior, where by default, the snat is given only on primary ip-config. 

Because of above, there are two options to reach internet from containers
1) you can configure public-ip on each ip-config. This will give you snat on each secondary ip.
2) Add a snat rule in the VM by yourself. The rule will look like following
iptables -t nat -A POSTROUTING  -m addrtype ! --dst-type local ! -d '<vnet-address-space>,' -j MASQUERADE

The above rule will snat the traffic that is going outside the vnet with the primary ip. You can exclude your on-prem space from getting snat'ed if you have that scenario.

**Comment by EgoAleSum** [comment]
So, the container was assigned an IP which also had a public ip (on the same ip-config). However, I added that after the VM was created, so I assume that's why snat wasn't enabled?

Will re-trying that give me full inbound and outbound connectivity between my container and the Internet?

I have destroyed the VM now, but I'd be happy to share my Terraform templates and setup instructions.

PS: I would recommend documenting everything: the need to enable ipv4 forwarding, SNAT, etc :)

**Comment by kingliantop** [comment]
Thanks for you guys workaround! I test container to container, container to VM host, they all work fine, and with public IP assignment to the container, the container can access internet as well.

Yes, I agree all these trivial details should be well documented, the following up issue is the IPAM:

Each time I want to create a container using Azure network driver, I have to create an pre-allocated IP and IP config to the NIC in advance, then the container can be assigned an vnet IP address, do we have any plan to the IPAM automatically to do these things since it is not convenient for the large-scale deployment?  Thanks!

**Comment by guddutopper** [comment]
@kingliantop hi, did you use the CNM plugin to create the azure-vnet network based on this link - https://github.com/Azure/azure-container-networking/blob/master/docs/cnm.md
I am also able to create network but while joining container to the above network, I am facing issues
