### ISSUE TITLE
Does this work with Azure Container Instances (ACI)?

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-container-networking#96]
Can we use these plugins easily with ACI?
Thanks.

**Comment by EgoAleSum** [comment]
While I'm not one of the devs, I would say this is unlikely, as ACI offers you a container and doesn't expose the orchestrator. That is: the complexities that this plugin aims to solve will already be taken care of for you.

**Comment by seanknox** [comment]
As a MSFT staffer I can confirm the above. Networking is completely managed by ACI.

**Comment by ChristianWeyer** [comment]
Thanks!
